### ISSUE TITLE
ReadLock not working correctly

### ISSUE THREAD

**Issue by HansChua** [redisson/redisson#1219]
Hi,

Is this the expected behaviour of the ReadLock from ReadWriteLock?

Clarifying because I did not encounter this in release 3.5.4

There are multiple threads that are trying to lock and unlock the readlock concurrently but I am encountering the "attempt to unlock lock, not locked by current thread by node id" exception.

Here is a rough code sample to replicate the issue.
```java
ExecutorService service;
RReadWriteLock rwlock;
RLock rlock = rwlock.readLock();

for (int i=0; i<10; i++) {
  service.submit (() -> {
    for (int j=0; j<1000; j++) {
      rlock.lock();
      try {
      } finally {
         try {
           rlock.unlock();
         } catch(Exception e) {
            e.printStackTrace();
         }
      }
    }
  });
}
```

The unlock part throws the following exception even though they're all read locks.
```java
java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: e3784ec0-94c6-4138-ac2a-1865eb79c93d thread-id: 21
	at org.redisson.RedissonLock.unlock(RedissonLock.java:367)
	at Main.lambda$0(Main.java:25)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
 ```

**Comment by hans123456** [comment]
Hi @mrniko 

Can I bother you to check if this is the expected behaviour of the ReadLock?

**Comment by mrniko** [comment]
Hi! Unfortunately, I can't reproduce your problem. Nothing has changed in ReadWriteLock behaviour.

Here is my test code:
```java
    @Test
    public void test() throws InterruptedException {
        ExecutorService service = Executors.newFixedThreadPool(10);
        RReadWriteLock rwlock = redisson.getReadWriteLock("test");
        RLock rlock = rwlock.readLock();

        for (int i = 0; i < 100; i++) {
            service.submit(() -> {
                for (int j = 0; j < 1000; j++) {
                    rlock.lock();
                    try {
                    } finally {
                        try {
                            rlock.unlock();
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                }
            });
        }
        
        service.shutdown();
        
        assertThat(service.awaitTermination(1, TimeUnit.MINUTES)).isTrue();
    }
```

**Comment by hans123456** [comment]
Hi @mrniko

Thank you for replying.

It seems that it is encountered when there is a colon in the lock key name or if the lock is from a map.

```Java
RReadWriteLock rwlock = redisson.getReadWriteLock("test:test");
```

```Java
RReadWriteLock rwlock = redisson.getMap ("test").getReadWriteLock("test");
```

**Comment by mrniko** [comment]
redisson.getReadWriteLock will have a key like this: "test:83293810291:key" which don't match with "test:test"

**Comment by hans123456** [comment]
yes they are not the same, but were you able to replicate the issue with keys have colons?

**Comment by mrniko** [comment]
I'm afraid there are many places where colons are used.

**Comment by hans123456** [comment]
I wonder why I wasn't encounter the issue in version 3.5.4

With a single readlock named "test:test", it should't encounter lock / unlock problems because they are all readlocks.

```Java
RReadWriteLock rwlock = redisson.getReadWriteLock("test:test");
```

**Comment by mrniko** [comment]
Could you check if it works with 3.5.5?

**Comment by hans123456** [comment]
Hi, in 3.5.5 I am encountering a different error

Code
```Java
ExecutorService service = Executors.newCachedThreadPool();
RReadWriteLock rwlock = redisson.getReadWriteLock("test");
RLock rlock = rwlock.readLock();

for (int i=0; i<3; i++) {
  service.submit (() -> {
    for (int j=0; j<1000; j++) {
      rlock.lock();
      try {
      } finally {
         try {
           rlock.unlock();
         } catch(Exception e) {
            e.printStackTrace();
         }
      }
    }
  });
}

service.shutdown();
service.awaitTermination(2, TimeUnit.MINUTES);
```

Error
```Java
org.redisson.client.RedisException: CROSSSLOT Keys in request don't hash to the same slot. channel: [id: 0xa478782a, L:/127.0.0.1:60560 - R:/127.0.0.1:6381] command: (EVAL), params: [local mode = redis.call('hget', KEYS[1], 'mode'); if (mode == false) then redis.call('publish', KEYS..., 4, test:test, redisson_rwlock:{test:test}, {test:test}:4a16fd19-3a29-493f-8dbe-ba434d5f286a:20:rwlock_timeout, {test, 0, 4a16fd19-3a29-493f-8dbe-ba434d5f286a:20]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:243)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:103)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
```

**Comment by mrniko** [comment]
That's strange, since I'm unable to reproduce it with 3.5.5 too.

**Comment by mrniko** [comment]
Have you checked your Redis setup? I think there is a problem with it.

**Comment by hans123456** [comment]
Is there a minimum supported Redis version?

I'm using the following setups
* docker with version 3.1
* Redis for windows, version 3

**Comment by hans123456** [comment]
reinstalled Docker, redis-4.0.1-alphine.tar

```
docker load redis-4.0.1-alphine.tar
docker run --name redis -p 6379:6379 -d redis-4.0.1-alphine redis-server --save "" --appendonly no
docker star redis
```

**Comment by hans123456** [comment]
I tried using the RedisRunner in the test folder to configure the Redis.

I am using version 3.0.504 to run the Redis runner but still encountering the error :/

**Comment by hans123456** [comment]
Hi @mrniko,

Could I bother you again to try this test case?

```Java
@Test
public void test() throws InterruptedException {
  ExecutorService service = Executors.newFixedThreadPool(10);
  RReadWriteLock rwlock = redisson.getMap("test").getReadWriteLock("test");
  RLock rlock = rwlock.readLock();

  List<Callable<Void>> callables = new ArrayList<>();
  for (int i = 0; i < 100; i++) {
    callables.add(() -> {
      for (int j = 0; j < 1000; j++) {
        rlock.lock();
        try {
        } finally {
          rlock.unlock();
        }
      }
      return null;
    });
  }

  List<Future<Void>> futures = service.invokeAll(callables);
  for (Future<Void> future : futures) {
    assertThatCode(future::get).doesNotThrowAnyException();
  }

  service.shutdown();

  assertThat(service.awaitTermination(5, TimeUnit.MINUTES)).isTrue();
}
```

**Comment by mrniko** [comment]
I confirm, it's a bug. Thanks for testcase!

**Comment by mrniko** [comment]
Fixed

**Comment by domgomIW** [comment]
I'm still seeing the IllegalMonitorStateException when I run the test of https://github.com/redisson/redisson/issues/1219#issuecomment-358971804 under the latest redisson 3.11.4

**Comment by mrniko** [comment]
@domgomIW 

Could you provide any sample code to reproduce that?

**Comment by domgomIW** [comment]
@mrniko just the test of the comment https://github.com/redisson/redisson/issues/1219#issuecomment-358971804

```
@Test
public void test() throws InterruptedException {
  ExecutorService service = Executors.newFixedThreadPool(10);
  RReadWriteLock rwlock = redisson.getMap("test").getReadWriteLock("test");
  RLock rlock = rwlock.readLock();

  List<Callable<Void>> callables = new ArrayList<>();
  for (int i = 0; i < 100; i++) {
    callables.add(() -> {
      for (int j = 0; j < 1000; j++) {
        rlock.lock();
        try {
        } finally {
          rlock.unlock();
        }
      }
      return null;
    });
  }

  List<Future<Void>> futures = service.invokeAll(callables);
  for (Future<Void> future : futures) {
    assertThatCode(future::get).doesNotThrowAnyException();
  }

  service.shutdown();

  assertThat(service.awaitTermination(5, TimeUnit.MINUTES)).isTrue();
}
```
I also tried the concurrency levels of the test that you added to the commit
https://github.com/redisson/redisson/commit/3db1c46c420181515d054b987c10968dd23640bf
and with those concurrency levels (10 callables with 10 locks per callable) I don't get any errors.
But when you change to 100 callables with 1000 locks the error comes back.

**Comment by mrniko** [comment]
@domgomIW 

Unable to reproduce the issue using your test case.

**Comment by domgomIW** [comment]
@mrniko https://github.com/domgomIW/read-lock-example executed on a 2015 Macbook i5 16Gb RAM.

**Comment by tomaspiaggio** [comment]
@domgomIW have you made any progress? I seem to be having a similar issue. Maybe I can provide a different test in which this fails.

**Comment by usultis** [comment]
I see the same issue in our code(using 3.11.4)

**Comment by mrniko** [comment]
@tomaspiaggio 

> Maybe I can provide a different test in which this fails.

that would be great

**Comment by tomaspiaggio** [comment]
I'm trying to write a RoundRobin strategy using the `RBlockingQueue`. I have multiple instances serving this information. The lock for multiple things. The first one is to ensure that the same information is not being served more than once. Another one is because on initialization, the instances load information from the database, clearing what already exists to ensure consistency. If I didn't have the lock, there would be repeated values in the queue. 

I'm using the following method to restore redis' information with the one found in the database:
```scala
private def restoreConsistency(values: util.Collection[Stream]): Unit = withLock {
    redisQueue.clear()
    redisQueue.addAll(values)
}
```
The previous method is called on service initialization once. The `Stream` object is my own implementation. It is irrelevant as it only contains information.

Note that I made another method which a block of code can be passed to it and it tries to get the lock and execute the block, returning the result if there is one:

```scala
private def withLock[T](block: => T): T = {
  lock.lock(5, TimeUnit.SECONDS)
  val result: T = block
  lock.unlock()
  result
}
```

I have two different tests with two different outputs that might help. The first test is a simple `RLock` test.:

```scala
"RLock" should "lock" in {
  // this is just a helper that gets the configuration used in this service
  val redisson: RedissonClient = RedisFlyweightConfiguration.getRedisClient

  println("before getting first lock")
  val lock: RLock = redisson.getLock("lock")
  println("after getting first lock")
  lock.lock(10, TimeUnit.SECONDS)
  println("after first locked")

  val t: Thread = new Thread(() => {
    println("before getting second lock")
    val lock1: RLock = redisson.getLock("lock")
    println("after getting second lock")
    lock1.lock(2, TimeUnit.SECONDS)
    println("after second locked")
    lock1.unlock()
    println("after second unlocked")
  })

  t.start()

  lock.unlock()
  println("after first unlocked")

  Thread.sleep(10000)

  t.join()
  redisson.shutdown()
}
```

This is the output: 

```
Exception in thread "main" org.redisson.client.RedisException: ERR Error running script (call to f_9401052d872adfd0179ef8c8e8c028512707629a): @user_script:1: WRONGTYPE Operation against a key holding the wrong kind of value . channel: [id: 0x6f260f0a, L:/127.0.0.1:52806 - R:0.0.0.0/0.0.0.0:6379] command: (EVAL), params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, map-service, 5000, d35816a2-6346-4d3a-aaec-bd34621ca1dc:11]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:365)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:209)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:147)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

Additionally, I wrote another test that looks very similar, but crashes with a different error. Take the following test: 

```scala
"WorkerStreamProviderImpl" should "add a stream" in {
  clearQueue("test-queue") // this line ensures that there's nothing in the queue
  val testStream = addStream("test-queue") // fails here -> creating a new object in the queue
  // the following is not reached
  WorkerStreamProviderImpl.streams.find(_.id == testStream.id) match {
    case Some(value) => value.equals(testStream) shouldBe true
    case None => fail("The VideoStream does not exist in the streams list.")
  }
}
```

The `addStream` method adds a `Stream` object to a local `HashMap` and calls `restoreConsistency ` with the values. This is the error I get: 

```
An exception or error caused a run to abort. 
java.lang.ExceptionInInitializerError
	at business.workers.WorkerStreamProviderTest.addStream(WorkerStreamProviderTest.scala:15)
	at business.workers.WorkerStreamProviderTest.$anonfun$new$1(WorkerStreamProviderTest.scala:24)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike.invokeWithFixture$1(FlatSpecLike.scala:1680)
	at org.scalatest.FlatSpecLike.$anonfun$runTest$1(FlatSpecLike.scala:1692)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FlatSpecLike.runTest(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpecLike.runTest$(FlatSpecLike.scala:1674)
	at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike.$anonfun$runTests$1(FlatSpecLike.scala:1750)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FlatSpecLike.runTests(FlatSpecLike.scala:1750)
	at org.scalatest.FlatSpecLike.runTests$(FlatSpecLike.scala:1749)
	at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1685)
	at org.scalatest.Suite.run(Suite.scala:1147)
	at org.scalatest.Suite.run$(Suite.scala:1129)
	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike.$anonfun$run$1(FlatSpecLike.scala:1795)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FlatSpecLike.run(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpecLike.run$(FlatSpecLike.scala:1793)
	at org.scalatest.FlatSpec.run(FlatSpec.scala:1685)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1346)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1340)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1340)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
Caused by: java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: 78f4e83a-aeca-4c13-adbb-0af7b28a260c thread-id: 1
	at org.redisson.RedissonLock.lambda$unlockAsync$3(RedissonLock.java:577)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82)
	at org.redisson.command.RedisExecutor.handleReference(RedisExecutor.java:505)
	at org.redisson.command.RedisExecutor.handleSuccess(RedisExecutor.java:498)
	at org.redisson.command.RedisExecutor.handleResult(RedisExecutor.java:483)
	at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:469)
	at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:187)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82)
	at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:454)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:449)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:380)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:209)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:147)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

The thing that makes me think that this is a problem with the library is that every piece of my testing code is executing in sequence. I'm not creating new threads. 

Hope this helps.

All these tries were made with scala 2.12.7, and redisson 3.11.4.

**Comment by mrniko** [comment]
@tomaspiaggio 

Thanks for shared tests!

Unable to reproduce first case:

```java
    @Test
    public void test1() throws InterruptedException {
          // this is just a helper that gets the configuration used in this service
          System.out.println("before getting first lock");
          RLock lock = redisson.getLock("lock");
          System.out.println("after getting first lock");
          lock.lock(10, TimeUnit.SECONDS);
          System.out.println("after first locked");

          Thread t = new Thread(() -> {
            System.out.println("before getting second lock");
            RLock lock1 = redisson.getLock("lock");
            System.out.println("after getting second lock");
            lock1.lock(2, TimeUnit.SECONDS);
            System.out.println("after second locked");
            lock1.unlock();
            System.out.println("after second unlocked");
          });

          t.start();

          lock.unlock();
          System.out.println("after first unlocked");

          Thread.sleep(10000);

          t.join();
    }
```

The error you get tells that you're share the same lock name with other Redisson object.

As for second test. Can you re-write it as standalone?

**Comment by tomaspiaggio** [comment]
@mrniko Here's the standalone test: 

```scala
"Standalone test" should "work" in {
  import scala.collection.JavaConverters._

  // this creates a map only containing the Stream below
  val map = new HashMap[Int, Stream]() + (0 -> new StreamImpl(0, s"${UUID.randomUUID()}"))

  // getting the redis queue
  val redisQueue: RBlockingQueue[Stream] = RedisFlyweightConfiguration.getRedisClient.getBlockingQueue("some-service")

  // getting the lock
  val lock: RLock = RedisFlyweightConfiguration.getRedisClient.getLock("some-service")

  def withLock[T](block: => T): T = {
    lock.lock(5, TimeUnit.SECONDS)
    val result: T = block
    lock.unlock()
    result
  }

  def restoreConsistency(values: util.Collection[Stream]): Unit = withLock {
    redisQueue.clear()
    redisQueue.addAll(values)
  }

  restoreConsistency(map.values.asJavaCollection)
}
```

I'm still getting the following error: 

```
ERR Error running script (call to f_3ffe249c16dee540ac8ab32e39bd408626b9aff7): @user_script:1: WRONGTYPE Operation against a key holding the wrong kind of value . channel: [id: 0x72189865, L:/127.0.0.1:61712 - R:0.0.0.0/0.0.0.0:6379] command: (EVAL), params: [if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) then return nil;end; local counter = redis.call('h..., 2, some-service, redisson_lock__channel:{some-service}, 0, 5000, 38d47696-41b3-4b30-9cb3-4db828bd9b7a:1]
org.redisson.client.RedisException: ERR Error running script (call to f_3ffe249c16dee540ac8ab32e39bd408626b9aff7): @user_script:1: WRONGTYPE Operation against a key holding the wrong kind of value . channel: [id: 0x72189865, L:/127.0.0.1:61712 - R:0.0.0.0/0.0.0.0:6379] command: (EVAL), params: [if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) then return nil;end; local counter = redis.call('h..., 2, some-service, redisson_lock__channel:{some-service}, 0, 5000, 38d47696-41b3-4b30-9cb3-4db828bd9b7a:1]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:365)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:209)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:147)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Hope this helps. Could you please elaborate when you said: 
> The error you get tells that you're share the same lock name with other Redisson object.

I have only one instance of `Redisson` object. That's what the `RedisFlyweightConfiguration.getRedisClient` do, it creates an object and provides the instance for the services that need it. If what you mean is another `Redisson` object in another machine, then how would I lock anything?

**Comment by mrniko** [comment]
In your example getBlockingQueue("some-service") and getLock("some-service") have the same name. This is wrong

**Comment by tomaspiaggio** [comment]
Sorry @mrniko my bad. I changed the code to look like this: 

```scala
"Standalone test" should "work" in {
  import scala.collection.JavaConverters._

  // this creates a map only containing the Stream below
  val map = new HashMap[Int, VideoStream]() + (0 -> new VideoStreamImpl(0, s"${UUID.randomUUID()}"))

  // getting the redis queue
  val redisQueue: RBlockingQueue[VideoStream] = RedisFlyweightConfiguration.getRedisClient.getBlockingQueue("some service")

  // getting the lock
  val lock: RLock = RedisFlyweightConfiguration.getRedisClient.getLock("some service's lock")

  def withLock[T](block: => T): T = {
    lock.lock(5, TimeUnit.SECONDS)
    val result: T = block
    lock.unlock()
    result
  }

  def restoreConsistency(values: util.Collection[VideoStream]): Unit = withLock {
    redisQueue.clear()
    redisQueue.addAll(values)
  }

  restoreConsistency(map.values.asJavaCollection)
}
```
and got the following error:
```
An exception or error caused a run to abort: io.netty.util.internal.StringUtil.indexOfNonWhiteSpace(Ljava/lang/CharSequence;I)I 
java.lang.NoSuchMethodError: io.netty.util.internal.StringUtil.indexOfNonWhiteSpace(Ljava/lang/CharSequence;I)I
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parse(UnixResolverDnsServerAddressStreamProvider.java:193)
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.<init>(UnixResolverDnsServerAddressStreamProvider.java:94)
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.<init>(UnixResolverDnsServerAddressStreamProvider.java:128)
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parseSilently(UnixResolverDnsServerAddressStreamProvider.java:70)
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$1.provider(DnsServerAddressStreamProviders.java:57)
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$1.<init>(DnsServerAddressStreamProviders.java:36)
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.<clinit>(DnsServerAddressStreamProviders.java:34)
	at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:208)
	at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:160)
	at org.redisson.connection.SingleConnectionManager.<init>(SingleConnectionManager.java:34)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:194)
	at org.redisson.Redisson.<init>(Redisson.java:120)
	at org.redisson.Redisson.create(Redisson.java:160)
	at persistance.memory.RedisFlyweightConfiguration$.$anonfun$redisson$1(RedisFlyweightConfiguration.scala:22)
	at scala.util.Try$.apply(Try.scala:209)
	at persistance.memory.RedisFlyweightConfiguration$.retry$1(RedisFlyweightConfiguration.scala:29)
	at persistance.memory.RedisFlyweightConfiguration$.retryExponentialBackoff(RedisFlyweightConfiguration.scala:34)
	at persistance.memory.RedisFlyweightConfiguration$.<init>(RedisFlyweightConfiguration.scala:22)
	at persistance.memory.RedisFlyweightConfiguration$.<clinit>(RedisFlyweightConfiguration.scala)
	at business.workers.WorkerStreamProviderTest.$anonfun$new$6(WorkerStreamProviderTest.scala:64)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike.invokeWithFixture$1(FlatSpecLike.scala:1680)
	at org.scalatest.FlatSpecLike.$anonfun$runTest$1(FlatSpecLike.scala:1692)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FlatSpecLike.runTest(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpecLike.runTest$(FlatSpecLike.scala:1674)
	at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike.$anonfun$runTests$1(FlatSpecLike.scala:1750)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FlatSpecLike.runTests(FlatSpecLike.scala:1750)
	at org.scalatest.FlatSpecLike.runTests$(FlatSpecLike.scala:1749)
	at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1685)
	at org.scalatest.Suite.run(Suite.scala:1147)
	at org.scalatest.Suite.run$(Suite.scala:1129)
	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike.$anonfun$run$1(FlatSpecLike.scala:1795)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FlatSpecLike.run(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpecLike.run$(FlatSpecLike.scala:1793)
	at org.scalatest.FlatSpec.run(FlatSpec.scala:1685)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1346)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1340)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1340)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```
I've noticed that it changes from version to version. In version 3.11.1 I didn't get any errors.

**Comment by mrniko** [comment]
> java.lang.NoSuchMethodError: io.netty.util.internal.StringUtil.indexOfNonWhiteSpace

Make sure you don't have different versions of netty in classpath

**Comment by chowtin** [comment]
this error happens in 3.11.5. 
which version fixed this issue?
```
attempt to unlock lock, not locked by current thread by node id: e5dd1158-244f-43cc-a7ae-6bd34c62c783 thread-id: 70
```

**Comment by mrniko** [comment]
@chowtin 

Could you provide test code to reproduce it?

**Comment by shihua-guo** [comment]
I am a beginner of Redission.
**this error happens in 3.11.6.
This is situation1:**
```

    public static void main(String[] args) {
        Config config = new Config();
        SingleServerConfig singleServerConfig = config.useSingleServer();
        singleServerConfig.setAddress("redis://10.16.1.150:6379");
        singleServerConfig.setDatabase(0);
        singleServerConfig.setConnectionMinimumIdleSize(20);

        System.out.println("lock");
        final RedissonClient redissonClient = Redisson.create(config);
        final RLock lock = redissonClient.getLock("lock");
        lock.lock(10,TimeUnit.SECONDS);
        try{
            try {
                Thread.sleep(10000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }finally {
            System.out.println("unlock");
            lock.unlock();
        }
    }
```
Everytime I **Sleep** in the middle of the **Lock**  And I got the error:
```
java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: ...
```





----
**And below the situation2:**
I write a **timmer** use **Aspect**
```
package com.tg.lottery.annotation;

import org.aspectj.lang.JoinPoint;
import org.aspectj.lang.annotation.After;
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Before;
import org.aspectj.lang.annotation.Pointcut;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 * timmer
 *
 */
@Aspect
@Component
public class UseTimeRecordAspect {
    
    private static final Logger logger = LoggerFactory.getLogger(UseTimeRecordAspect.class);
    ThreadLocal<Long> useTime = new ThreadLocal<>();
    
    @Pointcut("@annotation(useTimeRecord)")
    public void calTime(UseTimeRecord useTimeRecord) {
    }
    
    @Before("calTime(useTimeRecord)")
    public void before(JoinPoint joinPoint, UseTimeRecord useTimeRecord) {
        useTime.set(System.currentTimeMillis());
        logger.info(useTimeRecord.name() + " timmer start");
    }
    
    @After("calTime(useTimeRecord)")
    public void after(JoinPoint joinPoint, UseTimeRecord useTimeRecord) {
        float second = (System.currentTimeMillis() - useTime.get()) * 1.0F / 1000;
        logger.info(useTimeRecord.name() + "  all time " + second + " second");
    }
    
}

```

Below the lock process

```
public void processWithLock(Lottery lottery) throws LotteryException {
        RLock redissonLock = redisson.getLock(lottery.getId());
        redissonLock.lock(5, TimeUnit.SECONDS);
        try{
            dosomething();
        } finally {
            redissonLock.unlock();
        }
    }

@UseTimeRecord(name = "dosomethingTimmer")
public void dosomething(){
  .....
}
```
Everytime I **use the Aspect** in the middle of the **Lock**  And I got the error:
```
java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: ...
```

**Comment by chowtin** [comment]
@mrniko I changed *async* way to use redisson, also made `waitLockTime > lockLeaseTime`, this issue disappeared .
this change has been put into production for several weeks, so i believe my usage was error, I/O thread was blocked somewhere.
