### ISSUE TITLE
Invalidated session in one tomcat is still used in another tomcat instance when relogin

### ISSUE THREAD

**Issue by rlimarto** [redisson/redisson#1432]
Hello,

I am using redisson tomcat session manager in docker environment. I have 2 tomcat containers and want to share the sessions with redis. I can see the sessions information are stored and retrieved on redis.

However, I have an issue that an invalidated session is used because the invalidation is done in another tomcat. The steps that I've done is:
- Login request goes to tomcat1 and a session is created.
- Any request after login (e.g. query) goes to tomcat2. The same session is used, and it works fine.
- Logout request goes to tomcat1 and the session is invalidated.
- Try to re-login and the request goes to tomcat2 and it gets a session.
- The problem occurs here. When a request done after re-login, it goes to tomcat1, but the session is not there, and my application throws an error.

I have debugged through the code and I found that:
* When the first login request is done in tomcat1, the getSession method is called and findSession method will not find any sessions, therefore a new session is created in the memory of tomcat1 and stored to redis.
* When a request (e.g. query) goes to tomcat2, the findSession method will look into the tomcat2 memory first, and if it could not find it, it will find the session info in redis, and then create a new session object in the tomcat2 memory and put the session information from redis into it. (Correct me if I'm wrong)
* When logout, it goes to tomcat1, the session is invalidated, it is removed from the tomcat1 memory and also the session info is removed from the redis. This means the session in tomcat2 memory is never removed at this point. (Again, correct me if I'm wrong)
* Therefore when re-login request goes to tomcat2, because findSession method will get the session from the memory first, and the client still has the same session id, it will get the session from tomcat2 memory which has already been invalidated in tomcat1 and used it in the request without updating to redis.
* Finally after re-logged in, when trying to make a request and it goes to tomcat1, the session does not exist because the findSession could not find the session neither in tomcat1 memory nor the redis. Therefore the application will throw an error because it checks first if the session exists before making a query request.

My question is what behaviour do you expect in this case? Is the findSession method already working as expected?
Or do I miss something in my application? (e.g. do I have to always check the "session:isValid" should be true everytime I do login? (because it's not described in the documentation usage guide))

Thanks.

Regards,
Ricky.

**Comment by mrniko** [comment]
Your problem was fixed in https://github.com/redisson/redisson/issues/1414

**Comment by rlimarto** [comment]
@mrniko I thought that issue is about Vaadin and readMode=MEMORY.
I was using readMode=REDIS, and I tried with the newest release 3.7.0, and my issue still happens.
After that I tried to use the readMode=MEMORY, and the issue doesn't happen anymore. Thanks!

However, with your recent changes to readMode=MEMORY, now the attributes will always be somehow synchronized between tomcat instances, which this case somehow was the issue where you firstly introduced readMode property (issue #974 ).
Does this mean that readMode=REDIS is not used anymore?

**Comment by mrniko** [comment]
REDIS readMode could work slower for some cases, since Redisson read attribute not from session but Redis.

**Comment by rlimarto** [comment]
But basically, wasn't REDIS readMode introduced in the first place to share attributes between tomcat instances with non-sticky session? This is what I thought because the attributes will always be read from Redis. Therefore I was using REDIS readMode all the time.
But with your recent changes in 3.7.0, those sharing attributes in non-sticky session feature is somehow supported in MEMORY readMode too, and even better, because my issue was also solved.
This made me rethink of when exactly will I use the REDIS readMode?

**Comment by mrniko** [comment]
Use Redis readMode if session data requires strong consistency
