### ISSUE TITLE
Missing PubSub messages when using connection ping

### ISSUE THREAD

**Issue by mmatosevic** [redisson/redisson#1497]
﻿### Expected behavior
setPingConnectionInterval should send periodic ping messages and keep channels alive, but this must not affect any other type of messages on channels.

### Actual behavior
When using setPingConnectionInterval some messages will not be delivered to listeners after being published. I have a test code which can reliably reproduce this issue:
```
import org.redisson.Redisson;
import org.redisson.api.RTopic;
import org.redisson.api.RedissonClient;
import org.redisson.codec.SerializationCodec;
import org.redisson.config.Config;
import org.redisson.config.SubscriptionMode;

import java.util.UUID;
import java.util.concurrent.ConcurrentSkipListSet;

public class PlainPubSubTest {

    public static void main(String[] args) throws InterruptedException {
        ConcurrentSkipListSet<String> sentItems = new ConcurrentSkipListSet<>();
        ConcurrentSkipListSet<String> receivedItems = new ConcurrentSkipListSet<>();

        System.out.println("Staring test");

        RedissonClient redissonClient = redissonClient(configSentinel());

        RTopic<String> eventsTopic = redissonClient.getTopic("eventsTopic");
        eventsTopic.addListener((channel, msg) -> receivedItems.add(msg));

        System.out.println("Starting sending loop");
        for(int i = 0; i<1000; i++){
            final String message = UUID.randomUUID().toString();
            eventsTopic.publish(message);
            sentItems.add(message);
            Thread.sleep(10);
        }

        System.out.println("Sent: " + sentItems.size() + ", got: " + receivedItems.size());
        Thread.sleep(1000);
        System.out.println("Sent: " + sentItems.size() + ", got: " + receivedItems.size());
    }

    private static RedissonClient redissonClient(Config config){
        return Redisson.create(config);
    }

    private static Config configSentinel(){
        Config config = new Config();
        config.setCodec(new SerializationCodec());
        String password = "*****************";
        String masterName = "my-master-name";
        String[] sentinelAddresses = new String[]{"redis://localhost:26001", "redis://localhost:26002", "redis://localhost:26003"};
        Integer connectionTimeout = 10000;
        int pingTimeout = 5000;
        int reconnectionTimeout = 5000;
        int connectionPoolSize = 10;
        int connectionPoolMinSize = 10;
        int connectionPingInterval = 50; //Changing to 0 eliminates issue
        config.useSentinelServers()
                .setPassword(password)
                .setMasterName(masterName)
                .addSentinelAddress(sentinelAddresses)
                .setConnectTimeout(connectionTimeout)
                .setPingTimeout(pingTimeout)
                .setPingConnectionInterval(connectionPingInterval)
                .setSubscriptionMode(SubscriptionMode.MASTER)
                .setFailedSlaveReconnectionInterval(reconnectionTimeout)
                .setMasterConnectionMinimumIdleSize(connectionPoolMinSize)
                .setMasterConnectionPoolSize(connectionPoolSize);
        return config;
    }
}
```

Output of this code will produce varying results each time, but it will never get all sent messages, like this:
```
Staring test
Starting sending loop
Sent: 1000, got: 640
Sent: 1000, got: 640
```

However if connectionPingInterval is set to 0 (disabled) issue is completely eliminated, like this:
```
Staring test
Starting sending loop
Sent: 1000, got: 1000
Sent: 1000, got: 1000
```

### Redis version
```
redis_version:4.0.6
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:f1060815dd32471a
redis_mode:standalone
os:Linux 3.10.0-514.26.1.el7.x86_64 x86_64
```

### Redisson version
3.7.2

### Redisson configuration
Visible in test case

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by mmatosevic** [comment]
I've tried to test again with 3.7.3 version and unfortunately I still have the same issue like before (same test code), some messages are dropped although it's somehow better now. Before the fix almost half of messages dropped, and now ~10 per 1000 are dropped, actual results from my tests:

1.) Sent: 1000, got: 991
2.) Sent: 1000, got: 993
3.) Sent: 1000, got: 994

I know that you added my test case to your suite, does it pass every time or fails sometimes for you?
Maybe it's something specific to my configuration (3 sentinels + 1 master + 1 salve), but I doubt it.

Could you please check why the same code results in still similar issue.
Let me know if I can help you somehow to fix this issue.

Also, should I open new issue, or you can re-open this one?

Thank you!

**Comment by mrniko** [comment]
Let me check it

**Comment by mrniko** [comment]
This issue is reproducable in 2 of 5 test executions. I have fixed it.

**Comment by mmatosevic** [comment]
Thank you! I will wait for next release...

**Comment by mmatosevic** [comment]
Still no luck, now I have some new warning message in logs:
```
Jul 26, 2018 11:54:17 AM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: CommandPubSubDecoder.decode() must consume the inbound data or change its state if it did not decode anything.
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:379)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
Also not all messages are received:
```
Sent: 1000, got: 940
```
This is in version redisson 3.7.5 everything other is the same as before.
Could you please take a look?

Thank you!

**Comment by mrniko** [comment]
tested it with 3.8.1 - test passed

**Comment by valodzka** [comment]
Same issue as of 3.8.1:

    2018-09-18 15:29:47,741 	nio-redisson-1-3 	WARN 	io.netty.channel.DefaultChannelPipeline 		An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
    io.netty.handler.codec.DecoderException: CommandPubSubDecoder.decode() must consume the inbound data or change its state if it did not decode anything.
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:379)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:546)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by valodzka** [comment]
In case it's matter - I slightly changed @mmatosevic  reproducer:

    private static Config configSentinel(){
        Config config = new Config();
        config.setCodec(new SerializationCodec());
        int connectionPingInterval = 50; //Changing to 0 eliminates issue

        config.useSingleServer()
                .setAddress("redis://localhost:6379")
                .setConnectTimeout(20_000)
                .setTimeout(25_000)
                .setRetryInterval(750)
                .setPingConnectionInterval(connectionPingInterval)
                .setDnsMonitoringInterval(-1)
                .setClientName("test-name")
                .setConnectionMinimumIdleSize(4)
                .setConnectionPoolSize(16);

        return config;
    }

**Comment by mrniko** [comment]
Fixed

**Comment by valodzka** [comment]
Same issue as of redisson 3.9.0. Same reproducer. Works well with pingConnectionInterval(0), fails with pongConnectionInterval(50). A bit different exception:

    java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at org.redisson.client.handler.State.getLastLevel(State.java:56)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:359)
	at org.redisson.client.handler.CommandDecoder.decodeFromCheckpoint(CommandDecoder.java:199)
	at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:90)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:108)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)

**Comment by mrniko** [comment]
Fixed. Could you please recheck it against 3.0.0 branch?

**Comment by valodzka** [comment]
Same issue. 

> I'm unable to reproduce it with current test

Thats weird. I created special project https://github.com/valodzka/redisson-issue-1497.  Easily reproducible (like 80% times) for me at commit 7b20c0d9a55762ea86d1dd6505afbccd20d56079 with java 11 and java 8, redis 4 and redis 5 (mac os 10.13.6). Log example https://gist.github.com/valodzka/da427f73b2c6437460bc4be3b527ac45.

**Comment by valodzka** [comment]
Also tested on clean linux (debian 9, 4.9.0-8-amd64, openjdk 11, redis 4.0.11, redission 3.0.0 branch). Not at every run, but very often gives the same: https://gist.github.com/valodzka/da427f73b2c6437460bc4be3b527ac45/revisions

**Comment by mmatosevic** [comment]
I can also confirm that issue is still present in 3.9.0 version.
Exception:
```
Nov 05, 2018 4:36:05 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.redisson.client.handler.State.getLastLevel(State.java:56)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:359)
	at org.redisson.client.handler.CommandDecoder.decodeFromCheckpoint(CommandDecoder.java:199)
	at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:90)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:108)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	... 32 more

Sent: 1000, got: 970
Sent: 1000, got: 970
```

**Comment by mrniko** [comment]
Fixed

**Comment by valodzka** [comment]
I've tested 3.10.1 and can confirm that old reproducer works. But small modification breaks redission again. I've updated project with new version https://github.com/valodzka/redisson-issue-1497
Sleep in decoder emulates any heavy decoding work.

Without setPingConnectionInterval - ok, as expected:

    Sent: 10, got: 1
    Sent: 10, got: 10

With setPingConnectionInterval - messages lost:

    Sent: 10, got: 1 
    Sent: 10, got: 2

**Comment by mrniko** [comment]
@valodzka 

Thanks for your feedback! if you add log message to `PingConnectionHandler.sendPing` method you will see that subscribed channel closed before remaining messages were received and Redis doesn't resend them in this case. This issue happens due to long delay in decoding process so expected ping for 50 ms couldn't be get if you have delay in decoding process for 4000 ms.

**Comment by valodzka** [comment]
Could you explain which settings would be correct in such case? `setPingTimeout `is deprecated, `setTimeout `to big value changes nothing.

**Comment by mrniko** [comment]
@valodzka 

You need to increase `PingConnectionInterval` so all messages have time to arrive

**Comment by valodzka** [comment]
Okay, thank you, sorry for incorrect reporting
