### ISSUE TITLE
Regression: DNS resolver failing to find valid DNS record

### ISSUE THREAD

**Issue by johnjaylward** [redisson/redisson#1625]
### Expected behavior
The DNS resolver should find valid DNS records. The hostname I'm having trouble with worked in 3.5.0, it is failing in newer versions.

I opened a ticket with Netty first thinking it was a problem with the resolver itself, but after trying different Netty versions, it appears to be a configuration issue with how Reddison is calling the resolver.

See https://github.com/netty/netty/issues/8261

### Actual behavior
Exception thrown:
```
Caused by: io.netty.resolver.dns.DnsNameResolverContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'host.toplevel' failed to resolve 'host.toplevel.search.domain' after 7 queries 
	at io.netty.resolver.dns.DnsNameResolverContext.finishResolve(DnsNameResolverContext.java:721)
	at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:663)
	at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:306)
	at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:295)
	at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:636)
	at io.netty.resolver.dns.DnsNameResolverContext$3.operationComplete(DnsNameResolverContext.java:342)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.resolver.dns.DnsQueryContext.setSuccess(DnsQueryContext.java:197)
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:180)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:969)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1412)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:943)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
### Steps to reproduce

1. Configure a top level domain `someDomain` on a DNS server you own
1. Configure a host under the new top level domain `someHost.someDomain`
1. Configure multiple resolvers  on the DNS client machine that will run the Netty code. i.e. 8.8.8.8, 192.168.1.1, and 10.0.0.1 (I have 3 resolvers configured, each pointing to different DNS masters  - global DNS, local personal private network, company private network over a VPN)
1. Configure the search domain to not match the top level domain, i.e. `search.otherDomain` on the DNS client machine that will run the Netty code
1. Configure redisson to connect to `someHost.someDomain`
1. failure during configuration.

### Redisson version
Trying to migrate from 3.5.0 to the latest version

**Comment by mrniko** [comment]
Try to use Redisson 3.8.0 with netty 4.1.13.Final (version used by 3.5.0).

**Comment by johnjaylward** [comment]
I tried that. It still appeared to fail the lookup.

**Comment by mrniko** [comment]
It would help a lot if you try 3.6.0 and 3.7.0 just want to understand which version brings this issue

**Comment by mrniko** [comment]
It's very strange DnsNameResolverContext doesn't exist in netty anymore, at least at latest one 4.1.29 used by 3.8.0. Seems you have got different netty versions in classpath.

**Comment by mrniko** [comment]
Any update?

**Comment by johnjaylward** [comment]
### Redisson 3.5 config using netty-4.1.13
```json
{
	"singleServerConfig":{
		"address":"redis://someHost.someDomain:6379",
		"password":null,
		"subscriptionConnectionMinimumIdleSize":1,
		"subscriptionConnectionPoolSize":50,
		"connectionMinimumIdleSize":1,
		"connectionPoolSize":64,
		"dnsMonitoring":false,
		"dnsMonitoringInterval":5000,
		"idleConnectionTimeout":10000,
		"connectTimeout":10000,
		"timeout":3000,
		"retryInterval":1500,
		"reconnectionTimeout":3000,
		"failedAttempts":3,
		"database":0,
		"subscriptionsPerConnection":5,
		"clientName":"client"
	},
   "threads":0,
   "nettyThreads":0,
   "codec":null,
   "useLinuxNativeEpoll":false
}
```
Everything works fine, no issues using that.

###  Redisson 3.8 using netty 4.1.13
```json
{
   "singleServerConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":3000,
      "retryAttempts":3,
      "retryInterval":1500,
      "password":null,
      "subscriptionsPerConnection":5,
      "address": "redis://someHost.someDomain:6379",
      "subscriptionConnectionMinimumIdleSize":1,
      "subscriptionConnectionPoolSize":50,
      "connectionMinimumIdleSize":32,
      "connectionPoolSize":64,
      "database":0,
      "dnsMonitoringInterval":5000,
      "clientName":"client"
   },
   "threads":0,
   "nettyThreads":0,
   "codec":{
      "class":"org.redisson.codec.JsonJacksonCodec"
   },
   "transportMode":"NIO"
}
```

Stack trace:
```
Caused by: java.net.UnknownHostException: failed to resolve 'someHost.someDomain' after 7 queries 
	at io.netty.resolver.dns.DnsNameResolverContext.finishResolve(DnsNameResolverContext.java:700)
	at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:642)
	at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:290)
	at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:280)
	at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:619)
	at io.netty.resolver.dns.DnsNameResolverContext$3.operationComplete(DnsNameResolverContext.java:325)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.resolver.dns.DnsQueryContext.setSuccess(DnsQueryContext.java:197)
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:180)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:947)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

### Redisson 3.8 with default netty (4.1.29)
same config as above

Stack Trace:
```
Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'someHost.someDomain' failed to resolve 'someHost.someDomain.search.otherDomain' after 7 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:816)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:777)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:310)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:299)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:750)
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:62)
	at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:359)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
	at io.netty.resolver.dns.DnsQueryContext.setSuccess(DnsQueryContext.java:192)
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:184)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1067)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

As you can see, the trace messages are different, but the result is the same. Redisson 3.6.0+ can not find the host, while 3.5.0 can.

**Comment by mrniko** [comment]
I guess it's still could be considered as a netty bug since before `2.10.6 / 3.5.6` version Redisson didn't use netty based dns resolver. Have a look at this change https://github.com/redisson/redisson/commit/d3d6424983dee335df440a3b1bea4011c8b4c7fb

**Comment by mrniko** [comment]
Confirmed! Netty's bug https://github.com/netty/netty/issues/8261#issuecomment-427350547

**Comment by mrniko** [comment]
Done! Implemented workaround on Redisson side.

**Comment by randomSpirit** [comment]
similar issue happened  again
@mrniko 
> Redisson 3.9 with default netty (4.1.29.Final)

`2018-12-06 17:25:10.746 ERROR 1 --- [redisson-netty-4-1] org.redisson.connection.DNSMonitor       : Unable to resolve mb.y.redis.sohucs.com
io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'someHost.someDomain' failed to resolve 'someHost.someDomain.search.otherDomain' after 2 queries 
  at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:816) [netty-resolver-dns-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:777) [netty-resolver-dns-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:310) [netty-resolver-dns-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:299) [netty-resolver-dns-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.resolver.dns.DnsResolveContext.access$500(DnsResolveContext.java:62) [netty-resolver-dns-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:356) [netty-resolver-dns-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:216) [netty-resolver-dns-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:43) [netty-resolver-dns-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:166) [netty-resolver-dns-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446) [netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
  at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/172.16.40.1:53] query timed out after 5000 milliseconds (no stack trace available)`

**Comment by mrniko** [comment]
Fixed

**Comment by damoyang** [comment]
similar issue happens again in 3.11.2
Caused by: java.net.UnknownHostException: failed to resolve 'rm50473.eos.grid.sina.com.cn' after 2 queries 
	at shaded.io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:925)
	at shaded.io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:884)
	at shaded.io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:356)
	at shaded.io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:64)
	at shaded.io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:405)
	at shaded.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
	at shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493)
	at shaded.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472)
	at shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)
	at shaded.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)
	at shaded.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531)
	at shaded.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111)
	at shaded.io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:228)
	at shaded.io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:42)
	at shaded.io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:177)
	at shaded.io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at shaded.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: shaded.io.netty.resolver.dns.DnsNameResolverTimeoutException: [/192.168.0.1:53] query via UDP timed out after 5000 milliseconds (no stack trace available)

**Comment by pditommaso** [comment]
Still seeing this with redisson 3.11.5 and netty 4.1.42. Any suggestion?

**Comment by mrniko** [comment]
@damoyang

>  shaded.io.netty.resolver.dns.DnsNameResolverTimeoutException: [/192.168.0.1:53] query via UDP timed out after 5000 milliseconds

Please check your network

**Comment by pditommaso** [comment]
I'm trying the workaround described in [this comment](https://github.com/netty/netty/issues/8880#issuecomment-558411219), thanks.

**Comment by pditommaso** [comment]
Confirming that this still happens with redisson 3.11.5 and netty 4.1.42. Since my stack runs on Kubernetes I've tried to set `single-request-reopen` dnsConfig and use debian instead of alpine as suggested in the comment linked previously.

**Comment by mrniko** [comment]
@pditommaso 

Thanks for your feedback. Did you try this as well ? https://github.com/netty/netty/issues/8880#issuecomment-484512740

**Comment by pditommaso** [comment]
Disabling Ipv6? doing it right now, I'll keep this post updated. Thanks.

**Comment by pditommaso** [comment]
Setting `-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true` did not help. My solution was to use tcp mode for DNS request as reported [here](https://github.com/kubernetes/kubernetes/issues/56903#issuecomment-424498508).

**Comment by pditommaso** [comment]
Unfortunately still getting this and I've used all possible workarounds.

**Comment by pditommaso** [comment]
The DNS is deployed and managed by the K8s cluster. Frankly, I have no idea how to debug this issue. Any suggestion is welcome.

**Comment by mrniko** [comment]
did you try to sniff udp traffic?

**Comment by pditommaso** [comment]
Nope, but I've specified to use tcp instead of udp as suggested here   https://github.com/kubernetes/kubernetes/issues/56903#issuecomment-424498508

**Comment by steveyegge** [comment]
I'm experiencing the same issue with **Redisson 3.13.4** which brings in **Netty 4.1.51 Final**.  I'm not using Kubernetes.  I'm using docker-compose + docker on a Google Compute Engine VM.  It's failing to resolve an unqualified DNS name on my VPC which is resolved correctly by dig/nslookup/ping/etc.  

The container is built from jetty:9-jdk14-slim, which I think (?) means it's based on debian.

I'm using dirt-simple Redisson configuration:

`private val config = Config().apply { useSingleServer().address = "redis://my-host:6379" }`

My container's /etc/resolv.conf looks like this:

`search c.some-domain.internal. google.internal.

nameserver 127.0.0.11

options ndots:0
`

The host VM image is from Debian 10.  The host VM's /etc/resolv.conf looks like this:

`domain c.some-domain.internal

search c.some-domain.internal. google.internal.

nameserver 169.254.169.254`

I worked around it for now by passing a fully-qualified name for my-host.  Would love to know why it doesn't work though.

**Comment by ycstream** [comment]
Still seeing this with redisson 3.16.1 and netty 4.1.66. And,I have tried ping my redis domain name ,it is ok.
this is my configuration:
`Config config = new Config();
        config.setThreads(16)
                .setNettyThreads(32)
                .setTransportMode(TransportMode.NIO)
                .setAddressResolverGroupFactory(new DnsAddressResolverGroupFactory())
                .useSingleServer()
                .setAddress(String.format("redis://%s:%s",redisHost,redisPort))
                .setPassword(redisPassword)
                .setIdleConnectionTimeout(10000)
                .setTimeout(3000)
                .setConnectTimeout(10000)
                .setRetryAttempts(3)
                .setRetryInterval(1500)
                .setSubscriptionsPerConnection(5)
                .setSubscriptionConnectionMinimumIdleSize(1)
                .setSubscriptionConnectionPoolSize(50)
                .setConnectionMinimumIdleSize(24)
                .setConnectionPoolSize(64)
                .setDnsMonitoringInterval(5000)`

**Comment by ycstream** [comment]
> similar issue happened again @mrniko
> 
> > JDK 1.8
> > Redisson 3.9 with default netty (4.1.29.Final)
> 
> ```
> 2018-12-06 17:25:10.746 ERROR 1 --- [redisson-netty-4-1] org.redisson.connection.DNSMonitor       : Unable to resolve mb.y.redis.sohucs.com
> io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'someHost.someDomain' failed to resolve 'someHost.someDomain.search.otherDomain' after 2 queries 
>   at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:816) [netty-resolver-dns-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:777) [netty-resolver-dns-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:310) [netty-resolver-dns-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:299) [netty-resolver-dns-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.resolver.dns.DnsResolveContext.access$500(DnsResolveContext.java:62) [netty-resolver-dns-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:356) [netty-resolver-dns-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:216) [netty-resolver-dns-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:43) [netty-resolver-dns-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:166) [netty-resolver-dns-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446) [netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
>   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.29.Final.jar!/:4.1.29.Final]
>   at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
> Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/172.16.40.1:53] query timed out after 5000 milliseconds (no stack trace available)
> ```



Hi, did you finally solve this problem? I also had the same problem.

**Comment by mrniko** [comment]
Did you try specify fully-qualified name for host ?

**Comment by memorais** [comment]
Do you managed to solve that @ycstream ? Facing same issue Redisson 3.16.8...

**Comment by ycstream** [comment]
> Do you managed to solve that @ycstream ? Facing same issue Redisson 3.16.8...

no,it still exists

**Comment by ycstream** [comment]
> netty-all-4.1.66.Final.jar:4.1.66.Final


> Did you try specify fully-qualified name for host ?
> 
> Also please update netty to the latest version. A few bug fixes for dns resolver were fixed after that version.

Which version of netty is available? I am using 4.1.66.Final now

**Comment by mrniko** [comment]
@ycstream Latest is 4.1.76.Final

**Comment by mrniko** [comment]
Fixed by commit https://github.com/redisson/redisson/commit/2d83ebdf64bde8793b8c3b24be81ad23e72119d5

**Comment by alphaxo** [comment]
@mrniko We have recently experienced this problem, could you tell me what the reason cause the problem, and is there any way to reproduce it

**Comment by kannamr** [comment]
@mrniko when this will be part of the new release?

**Comment by murainwood** [comment]
> @mrniko when this will be part of the new release?

I got the same issue with 3.17.7. Seems would be fix in next release?

**Comment by mrniko** [comment]
This fixed in unreleased 3.17.8 version

**Comment by sean-scott-lr** [comment]
How are people working around this issue with ElastiCache-Redis in AWS?   Looks like the issue has been open for years so there has to be a workaround

**Comment by mrniko** [comment]
@sean-scott-lr 

You can look at commit https://github.com/redisson/redisson/commit/2d83ebdf64bde8793b8c3b24be81ad23e72119d5

**Comment by grantkl** [comment]
Is there a date on when 3.17.8 will be released with this fix?

**Comment by zhangyunbo1994** [comment]
This issue's fix seems already be included in the 3.18.0 release.

**Comment by mrniko** [comment]
@Gdk666 

This also can be a solution

**Comment by hjizettle** [comment]
We are seeing this intermittently without any other side effects on 3.19.1. The service continues to operate fine but this shows up in the logs.

**Comment by mrniko** [comment]
@hjizettle 

Try to define SequentialDnsAddressResolverFactory with concurrencyLevel = 2

**Comment by lievenvaneeckhaute** [comment]
> We are seeing this intermittently without any other side effects on 3.19.1. The service continues to operate fine but this shows up in the logs.

Same. Tried the SequentiqlDnsAddressResolver with concurrencyLevel 1 and 2. In both cases it still happens.

**Comment by ll09-leraner** [comment]
Netty:4.1.91
Redisson:3.18.0
it still seems to happen sometimes
`org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=rediss://xxxxxx:6380]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)`

**Comment by hellojukay** [comment]
alpine 3.18.3 , and redisson  3.24.0 ,  nettry  4.1.100.Final also can reproduce

**Comment by mrniko** [comment]
@ll09-leraner 

Try to upgrade to 3.24.1 version.

**Comment by zhumengzhu** [comment]
We have also encountered this problem, it seems to be related to this: [Racy conntrack and DNS lookup timeouts
](https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts)
We are currently attempting to upgrade Alpine to version 3.18.3 and are in the testing phase, not sure if it will work.

**Comment by hellojukay** [comment]
> We have also encountered this problem, it seems to be related to this: [Racy conntrack and DNS lookup timeouts ](https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts) We are currently attempting to upgrade Alpine to version 3.18.3 and are in the testing phase, not sure if it will work.

I have ready test on alpine , it can not fix the problem , because redisson dns not implement by musl , it depends on netty dns resovler.

**Comment by gkw666** [comment]
Still seeing this with redisson 3.18.0 and netty 4.1.79.Final Any suggestion?

**Comment by mrniko** [comment]
@gkw666 

Fixed in 3.26.1. Also make sure that Netty 4.1.105 or higher in classpath.
