### ISSUE TITLE
Redisson can't resolve short DNS name

### ISSUE THREAD

**Issue by yevgenb** [redisson/redisson#1693]
### Actual behavior

Since version 3.8.2 Redisson failed to resolve short DNS name.

### Steps to reproduce or test case

1) Configure redis full host name (in our case
 redis-test.domain.com)
2) Add search domain "domain.com" to  /etc/resolv.conf
3) Verify that short name can be resolved with nslookup:
nslookup redis-test
Server:		192.168.20.167
Address:	192.168.20.167#53

Non-authoritative answer:
Name:	redis-test.domain.com
Address: 135.17.72.111
3) Configure redisson client to connect to "redis-test"
4) Client can't connect to server:
{"time":"2018-10-24T10:36:45.969-07:00","@version":1,"msg":"failed to resolve 'redis-test' after 3 queries ","logger_name":"org.redisson.cluster.ClusterConnectionManager","thread_name":"main","level":"WARN","level_value":30000,"name":"gws-core-auth","pid":66459}

### Redisson version
3.8.2
### Redisson configuration
Default config used

**Comment by mrniko** [comment]
So you unable to reproduce this issue with 3.8.1?

**Comment by yevgenb** [comment]
Works fine with 3.8.1:
{"time":"2018-10-24T10:50:18.751-07:00","@version":1,"msg":"Redisson 3.8.1","logger_name":"org.redisson.Version","thread_name":"main","level":"INFO","level_value":20000,"name":"gws-core-auth","pid":67160}
{"time":"2018-10-24T10:50:19.788-07:00","@version":1,"msg":"Redis cluster nodes configuration got from redis-test/135.17.72.178:7000:\n8c4fbb12ca5805c34ec6a06d8f7ad032168e5c5c 127.0.0.1:7005 slave 30b5d840d46caed4c4bc749846bf842e07e68416 0 1540403430113 6 connected\n204c7186bc5dfb7bf0fbed9719230bab7e26ef5e 127.0.0.1:7001 master - 0 1540403429087 2 connected 5461-10922\nfaf63dfda8682b0ce6701e670bfdc3a4b4b2040c 127.0.0.1:7000 myself,master - 0 0 1 connected 0-5460\n9640eae4292a97d2761545c75bcf5b43f5ae6118 127.0.0.1:7004 slave 204c7186bc5dfb7bf0fbed9719230bab7e26ef5e 0 1540403428579 5 connected\n30b5d840d46caed4c4bc749846bf842e07e68416 127.0.0.1:7002 master - 0 1540403430113 3 connected 10923-16383\n7696040b2cadf1d7d279af5c67ca707e86747e1e 127.0.0.1:7003 slave faf63dfda8682b0ce6701e670bfdc3a4b4b2040c 0 1540403429087 4 connected\n","logger_name":"org.redisson.cluster.ClusterConnectionManager","thread_name":"main","level":"INFO","level_value":20000,"name":"gws-core-auth","pid":67160}

**Comment by mrniko** [comment]
Seems had been broken by fix of https://github.com/redisson/redisson/issues/1646 issue.

**Comment by yevgenb** [comment]
Thank you!

**Comment by mrniko** [comment]
Fixed

**Comment by arpit728** [comment]
@mrniko 
I am still facing this issue with 3.9.0, take a look at below stack trace.
```java
WARN  [2018-11-01 17:49:09,483] [main] ClusterConnectionManager: failed to resolve 'scheduler-redis' after 3 queries
Exception in thread "main" org.redisson.client.RedisConnectionException: Can't connect to servers!
	at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:159)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:198)
	at org.redisson.Redisson.<init>(Redisson.java:122)
	at org.redisson.Redisson.create(Redisson.java:161)
	at com.webengage.scheduler.SchedulerApplication.run(SchedulerApplication.java:83)
	at com.webengage.scheduler.SchedulerApplication.run(SchedulerApplication.java:31)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:40)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
	at io.dropwizard.cli.Cli.run(Cli.java:75)
	at io.dropwizard.Application.run(Application.java:79)
	at com.webengage.scheduler.SchedulerApplication.main(SchedulerApplication.java:36)
Caused by: java.net.UnknownHostException: failed to resolve 'scheduler-redis' after 3 queries
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:845)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:806)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:333)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:322)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:779)
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:62)
	at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:382)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
	at io.netty.resolver.dns.DnsQueryContext.setSuccess(DnsQueryContext.java:192)
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:184)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1127)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mrniko** [comment]
@arpit728 

Did you try to update netty to 4.1.31.final? According to this comment https://github.com/redisson/redisson/issues/1486#issuecomment-434693048 it solves the problem.

**Comment by arpit728** [comment]
@mrniko 
It didn't workout, still getting the same error.

**Comment by samiahmed1** [comment]
having the same issue as @arpit728, works on 3.8.1 but doesn't work on 3.8.2 or 3.9.0. Using the latest netty library didn't work for me either

**Comment by zpa3x60** [comment]
I also have this problem.

**Comment by mrniko** [comment]
Please update to 3.10.0 version and set `Config.addressResolverGroupFactory=DnsAddressResolverGroupFactory` if you encounter this issue

**Comment by samiahmed1** [comment]
That worked for me, thanks!

**Comment by mrniko** [comment]
Fixed with a new implementation

**Comment by safonovserg** [comment]
i still facing it in redisson 3.11.4 : io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'my-host' failed to resolve 'my-host.int' after 3 queries 
at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:877)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:838)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:333)
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:63)
	at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:382)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:220)
	at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:43)
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:170)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/1.1.1.1:53] query timed out after 5000 milliseconds (no stack trace available)

**Comment by mrniko** [comment]
@safonovserg 

Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/1.1.1.1:53] query timed out after 5000 milliseconds

**Comment by jerryhu1234** [comment]
io.netty.resolver.dns.SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'redis-redis.jpilot-uat' failed to resolve 'redis-redis.jpilot-uat.jpilot-uat.svc.cluster.local' after 2 queries 
    at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:925)
    at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:884)
    at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:356)
    at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:64)
    at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:405)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)
    at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)
    at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531)
    at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111)
    at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:228)
    at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:42)
    at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:177)
    at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:834)
