### ISSUE TITLE
Unable to decode data +PONG

### ISSUE THREAD

**Issue by zhou-hao** [redisson/redisson#1855]
### Steps to reproduce or test case
```text
2019-01-12 12:53:15.134 ERROR 1 --- [isson-netty-1-3] o.r.client.handler.CommandDecoder        : Unable to decode data. channel: [id: 0x51b60460, L:/10.42.1.145:35170 - R:10.42.3.8/10.42.3.8:6379] message: +PONG
java.util.concurrent.CancellationException: null
java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263) org.redisson.misc.RedissonPromise.cancel(RedissonPromise.java:239)
org.redisson.client.handler.PingConnectionHandler$1.run(PingConnectionHandler.java:59)
io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:670)
io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:745)
io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:473)
java.lang.Thread.run(Thread.java:745)
```
### Redis version
`4.0.11`
### Redisson version
`3.10.0`
### Redisson configuration
```java
                Config config = new Config();
                config.useSentinelServers()
                        .setScanInterval(1000)
                        .setPingConnectionInterval(1000)
                        .setFailedSlaveCheckInterval(5000)
                        .setFailedSlaveReconnectionInterval(3000)
                        .setKeepAlive(true)
                        .addSentinelAddress(address)
                        .setMasterConnectionPoolSize(128)
                        .setSlaveConnectionPoolSize(128)
                        .setConnectTimeout(10000)
                        .setTimeout(10000)
                        .setMasterName("redis-master")
                        .setPassword("password")
                        .setDatabase(0);
```

**Comment by aawu** [comment]
i have the same problem and it will occur after long idle time,just like this:
RBlockingQueue<Object> list = redissonService.getPriorityBlockingQueue("test");
while (true) {
                Object o = list.take();
}

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by LeonardoEzio** [comment]
How to fixed it ? I used 3.13.3 but  the problem still exist

**Comment by mrniko** [comment]
Can you give sample code to reproduce it and stacktrace?

**Comment by LeonardoEzio** [comment]
>

**Comment by LeonardoEzio** [comment]
In which version I can find this Fixed : Fixed - don't send PING command for blocking queues. #1855

**Comment by LeonardoEzio** [comment]
I just seting  PingConnectionInterval and PingTime out in version 3.13.3 , then when i start up my application , It throws  Unable to decode data. channel: [id: 0x51b60460, L:/10.42.1.145:35170 - R:10.42.3.8/10.42.3.8:6379] message: +PONG

**Comment by mrniko** [comment]
any code sample?

**Comment by LeonardoEzio** [comment]
![kk_image](https://user-images.githubusercontent.com/33782470/93759320-8fdbb780-fc3c-11ea-9cd7-415f7764532e.png)

**Comment by LeonardoEzio** [comment]
When I change the version to 3.11.1 the problem has been solved . could u tell me the reason?
