### ISSUE TITLE
Spring session renaime failed when session ID changed on Redis cluster

### ISSUE THREAD

**Issue by yevgenb** [redisson/redisson#1897]
### Actual behavior
Redisson Session exception:

{"time":"2019-01-31T20:49:46.279+00:00","level":"ERROR","msg":"Runtime error: [[org.redisson.client.RedisException: CROSSSLOT Keys in request don't hash to the same slot. channel: [id: 0x1bc3eb9e, L:/172.18.0.6:51190 - R:172.18.0.3/172.18.0.3:7002] command: (RENAME), params: [spring:session:afe9d89c-35fe-4cd5-949f-b6fc07426bbe, spring:session:b93a060f-331a-4bcb-839f-8f2d764941ff]]]","requestId":"98778a17-677b-453b-91a7-b520b1596458","X-B3-TraceId":"2cc7f5f9cc324dcf","requestURI":"/auth/v3/oauth/token","stackTrace":"org.redisson.client.RedisException: CROSSSLOT Keys in request don't hash to the same slot. channel: [id: 0x1bc3eb9e, L:/172.18.0.6:51190 - R:172.18.0.3/172.18.0.3:7002] command: (RENAME), params: [spring:session:afe9d89c-35fe-4cd5-949f-b6fc07426bbe, spring:session:b93a060f-331a-4bcb-839f-8f2d764941ff]\n\tat org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:314)\n\tat org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:130)\n\tat org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:110)\n\tat io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)\n\tat io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)\n\tat io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)\n\tat io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)\n\tat io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.lang.Thread.run(Thread.java:748)\n"

### Redis version
Redis Cluster 3.2.7

### Redisson version 
3.10.1

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by yevgenb** [comment]
Thank you!

**Comment by wangtora** [comment]
It is still happening when I do not use [RedissonSessionRepository](/redisson/redisson/tree/master/redisson/src/main/java/org/redisson/spring/session/RedissonSessionRepository.java) but only use [RedissonConnectionFactory](redisson/redisson/blob/master/redisson-spring-data/redisson-spring-data-21/src/main/java/org/redisson/spring/data/connection/RedissonConnectionFactory.java) with Spring Session's RedisOperationsSessionRepository by the following code:
```java
@EnableSpringHttpSession
public class SessionConfig {
    @Bean
    public static ConfigureRedisAction configureRedisAction() {
        return ConfigureRedisAction.NO_OP;
    }
}
```

**Comment by mrniko** [comment]
@wangtora 

in cluster mode new name used with rename command should be match with slot number used by current name.

**Comment by wangtora** [comment]
@mrniko
> 
> in cluster mode new name used with rename command should be match with slot number used by current name.

Of course I am aware of that, but it is out of my control. Look at my stack trace, the rename command is called from Spring Session's RedisOperationsSessionRepository. Is it possible to let the RedissonConnection.rename() to handle the cluster case, just as it is handled in RedissonSessionRepository.changeSessionId()?
