### ISSUE TITLE
redisson.cache.ReferenceCacheMap causes OOM..

### ISSUE THREAD

**Issue by sanjikk** [redisson/redisson#2574]
Recently I used redisson 3.11.6 to r/w online redis on our server serivce, however, after it runs few days correctly something bad happens. Yep, it is awful OOM. I dumped server memory file and found that the biggest object is ReferenceCacheMap from redission (see on the pic of jprofiler).. I am really confused about why this object increased all the time and can't be released by GC, I will post some pics, hope anyone can help me to fix this. Thanks a lot.
![image](https://user-images.githubusercontent.com/7340650/73902972-84689580-48d2-11ea-8d35-aae58faec6cb.png)
![image](https://user-images.githubusercontent.com/7340650/73903964-7b2cf800-48d5-11ea-8594-a7665be868f6.png)

My config file like this:

{
  "masterSlaveServersConfig":{
    "idleConnectionTimeout":10000,
    "pingTimeout":1000,
    "connectTimeout":10000,
    "timeout":3000,
    "retryAttempts":3,
    "retryInterval":1500,
    "reconnectionTimeout":3000,
    "failedAttempts":3,
    "password":"xxxxxxxxxxx",
    "subscriptionsPerConnection":5,
    "clientName":null,
    "loadBalancer":{
      "class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"
    },
    "slaveSubscriptionConnectionMinimumIdleSize":1,
    "slaveSubscriptionConnectionPoolSize":50,
    "slaveConnectionMinimumIdleSize":100,
    "slaveConnectionPoolSize":200,
    "masterConnectionMinimumIdleSize":32,
    "masterConnectionPoolSize":64,
    "readMode":"SLAVE",
    "slaveAddresses":[
      "redis://xxxxxxxxxx"
    ],
    "masterAddress": "redis://xxxxxxx",
    "database":0
  },
  "threads":0,
  "nettyThreads":0,
  "codec":{
    "class":"org.redisson.codec.JsonJacksonCodec"
  },
  "transportMode":"NIO"
}

**Comment by mrniko** [comment]
Thanks for report! I set maxIdleTimeout in 1h this should resolve the issue.

**Comment by mrniko** [comment]
ReferenceCacheMap replaced with LRUCacheMap

**Comment by lp2jx0309** [comment]
hi, mrniko, 
I think the bug still exist.
The root cause of this bug is that the cached value is a Map<Codec, Codec>（private static final Map<ClassLoader, Map<Codec, Codec>> CODECS = ReferenceCacheMap.soft(0, 0)，in fact,  ClassLoader is  limited）, and the map never expire ( maxIdleTime == 0 && ttl == 0, StdCachedValue.isExpired()). 

When there are hundrands of threads continuously accesss the server at the approximately same time with the code  "RedissonClient.getBucket("hello", new JsonJacksonCodec()).get()",  the reference of the map exists in all threads and JsonJacksonCodec instance is put into the map one by one. Even if the memory is exhausted, GC cannot collect the map , which eventually leads to memory overflow,
so, i suggest that the value of CacheMap not use MAP, or maxIdleTime and ttl not all set to zero.

**Comment by mrniko** [comment]
Hi,

Codecs map is now based on LRUMap

https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/command/RedisExecutor.java#L650

**Comment by lp2jx0309** [comment]
thanks, i read  the code again.
the size of CODECS and Map<Codec,Codec> are all restricted. so oom should not happen.
------------------------------------------------------
    private static final Map<ClassLoader, Map<Codec, Codec>> CODECS = new LRUCacheMap<>(25, 0, 0);
-----------------------------------------------------
               System.out.println("map is null");
                synchronized (CODECS) {
                    map = CODECS.get(threadClassLoader);
                    if (map == null) {
                        map = new LRUCacheMap<>(200, 0, 0);
