### ISSUE TITLE
Redisson considers XREADGROUP and XCLAIM commands as read only but redis considers them read-write commands not allowing these commands to be executed on read-only replica

### ISSUE THREAD

**Issue by AayushyaVajpayee** [redisson/redisson#2663]
**Expected behavior**
 In a sentinel environment with 1 master(write only), 2 slaves (Read only), Redisson Stream's readGroup and Claim method should execute commands on redis master node.
**Actual behavior**
The XREADGROUP and XCLAIM redis commands are actually write commands in redis but Redisson consider these as read only commands and executes on slave nodes resulting in the following error 
from redis:
`org.redisson.client.RedisException: READONLY You can't write against a read only replica.. channel: [id: 0x6de344ad, L:/10.1.60.141:59425 - R:10.1.60.147/10.1.60.147:8223] command: (XREADGROUP), params: [GROUP, TASK_CONSUMER_GROUP, lms_node, COUNT, 10, BLOCK, 15000, STREAMS, TASK_STORE_STREAM, >]`
**Steps to reproduce or test case**
 Use readGroups and claim  method in a  master-slave redis environment with master being write only and slaves being read only
**Redis version**
5.0.5
 *Redisson version**
3.11.5
**Redisson configuration**

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by AayushyaVajpayee** [comment]
Hi @mrniko 
In RedissonStream class `RedisCommands.XREADGROUP_BLOCKING_SINGLE` and `RedisCommands.XREADGROUP_SINGLE` also need to be updated to write commands. I think you missed them in your commit

**Comment by mrniko** [comment]
Hi @AayushyaVajpayee 

Thanks for pointing out! Fixed either.
