### ISSUE TITLE
RedissonReactiveSubscription is not initialized properly and as a result - no messages are handled

### ISSUE THREAD

**Issue by ddekaliuk** [redisson/redisson#2686]
**Expected behavior**
In case of using through org.springframework.data.redis.core.ReactiveStringRedisTemplate, I expect to handle messages from the channel I subscribed to via `reactiveRedisTemplate.listenTo(channel)`

**Actual behavior**
The subscription via `reactiveRedisTemplate.listenTo(channel)` is happening and `redis-cli PUBLISH channel hello` returns `(integer) 1`, but NO messages are handled.

Spent some time debugging, I noticed that anonymous subclass of `BaseRedisPubSubListener`  is created in `RedissonReactiveSubscription.receive()` with overridden `onMessage(CharSequence channel, Object msg)` method which as I understand should handle all the messages from redis channel (by the way, perhaps you could explain why `BaseRedisPubSubListener` overrides `onMessage` with empty implementation? ).

In fact the listener handles all messages and swallows it somewhere, debugging the message hits `onMessage` breakpoint, but nothing happened then.
By the way, in some unexplainable cases (I really don't know how to explain it) somewhere in the code the `SubscribeListener` is initialized and message that is handled by that listener is handled downstream (happens only in debug mode with some combination of breakpoints placed:)).
But event in that base, a single message first handled by `BaseRedisPubSubListener` empty implementation of `onMessage` and only then by `SubscribeListener` which translates the message downstream.
 I tried a lot of times but didn't understand what is really needed to achieve this. 
 
**Steps to reproduce or test case**
1. Initialize ReactiveStringRedisTemplate with regular spring config (example attached).
2. Call `reactiveRedisTemplate.listenTo(channel)` and subscribe to it. 

**Redis version**
5.0.5

**Redisson version**
org.redisson:redisson-spring-data-22:3.12.4

**Redisson configuration**
```
@Bean(destroyMethod = "shutdown")
    public RedissonClient redissonClient() {
        Config config = new Config();
        config.useSingleServer()
                .setDnsMonitoringInterval(-1)
                .setTimeout(commandTimeoutMillis)
                .setAddress("redis://" + host + ":" + port);
        return Redisson.create(config);
    }
@Bean
public ReactiveRedisConnectionFactory redisConnectionFactory(RedissonClient redissonClient) {
    return new RedissonConnectionFactory(redissonClient);
}
 @Bean
ReactiveStringRedisTemplate reactiveRedisTemplate(ReactiveRedisConnectionFactory redisConnectionFactory) {
    return new ReactiveStringRedisTemplate(redisConnectionFactory);
}
```

**Comment by mrniko** [comment]
Unable to reproduce it. Here it the code:

```
        RedissonConnectionFactory factory = new RedissonConnectionFactory(redisson);
        AtomicReference<byte[]> msg = new AtomicReference<byte[]>();

        ReactiveStringRedisTemplate template = new ReactiveStringRedisTemplate(factory);
        template.listenTo(ChannelTopic.of("test")).doOnEach(s -> {
            msg.set(s.get().getMessage().getBytes());
        }).subscribe();

        ReactiveRedisConnection connection = factory.getReactiveConnection();
        connection.pubSubCommands().publish(ByteBuffer.wrap("test".getBytes()), ByteBuffer.wrap("msg".getBytes())).block();

        Awaitility.await().atMost(Duration.ONE_SECOND)
                    .until(() -> Arrays.equals("msg".getBytes(), msg.get()));
```

**Comment by ddekaliuk** [comment]
Yes, I saw it is overridden, but it doesn't reach the overridden `onMessage`.
I tried few more times and found out that line https://github.com/redisson/redisson/blob/88172a2a24fa0b5e52c4a0721290cf5b10517b0c/redisson-spring-data/redisson-spring-data-22/src/main/java/org/redisson/spring/data/connection/RedissonReactiveSubscription.java#L65
is executed only when I put a breakpoint on it in debug mode and call it in "evaluate expression" menu.
and as a result of not executing the above line, the following listener addition https://github.com/redisson/redisson/blob/88172a2a24fa0b5e52c4a0721290cf5b10517b0c/redisson-spring-data/redisson-spring-data-22/src/main/java/org/redisson/spring/data/connection/RedissonReactiveSubscription.java#L174
is not performed.

Here is how I an subscribing to it completely: 
```
@Autowired
    private ReactiveStringRedisTemplate reactiveRedisTemplate;

    @EventListener(ApplicationReadyEvent.class)
    public void subscribe() {

            return reactiveRedisTemplate.listenTo(ChannelTopic.of("topic"))
                    .flatMap(message -> {
                        log.info("evicting redis cache: " + message.getMessage());
                        return reactiveRedisTemplate.delete(reactiveRedisTemplate.scan(ScanOptions.scanOptions()
                                .match("*" + message.getMessage() + "*").build()));
                    });
    }
```

And it successfully works with Letuce, just replacing the dependency without changing anything in the code

**Comment by mrniko** [comment]
I updated test code. Still executes successfully:

```java
        RedissonConnectionFactory factory = new RedissonConnectionFactory(redisson);
        AtomicReference<byte[]> msg = new AtomicReference<byte[]>();

        ReactiveStringRedisTemplate template = new ReactiveStringRedisTemplate(factory);
        template.listenTo(ChannelTopic.of("test")).flatMap(message -> {
            msg.set(message.getMessage().getBytes());
            return template.delete("myobj");
        }).subscribe();

        ReactiveRedisConnection connection = factory.getReactiveConnection();
        connection.pubSubCommands().publish(ByteBuffer.wrap("test".getBytes()), ByteBuffer.wrap("msg".getBytes())).block();

        Awaitility.await().atMost(Duration.ONE_SECOND)
                    .until(() -> Arrays.equals("msg".getBytes(), msg.get()));
```

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/blob/88172a2a24fa0b5e52c4a0721290cf5b10517b0c/redisson-spring-data/redisson-spring-data-22/src/main/java/org/redisson/spring/data/connection/RedissonReactiveSubscription.java#L65

executes once subscibe process has completed

**Comment by mrniko** [comment]
Could you try my code example?

**Comment by mrniko** [comment]
I found the bug subscribe and receive methods should be synchronized.

**Comment by ddekaliuk** [comment]
> https://github.com/redisson/redisson/blob/88172a2a24fa0b5e52c4a0721290cf5b10517b0c/redisson-spring-data/redisson-spring-data-22/src/main/java/org/redisson/spring/data/connection/RedissonReactiveSubscription.java#L65
> 
> executes once subscibe process has completed

I completely understand that, but as I see, It is not executed at least at the time when https://github.com/redisson/redisson/blob/88172a2a24fa0b5e52c4a0721290cf5b10517b0c/redisson-spring-data/redisson-spring-data-22/src/main/java/org/redisson/spring/data/connection/RedissonReactiveSubscription.java#L175
should add the channels to collection

**Comment by mrniko** [comment]
Fixed! Could you try it with attached version?

[redisson-spring-data-22-3.12.5-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4469203/redisson-spring-data-22-3.12.5-SNAPSHOT.jar.zip)

**Comment by ddekaliuk** [comment]
Thanks. Will let you know once I try.

**Comment by ddekaliuk** [comment]
It introduced a new issue)
Now the method `onMessage` is triggered for all listeners despite the channel they are listening to.
What I mean: 
`reactiveRedisTemplate.listenTo(ChannelTopic.of("channelA"))
.doOnNext(message -> log.info("evicting cache: for channelA")`
`reactiveRedisTemplate.listenTo(ChannelTopic.of("channelB"))
.doOnNext(message -> log.info("evicting cache: for channelB")`
-> 
`redis-cli PUBLISH channelA hello` returns `(integer) 1`
-> 
Sometimes the message is handled by wrong listener ("evicting cache: for channelB" is logged) but only in debug mode.
In regular mode -> no messages are handled.

**Comment by ddekaliuk** [comment]
Just wondering. Is there any reason to deny creating of appropriate listener right in the https://github.com/redisson/redisson/blob/88172a2a24fa0b5e52c4a0721290cf5b10517b0c/redisson-spring-data/redisson-spring-data-22/src/main/java/org/redisson/spring/data/connection/RedissonReactiveSubscription.java#L60 ?

**Comment by mrniko** [comment]
> Just wondering. Is there any reason to deny creating appropriate listener right in the

Because `receive()` method hasn't been invoked.

**Comment by mrniko** [comment]
Here is updated version:

[redisson-spring-data-22-3.12.5-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4469556/redisson-spring-data-22-3.12.5-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
Fixed

**Comment by ddekaliuk** [comment]
Actually it was not)
Sorry, didn't have a time to check earlier but it still does not work.
Once I have more time, I will debug and find the actual line that does not work.
Please reopen

**Comment by mrniko** [comment]
Could you provide test case ?

**Comment by ddekaliuk** [comment]
Just performed the same actions.
Just config I provided already.
Just started the app.
Just sent PUBLISH command to the channel and got '1' in response back but no messages are handled.

**Comment by mrniko** [comment]
Did you use the latest version I attached?

Unable to reproduce it using follow test:
```java
RedissonConnectionFactory factory = new RedissonConnectionFactory(redisson);
AtomicLong counter = new AtomicLong();

ReactiveStringRedisTemplate template = new ReactiveStringRedisTemplate(factory);
template.listenTo(ChannelTopic.of("test")).flatMap(message -> {
     counter.incrementAndGet();
     return Mono.empty();
}).subscribe();

template.listenTo(ChannelTopic.of("test2")).flatMap(message -> {
     counter.incrementAndGet();
     return Mono.empty();
}).subscribe();

ReactiveRedisConnection connection = factory.getReactiveConnection();
connection.pubSubCommands().publish(ByteBuffer.wrap("test".getBytes()), ByteBuffer.wrap("msg".getBytes())).block();

Awaitility.await().atMost(Duration.ONE_SECOND)
                    .until(() -> counter.get() == 1);
```

**Comment by ddekaliuk** [comment]
It just does not work.

Tested a lot of times of course with the version you attached.
The following test fails at the last line, so no messages are handled:

`  
    @Test
    void testSubscribe() throws InterruptedException {
        Config config = new Config();
        config.useSingleServer()
                .setDnsMonitoringInterval(-1)
                .setAddress("redis://localhost:6379");

        RedissonClient redissonClient = Redisson.create(config);
        RedissonConnectionFactory redissonConnectionFactory = new RedissonConnectionFactory(redissonClient);
        ReactiveStringRedisTemplate reactiveStringRedisTemplate = new ReactiveStringRedisTemplate(redissonConnectionFactory);

        AtomicLong counter = new AtomicLong();
        reactiveStringRedisTemplate.listenTo(ChannelTopic.of("test")).flatMap(message -> {
            counter.incrementAndGet();
            return Mono.empty();
        }).subscribe();

        reactiveStringRedisTemplate.listenTo(ChannelTopic.of("test2")).flatMap(message -> {
            counter.incrementAndGet();
            return Mono.empty();
        }).subscribe();

        Long received = reactiveStringRedisTemplate.convertAndSend("test", "msg").block();
        assertThat(received).isEqualTo(1);

        Thread.sleep(2000);
        assertThat(counter.get()).isEqualTo(1);
    }`

Just a reminder - subscription just works with Lettuce.

**Comment by mrniko** [comment]
It works fine for me. Even if sleep is just 100ms

**Comment by ddekaliuk** [comment]
Perhaps Spring version does some impact something.
I am on org.springframework.boot:spring-boot-starter-webflux:2.2.6.RELEASE

**Comment by mrniko** [comment]
set logging level `TRACE` for `org.redisson` to see Redis commands processed by Redisson

**Comment by mrniko** [comment]
> Perhaps Spring version does any impact something.
I am on org.springframework.boot:spring-boot-starter-webflux:2.2.6.RELEASE

It works well either.

**Comment by ddekaliuk** [comment]
I will try with more detailed log level today.

**Comment by ddekaliuk** [comment]
**Listener initialization: **
`@Slf4j
@Component
public class OnStartSubscriber {

    private ReactiveStringRedisTemplate reactiveRedisTemplate;

    @EventListener(ApplicationReadyEvent.class)
    public void subscribe() {
        reactiveRedisTemplate.listenTo(ChannelTopic.of("test"))
                .doOnNext(message -> log.info("got the message - " + message.getMessage()))
                .blockLast();
    }

    @Autowired
    public void setReactiveRedisTemplate(ReactiveStringRedisTemplate reactiveRedisTemplate) {
        this.reactiveRedisTemplate = reactiveRedisTemplate;
    }
}`

**gradle dependencies part: ** 
`    implementation "org.redisson:redisson-spring-data-22:3.12.4"

    repositories {
        flatDir {
            dirs 'local-libs'
        }
    }
    implementation name: "redisson-spring-data-22-3.12.5-SNAPSHOT"`

**After application start, 2 such commands were sent: **
`redis-cli PUBLISH test test-message`

**Full output in console:**
`2020-04-22 13:17:54.943  INFO 1941 --- [  restartedMain] CacheApplication             : Started CacheApplication in 8.327 seconds (JVM running for 8.823)
2020-04-22 13:17:55.008 TRACE 1941 --- [sson-netty-2-27] o.r.client.handler.CommandEncoder        : channel: [id: 0x94dead08, L:/127.0.0.1:49848 - R:localhost/127.0.0.1:6379] message: *2
$9
SUBSCRIBE
$4
test

2020-04-22 13:17:55.019 TRACE 1941 --- [sson-netty-2-27] o.r.client.handler.CommandPubSubDecoder  : reply: *3
$9
subscribe
$4
test
:1
, channel: [id: 0x94dead08, L:/127.0.0.1:49848 - R:localhost/127.0.0.1:6379], command: null
2020-04-22 13:18:13.133 TRACE 1941 --- [sson-netty-2-27] o.r.client.handler.CommandPubSubDecoder  : reply: *3
$7
message
$4
test
$12
test-message
, channel: [id: 0x94dead08, L:/127.0.0.1:49848 - R:localhost/127.0.0.1:6379], command: null
2020-04-22 13:18:39.369 TRACE 1941 --- [sson-netty-2-27] o.r.client.handler.CommandPubSubDecoder  : reply: *3
$7
message
$4
test
$12
test-message
, channel: [id: 0x94dead08, L:/127.0.0.1:49848 - R:localhost/127.0.0.1:6379], command: null
`

**Comment by mrniko** [comment]
If you send message from redis-cli then you need to use StringCodec on Redisson side

**Comment by ddekaliuk** [comment]
So how to use it?
What else needs to be added to the configuration?

**Comment by mrniko** [comment]
use `Config.setCodec` method

**Comment by ddekaliuk** [comment]
No, it does not work even with `config.setCodec(new StringCodec());`

**Comment by mrniko** [comment]
Unable to reproduce.
