### ISSUE TITLE
Connections are not dropped even idle time is larger than idleConnectionTimeout

### ISSUE THREAD

**Issue by stevenli1217** [redisson/redisson#2744]
connections for Redis cluster
```
7000: 17
7001: 17
7002: 67
7003: 67
7004: 17
7005: 19
```
```
d059d4385143f50065d8af39b5d1802eee23995c 127.0.0.1:7005@17005 myself,master - 0 1588375071000 14 connected 0-5460
f45784901ae916629008f28045d3f6c4c229d7b5 127.0.0.1:7002@17002 master - 0 1588375071000 16 connected 10923-16383
5bffb4061e8258210d5dab911af5028e5e9faa65 127.0.0.1:7001@17001 slave 0db7080759d155fa098516c04e442d40ec348234 0 1588375072926 15 connected
0db7080759d155fa098516c04e442d40ec348234 127.0.0.1:7003@17003 master - 0 1588375071513 15 connected 5461-10922
beebdb6edb0fcff2afbff6b9cb0e354dc489bb93 127.0.0.1:7000@17000 slave d059d4385143f50065d8af39b5d1802eee23995c 0 1588375071000 14 connected
c043ee0879b79ee4ca357237433c24897dc25ce8 127.0.0.1:7004@17004 slave f45784901ae916629008f28045d3f6c4c229d7b5 0 1588375071918 16 connected
```

For those connections to 7002/7003, I found that all of their idle time is larger than idleConnectionTimeout.   Could you please help to clarify why Redisson doesn't kill those connections?

```
$redis-cli -c -p 7002 client list | grep MyService 
id=171 addr=172.18.0.1:50020 fd=50 name=MyService age=6264 idle=6264 flags=r db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=readonly
id=172 addr=172.18.0.1:50022 fd=51 name=MyService age=6264 idle=6264 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=173 addr=172.18.0.1:50024 fd=52 name=MyService age=6264 idle=6264 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=cluster
id=174 addr=172.18.0.1:50026 fd=53 name=MyService age=6264 idle=6264 flags=r db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=readonly
id=175 addr=172.18.0.1:50028 fd=54 name=MyService age=6264 idle=6264 flags=r db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=readonly
id=176 addr=172.18.0.1:50034 fd=10 name=MyService age=6264 idle=6264 flags=r db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=readonly
```

My setting is as following:
```
clusterServersConfig:
  idleConnectionTimeout: 30000
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 10
  slaveConnectionMinimumIdleSize: 16
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 16
  masterConnectionPoolSize: 64

```

**Comment by mrniko** [comment]
How many connections are not killed less than 16 per slave and master?

**Comment by stevenli1217** [comment]
Per my description, 7002 and 7004 has 67 connections and those connections' idle time is larger than 6264 sec.

But my idleConnectionTimeout in my configuration is  30000 Millisecond

I suppose around 50 connections should be killed.

**Comment by mrniko** [comment]
Unable to reproduce. 
Started Redisson with provided config.
All masters have 16 + 1 service connection and 3 Redis cluster service connections.

**Comment by stevenli1217** [comment]
Reproduce steps:
1. On app startup, everything looks good. 
2. Kill SIGSTOP to 1-2 master node and let their slave nodes become the master nodes. 
3. Then kill SIGCONT to those failed master node and let them become salve nodes. 
4. Check the connections again. 

I can easily reproduce the issue on my laptop.  Maybe I can record a video for you later.

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/issues/2672#issuecomment-613265662

**Comment by mrniko** [comment]
which value did you set for readMode setting?

**Comment by mrniko** [comment]
You should see "master /127.0.0.1:6900 used as slave" in logs. It means that same amount of slave connections established to master

**Comment by stevenli1217** [comment]
Per my configuration, the connections will be doubled. 
When will those old master connections be killed?

**Comment by mrniko** [comment]
Could you try it with version attached?

[redisson-3.12.6-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4579972/redisson-3.12.6-SNAPSHOT.jar.zip)

**Comment by stevenli1217** [comment]
Issue remains.

Desc: 
```
  idleConnectionTimeout: 30000
  slaveConnectionMinimumIdleSize: 16
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 16
  masterConnectionPoolSize: 64
```
I use the above configuration which is easy to do count.

My test steps:
1. Start my app, all the redis connections are setup. No write/read
2. Master node 7000 has 2 connections. [ Works as designed ]
3. Restart Redis cluster.
4. After redis cluster is up again, master node 7000 has 4 connections 
    [Q1: where do these 2 connections come from?]
    But no connection will be killed when connection idle time is larger than idleConnectionTimeout
    [Q2: it seems that they're never killed. Not sure if this works as designed.]
5. Kill SIGSTOP to node 7000 and its slave node 7005 becomes the master. Kill SIGCONT to 7000 and it becomes a slave of 7005
6. Now node 7000 has 6 connections.  
    [Q3: I didn't see "master /127.0.0.1:xxx used as slave" in logs. But it seems that same amount of slave connections established to master]
    [Q4. node 7000 has 6 connections and are never killed. Is this bug for connection leak]

6 connections for node 7000
```
id=25 addr=172.18.0.1:40350 fd=12 name=MerchantDataService age=716 idle=716 flags=r db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=readonly
id=26 addr=172.18.0.1:40352 fd=13 name=MerchantDataService age=716 idle=716 flags=r db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=readonly
id=3 addr=172.18.0.1:38402 fd=10 name=MerchantDataService age=1020 idle=1017 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=cluster
id=6 addr=172.18.0.1:38446 fd=22 name=MerchantDataService age=1017 idle=1017 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=7 addr=172.18.0.1:38448 fd=23 name=MerchantDataService age=1017 idle=1017 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=8 addr=172.18.0.1:38452 fd=24 name=MerchantDataService age=1017 idle=1017 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
```

TCP connection status looks good
```
$netstat -an | grep 7000
tcp4       0      0  127.0.0.1.7000         127.0.0.1.61725        ESTABLISHED
tcp4       0      0  127.0.0.1.7000         127.0.0.1.61724        ESTABLISHED
tcp4       0      0  127.0.0.1.61725        127.0.0.1.7000         ESTABLISHED
tcp4       0      0  127.0.0.1.61724        127.0.0.1.7000         ESTABLISHED
tcp4       0      0  127.0.0.1.7000         127.0.0.1.61661        ESTABLISHED
tcp4       0      0  127.0.0.1.7000         127.0.0.1.61660        ESTABLISHED
tcp4       0      0  127.0.0.1.61661        127.0.0.1.7000         ESTABLISHED
tcp4       0      0  127.0.0.1.7000         127.0.0.1.61659        ESTABLISHED
tcp4       0      0  127.0.0.1.61660        127.0.0.1.7000         ESTABLISHED
tcp4       0      0  127.0.0.1.61659        127.0.0.1.7000         ESTABLISHED
tcp4       0      0  127.0.0.1.7000         127.0.0.1.61654        ESTABLISHED
tcp4       0      0  127.0.0.1.61654        127.0.0.1.7000         ESTABLISHED
tcp46      0      0  *.7000                 *.*                    LISTEN  
```


Test logs are here:

**Comment by mrniko** [comment]
I fixed this scenario

> Kill SIGSTOP A, then A fails and B becomes master. Then kill SIGCONT A and let A becomes slave
Now A should have around 64 *2 connections, B should have 64 connections
Please correct me if I was wrong.

**Comment by stevenli1217** [comment]
Hi @mrniko  Thank you for clarification.

I run a quick test to verify this use case bu issue remains. 
1. Kill sigstop A, master A becomes fail, slave B becomes master
2. Kill sigcont A, A becomes slave.
3. The total connections to A are doubled. 

I waited for a long time(5 mins, which is larger than idleConnectionTimeout) and no connection is killed.

**Comment by mrniko** [comment]
> slave B becomes master

Does master has doubled connections in this case?

**Comment by stevenli1217** [comment]
Both A and B's connections are doubled.

**Comment by mrniko** [comment]
> Kill sigstop A, master A becomes fail, slave B becomes master

Could you check only this case and share Redisson log output?

**Comment by stevenli1217** [comment]
Kill sigstop 7001, 7003 becomes master, kill sigcont 7001 and it becomes slave

Both  7001 and 7003's connections are doubled.  I waited for 2-3 mins and no connection is killed.

Configuration:
```
idleConnectionTimeout: 30000
  slaveConnectionMinimumIdleSize: 16
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 16
  masterConnectionPoolSize: 64
```

logs are here: https://drive.google.com/file/d/1ip7y9OlqkqXozoSKEUijRQ68Tn30-ohT/view?usp=sharing

**Comment by mrniko** [comment]
Thanks for the log!

Could you try this case only: `Kill sigstop A, master A becomes fail, slave B becomes master`
with version attached and share output?

[redisson-3.12.6-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4585629/redisson-3.12.6-SNAPSHOT.jar.zip)

**Comment by stevenli1217** [comment]
I use the latest jar and did the test:
1. Kill master 7003 and slave 7001 becomes the new master. 7003 is fail.  [12:51:07]
2. 7001's connections are doubled.  [12:51:10]
3. Wait for a long time and no connection is killed [12:54:54]

log is here: https://drive.google.com/file/d/1CiCh_aGiwNeenfNCmyakzSMYdPf6LB8U/view?usp=sharing

**Comment by mrniko** [comment]
> 7001's connections are doubled

since it serves slave connections as well.

**Comment by stevenli1217** [comment]
Yes. It make sense.

My question is : Will Redisson kill those slave connections after idleConnectionTimeout ?

> > 7001's connections are doubled
> 
> since it serves slave connections as well.

**Comment by mrniko** [comment]
The issue I fixed is 2xmasterConnectionMinimumIdleSize. So total connections was 2x(masterConnectionMinimumIdleSize) + 1x(slaveConnectionMinimumIdleSize). Now it remains:
1x(masterConnectionMinimumIdleSize) + 1x(slaveConnectionMinimumIdleSize).

These connections won't be killed since it equals to min. idle size connection pool.

**Comment by stevenli1217** [comment]
Got it. For each redis node in cluster, Redisson will create 2x(masterConnectionMinimumIdleSize) + 1x(slaveConnectionMinimumIdleSize).

Could you please share the link of the PR for this fix? 

Many thanks!

**Comment by mrniko** [comment]
> For each redis node in cluster, Redisson will create 2x(masterConnectionMinimumIdleSize) + 1x(slaveConnectionMinimumIdleSize).

Only for master remains single (without slaves) in its partition.

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/commit/53fbbf7d1fed02fdf9b44e2be9231c4eb461007b

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/commit/f4ad9382e12e4178c794d0fa5d3ab6fa78d9afcb

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/2672
