### ISSUE TITLE
Is tryLock() method expected to return false when redis is not available

### ISSUE THREAD

**Issue by coldray** [redisson/redisson#2801]
### Expected behavior
tryLock() method return false after certain time when redis is not available

### Actual behavior
tryLock() method is hanging forever

### Steps to reproduce or test case
```
boolean res = lock.tryLock(1, 1, TimeUnit.SECONDS);
if (res) {
   try {
     ...
   } finally {
       lock.unlock();
   }
}
```
when application starts, the redis server is there, then bring down the redis. 

Redis version
5.0
Redisson version
3.12.5
Redisson configuration
local redis docker without authentication

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/2790

**Comment by coldray** [comment]
Thanks for the fix. Now I'm using redisson 3.13.0. I have a follow-up question for that, in my code, I am using 

```
DEFAULT_LOCK_WAIT_SECS = 200L;
DEFAULT_LOCK_EXPIRE_SECS = 300L;
long cur = System.currentTimeMillis();
 try {
            if (lock.tryLock(DEFAULT_LOCK_WAIT_SECS, DEFAULT_LOCK_EXPIRE_SECS, TimeUnit.MILLISECONDS)) {
                return lock;
            } 
        }  finally {
            log.error("redis latency: {}", System.currentTimeMillis() - cur);
        }
```
In the normal case, I expect the max time to try to acquire the lock to be 200ms, if the redis server is not available and I still expect the function tryLock should return within 200ms or a bit more than 200ms, but the actual redis latency log shows the average latency is more than 4s in my local testing. 
Is my understanding correct in this case?

**Comment by coldray** [comment]
There is another thing I've tried. I'm using redisson library 3.13.0. I found that in the tryLock() function, even if I set DEFAULT_LOCK_WAIT_SECS extremely small, I can still get the returned boolean as true in my local test environment. 
Here is my example:
```
DEFAULT_LOCK_WAIT_SECS = 1L;
DEFAULT_LOCK_EXPIRE_SECS = 30000000000L;
boolean res = lock.tryLock(DEFAULT_LOCK_WAIT_SECS, DEFAULT_LOCK_EXPIRE_SECS, TimeUnit.NANOSECONDS);
if (res) {
   try {
     ...
   } finally {
       lock.unlock();
   }
}
```
The code blcok inside try is being exectued even if I set the DEFAULT_LOCK_WAIT_SECS to be 1L NANOSECONDS. Could you help me identify whether it's a bug or there is something I misunderstand? Thanks in advance.

**Comment by mrniko** [comment]
> The code blcok inside try is being exectued even if I set the DEFAULT_LOCK_WAIT_SECS to be 1L NANOSECONDS. Could you help me identify whether it's a bug or there is something I misunderstand?

wait timeout is applied only after first attempt to acquire lock.

**Comment by coldray** [comment]
Is it possible to apply the wait timeout even for the first attempt?

**Comment by mrniko** [comment]
I'm afraid no, since if command was sent succefully it's impossible to cancel it.
