### ISSUE TITLE
MOVED redirection loop detected with AWS Elasticache redis

### ISSUE THREAD

**Issue by ddinde** [redisson/redisson#3162]
Getting following error:

`org.redisson.client.RedisException: MOVED redirection loop detected. Node redis://xxxxx-cache-0001-001.xxxxx-cache.yyyyy.usw2.cache.amazonaws.com:6379 has further redirect to redis://xxxxx-cache-0001-001.xxxxx-cache.yyyyy.usw2.cache.amazonaws.com:6379`

We are using redisson 3.13.4 ( tried with 3.13.6 also) with AWS Elasticache Redis.
For our internal testing we created AWS Elasticache Redis cluster with following configuration:
Shards: 1 
replica: 1
Engine compatibilty: 5.0.6
readMode=MASTER.

Connecting to configuration endpoind.
In the error you see 'redis://' but we are using 'rediss://' , there is another bug in RedisException where 'redis://' ( without extra 's') is hardcoded.

It was working fine till last week.

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by ddinde** [comment]
Great, when 3.13.7 would be available on maven ?

**Comment by ddinde** [comment]
I created a build using master and i still see same error, only difference now is that, 'rediss://' ( with extra 's' is there , which is correct)

`org.redisson.client.RedisException: MOVED redirection loop detected. Node rediss://xxxxx-cache-0001-002.xxxxx-cache.yyyyy.usw2.cache.amazonaws.com:6379 has further redirect to rediss://xxxxx-cache-0001-002.xxxxx-cache.yyyyy.usw2.cache.amazonaws.com:6379
        at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:404)
        at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:164)
        at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
        at org.redisson.client.protocol.CommandData.tryFailure(CommandData.java:78)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:317)
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:178)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:102)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:830)
`

**Comment by mrniko** [comment]
Can you try to recreate AWS instance?

**Comment by ddinde** [comment]
I was trying to avoid that, as we may not hit this specific scenario again.
AWS redis cluster that we are using was created 2 months ago and it was working fine till last week. So If we recreate instance,  and if we don't hit that scenario then we wouldn't know what caused this issue.

OR do you think because of this bug, some erroneous entries are made, which  won't happen after this fix on fresh cluster.

**Comment by mrniko** [comment]
OK. Let's trace it. I'll make special Redisson version with additional logging for this issue.

**Comment by mrniko** [comment]
Could you share log with logging level = 'TRACE' for `org.redisson` package?

**Comment by ddinde** [comment]
After further investigation, we found  that problem was in our configuration.  We have support for both clustered and non clustered mode. Configuration which causes the switch was changed incorrectly, because of which AWS Elasticache redis cluster configuration endpoint was getting used with 'ReplicatedServersConfig' instead of 'ClusterServersConfig'.

Good thing I guess is,  through this ticket, 'redis' vs 'rediss' scheme related issue got fixed.

Thanks for your help, appreciate quick responses on this ticket.
