### ISSUE TITLE
confused in container use

### ISSUE THREAD

**Issue by wufengke** [redisson/redisson#3435]
I am using redission 3.13.4 in k8s with cluster mode in 3 master 3 slave. I meet some problem when i delete redis pod one by one manually to simulate k8s node shutdown, after the redis pods reruning on other node, still have
some errors happened and never recover until i restart the business client pod where redisson in.

one like bellow:

It seems connecting to an old server ip.

hope to get your help

**Comment by wufengke** [comment]
another error
![image](https://user-images.githubusercontent.com/4140747/108813060-3ad90e80-75eb-11eb-956b-4d6fa87e93ff.png)

**Comment by wufengke** [comment]
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 600
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 6000
  password: ${REDIS_PWD}
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 100
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
    - ${REDIS_NODE_1}
    - ${REDIS_NODE_2}
    - ${REDIS_NODE_3}
    - ${REDIS_NODE_4}
    - ${REDIS_NODE_5}
    - ${REDIS_NODE_6}
    #- "redis://10.182.1.167:8271"
    #- "redis://10.182.1.167:8272"
    #- "redis://10.182.1.167:8273"
  scanInterval: 1000
  pingConnectionInterval: 30000
  keepAlive: false
  tcpNoDelay: false
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: "NIO"

**Comment by mrniko** [comment]
Can you set `debug` logging level for `org.redisson.cluster.ClusterConnectionManager` and share output?

**Comment by wufengke** [comment]
[redisson.backend-web.log](https://github.com/redisson/redisson/files/6034899/redisson.backend-web.log)
loop reconnecting to and old address?

**Comment by mrniko** [comment]
try to define ip addresses in configuration

**Comment by mrniko** [comment]
Fixed

**Comment by wufengke** [comment]
Sorry for the late reply.

I change to ip addresses in config. But the problem remains, whether or not update your repaired code in version 3.13.4

I repaired it on my side, but not sure whether it is reasonable.

After changed to ip addresses and shut down the cluster. I find the problem in  method scheduleClusterChangeCheck(cfg). The nodes to be checked comes from lastPartitions variable.
![image](https://user-images.githubusercontent.com/4140747/109966455-3fa86b80-7d2b-11eb-804f-3d5a9da4299e.png)
But the lastPartitions variable value mybe broken at a certain time, and keeping some old values or empty. Some times the schdule is broken and stoped to check, but I can't find the cause of the problem.

I repaire it by rebuilding the partitions from configed address just like the constructor does.

![image](https://user-images.githubusercontent.com/4140747/109968220-610a5700-7d2d-11eb-835d-e1da1a2d6b88.png)

at least work well on my local...

@mrniko

**Comment by mrniko** [comment]
> But the lastPartitions variable value mybe broken at a certain time, and keeping some old values or empty. Some times the schdule is broken and stoped to check, but I can't find the cause of the problem.

This may happen if one of your cluster node returns wrong cluster state info

**Comment by avcad** [comment]
I am following this thread so today I created a test. I containerized the code below, running Redisson 3.15.1.

I am using Bitnami Redis Cluster and deleting Redis nodes e.g. kubectl delete pod  redis-redis-cluster-0 -n redis.

I first noticed errors even after restarting the client pod running Redisson.  I realized that sometimes Redis had
the old IP (from before the restart) in nodes.conf. I just upgraded to the latest binami Redis, and I dont see the 
problem anymore. nodes.conf has the new IPs on all the nodes.

Redisson is working ok when I delete one node. I did notice that when I delete all 3 nodes at the same time,
and they all come back with different IPs, Redisson continues to try to use the old IPs:
org.redisson.cluster.ClusterConnectionManager checkClusterState Can't update cluster state io.netty.channel.ConnectTimeoutException: connection timed out: (old IP)

so that scenario is falling. I guess Redisson is not attempting to get the new IPs using the hostnames when that happens.

```
public class Main {
	
	private static final String SP_YAML_CONFIG_FILE  = "CACHE_MANAGER_CONFIG";
	private static final String HOSTNAME             = "HOSTNAME";
	
	// Node 0
	// ------
	// 127.0.0.1:6379> CLUSTER KEYSLOT keyslot-003
	// (integer) 3040
	
	// Node 1
	// ------	
	// 127.0.0.1:6379> CLUSTER KEYSLOT keyslot-510
	// (integer) 9026
	
	// Node 2
	// ------	
	// 127.0.0.1:6379> CLUSTER KEYSLOT keyslot-930
	// (integer) 12353
	
	private static final String HASH_KEY_FOR_NODE0 = "{keyslot-003}-"; //  CLUSTER KEYSLOT keyslot-003: 3040
	private static final String HASH_KEY_FOR_NODE1 = "{keyslot-510}-"; //  CLUSTER KEYSLOT keyslot-510: 9026
	private static final String HASH_KEY_FOR_NODE2 = "{keyslot-930}-"; //  CLUSTER KEYSLOT keyslot-930: 12353
	
	private static final String [] HASH_KEYS = {
		HASH_KEY_FOR_NODE0,
		HASH_KEY_FOR_NODE1,
		HASH_KEY_FOR_NODE2
	};
	
	private static final int DEFAULT_SLEEP = 3000 ;// 3 seconds
	
	private static final String sourceClass = Main.class.getName();
	
	private static final Logger logger = Logger.getLogger(sourceClass);

	public static void main(String[] args) {

		final String configFile = System.getenv( SP_YAML_CONFIG_FILE );
		
		if ( configFile == null || configFile.isEmpty() ) {
			logger.severe("Environment variable " + SP_YAML_CONFIG_FILE + " is not defined");
			System.exit(-1);
		}
		
		String hostname  = System.getenv( HOSTNAME );    
		
		if ( hostname == null ) {
			hostname = "null";
		}
	
		try {
						
			final Config config = Config.fromYAML(new File( configFile ));
			
			final RedissonClient redisson = Redisson.create(config);
			
			int attempt = 1;

			while ( true ) {
				
				for ( int n = 0; n < HASH_KEYS.length; n++ ) {
					
					final String bucketName = HASH_KEYS[n] + hostname;
					
					try {
						
						redisson.getBucket( bucketName ).set( attempt );
						logger.info( "Updated bucket " + bucketName + " in node " + n + ": " + attempt );
						
					} catch ( RedisException r ) {									
						logger.info( "Failed to write bucket " + bucketName + " on node " + n + " with error: " + r );
					}					
				}
				
				try {
					Thread.sleep( DEFAULT_SLEEP );
				} catch (InterruptedException e) {
					logger.severe("sleep interrupted: " + e );
				}
				
				attempt++;
			}

		} catch (IOException e) {
			logger.severe("Failed to create client. Exiting container");
		}
				
		System.exit(-1);
	}

}
```

**Comment by mrniko** [comment]
@avcad 

At the moment, hostname resolving works only for a single Redis endpoint defined in config. (it works for AWS Elastiache config endpoint).

**Comment by mrniko** [comment]
@avcad 

Can  you create separate issue for your comment?

**Comment by wufengke** [comment]
I use the ip port address(k8s service ip port). In 'delete all 3 nodes at the same time' scenario, some other errors like 'slot for 1212 not ready...'(not exactly) will be find when you executing some redis commands randomly after the cluster recovered long time later. I logged the lastPartitions variable value and find the broken data never recover in it.
Maybe I can reproduce it in a future weekend and post the error out...

**Comment by mrniko** [comment]
@wufengke 

how to reproduce it? just restart all nodes in cluster at the same moment?

**Comment by wufengke** [comment]
> @wufengke
> 
> how to reproduce it? just restart all nodes in cluster at the same moment?

yes,  only this action and wait the redis cluster recover

**Comment by mrniko** [comment]
@wufengke 

Unable to reproduce. Here is my test:

```java
    @Test
    public void testFailoverInClusterAll() throws Exception {
        RedisRunner master1 = new RedisRunner().port(6890).randomDir().nosave();
        RedisRunner master2 = new RedisRunner().port(6891).randomDir().nosave();
        RedisRunner master3 = new RedisRunner().port(6892).randomDir().nosave();
        RedisRunner slave1 = new RedisRunner().port(6900).randomDir().nosave();
        RedisRunner slave2 = new RedisRunner().port(6901).randomDir().nosave();
        RedisRunner slave3 = new RedisRunner().port(6902).randomDir().nosave();

        ClusterRunner clusterRunner = new ClusterRunner()
                .addNode(master1, slave1)
                .addNode(master2, slave2)
                .addNode(master3, slave3);
        ClusterProcesses process = clusterRunner.run();

        Thread.sleep(2000);

        Config config = new Config();
        config.useClusterServers()
        .setLoadBalancer(new RandomLoadBalancer())
        .addNodeAddress(process.getNodes().stream().findAny().get().getRedisServerAddressAndPort());
        RedissonClient redisson = Redisson.create(config);

        List<RFuture<?>> futures = new ArrayList<RFuture<?>>();
        CountDownLatch latch = new CountDownLatch(1);
        Thread t = new Thread() {
            public void run() {
                for (int i = 0; i < 1000; i++) {
                    RFuture<?> f1 = redisson.getBucket("i" + i).getAsync();
                    RFuture<?> f2 = redisson.getBucket("i" + i).setAsync("");
                    RFuture<?> f3 = redisson.getTopic("topic").publishAsync("testmsg");
                    futures.add(f1);
                    futures.add(f2);
                    futures.add(f3);
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                    if (i % 100 == 0) {
                        System.out.println("step: " + i);
                    }
                }
                latch.countDown();
            };
        };
        t.start();
        t.join(1000);

        process.getNodes().forEach(n -> n.restart(10));

        assertThat(latch.await(105, TimeUnit.SECONDS)).isTrue();

        int errors = 0;
        int success = 0;
        int readonlyErrors = 0;

        for (RFuture<?> rFuture : futures) {
            rFuture.awaitUninterruptibly();
            if (!rFuture.isSuccess()) {
                errors++;
            } else {
                success++;
            }
        }

        redisson.shutdown();
        process.shutdown();

        assertThat(readonlyErrors).isZero();
        assertThat(errors).isLessThan(300);
        assertThat(success).isGreaterThan(2700);
    }
```

Did you try to reduce `pingConnectionInterval` to 5000

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/3587
