### ISSUE TITLE
Redisson AWS ElastiCache cluster discovery after re-sharding failing

### ISSUE THREAD

**Issue by milicicm** [redisson/redisson#3541]
We are using Redisson to connect to an AWS ElastiCache Redis cluster. We are seeing an elevated number of exceptions after we scale the cluster up or down and redistribute the slots.

**Expected behavior**
Redisson will pick up the new topology and slot distribution after the re-sharding is done.

**Actual behavior**
We are seeing these exceptions:

```
org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=XXXXX, addr=redis://XXXX:XXXX, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet. Increase value of retryAttempts and/or retryInterval settings.
```

The exceptions persist for hours after the re-sharding is done. We don't see these exceptions if we restart our service.

**Steps to reproduce or test case**

* Initialize Redisson client and connect to AWS ElastiCache cluster
* Add or remove shards
* Wait until cluster is in active state and slot redistribution is done
* Try to read from the cluster

**Redis version**
AWS ElastiCache Redis
Engine: Clustered Redis
Encryption-in-Transit: No
Redis Version 6.0.5

**Redisson version**
3.15.0

**Redisson configuration**
```
...
.useClusterServers()
.addNodeAddress(###)
.setScanInterval(100)
.setRetryInterval(50)
.setRetryAttempts(2)
.setPingConnectionInterval(1000)
.setTimeout(30000);
...
```

All other values are default

**Comment by milicicm** [comment]
Adding a bit more context. The error we are seeing is similar to the one fixed in #2750. The version we are using should include that fix. In #2837, it's stated that Redisson should automatically discover new nodes, which doesn't happen in our case. 

I've connected to the cluster manually and made sure that the new topology looks OK using CLUSTER NODES command.

**Comment by avcad** [comment]
3.15.1 has a fix that looks related:
Fixed - continuous reconnecting to broken host if it was defined as hostname in Redisson Cluster config

https://github.com/redisson/redisson/releases/tag/redisson-3.15.1

**Comment by mrniko** [comment]
Please provide log with `debug` logging level for `org.redisson` package

**Comment by milicicm** [comment]
Client is sending HGET commands at a constant throughput before and after scaling up the ElastiCache Redis cluster. Adding timeline with DEBUG / TRACE logs on one of our hosts:

1. Requested addition of one shard to the cluster at 6:43
2. Shard added to the cluster at 6:49
3. Log entires for one request two hours after:

```
2021-04-09T08:51:27.145Z [DEBUG] cluster nodes state got from (Bobcat-20) org.redisson.cluster.ClusterConnectionManager: slot 13879 for <key>
```

```
2021-04-09T08:51:27.145Z [DEBUG] ed6c0fd9-a57f-4c1b-b3fd-a75e5a000605 (Bobcat-20) org.redisson.command.RedisExecutor: acquired connection for command (HGET) and params [<key>, PooledUnsafeDirectByteBuf(ridx: 0, widx: 22, cap: 256)] from slot NodeSource [slot=13879, addr=null, redisClient=null, redirect=null, entry=null] using node ip-10-0-102-120.ec2.internal/10.0.102.120:6379... RedisConnection@63589843 [redisClient=[addr=redis://10.0.102.120:6379], channel=[id: 0x14b71955, L:/10.0.155.129:47790 - R:ip-10-0-102-120.ec2.internal/10.0.102.120:6379], currentCommand=null]
```

```
2021-04-09T08:51:27.146Z [TRACE] (redisson-netty-2-30) org.redisson.client.handler.CommandDecoder: reply: -MOVED 13879 10.0.131.227:6379 |, channel: [id: 0x14b71955, L:/10.0.155.129:47790 - R:ip-10-0-102-120.ec2.internal/10.0.102.120:6379], command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@fa5e5c6(incomplete)], command=(HGET), params=[<key>, PooledUnsafeDirectByteBuf(ridx: 0, widx: 22, cap: 256)], codec=org.redisson.client.codec.StringCodec]
```

```
2021-04-09T08:51:27.146Z [DEBUG] (redisson-netty-2-30) org.redisson.command.RedisExecutor: connection released for command (HGET) and params [<key>, PooledUnsafeDirectByteBuf(ridx: 0, widx: 22, cap: 256)] from slot NodeSource [slot=13879, addr=null, redisClient=null, redirect=null, entry=null] using connection RedisConnection@63589843 [redisClient=[addr=redis://10.0.102.120:6379], channel=[id: 0x14b71955, L:/10.0.155.129:47790 - R:ip-10-0-102-120.ec2.internal/10.0.102.120:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@fa5e5c6(failure: org.redisson.client.RedisMovedException)], command=(HGET), params=[<key> PooledUnsafeDirectByteBuf(ridx: 0, widx: 22, cap: 256)], codec=org.redisson.client.codec.StringCodec]]
```

```
2021-04-09T08:51:27.204Z [DEBUG] (redisson-timer-4-1) org.redisson.command.RedisExecutor: attempt 1 for command (HGET) and params [<key>, PooledUnsafeDirectByteBuf(ridx: 0, widx: 22, cap: 256)]

```

```
2021-04-09T08:51:27.279Z [DEBUG] (redisson-timer-4-1) org.redisson.command.RedisExecutor: attempt 2 for command (HGET) and params [<key>, PooledUnsafeDirectByteBuf(ridx: 0, widx: 22, cap: 256)]
```

```
2021-04-09T08:51:27.375Z [ERROR] <service_log> org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=13879, addr=redis://10.0.131.227:6379, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet. Increase value of retryAttempts and/or retryInterval settings. <stack trace>
```

The client was sending CLUSTER NODES commands up until the moment when the new shard was added, these are last entries for those commands:

```
2021-04-09T06:49:06.509Z [TRACE] (redisson-netty-2-7) org.redisson.client.handler.CommandEncoder: channel: [id: 0x0fbfb8d5, L:/10.0.155.129:54628 - R:/10.0.119.101:6379] message: *2

|$7

|CLUSTER

|$5

|NODES

|
```

```
2021-04-09T06:49:06.512Z [TRACE] (redisson-netty-2-7) org.redisson.client.handler.CommandDecoder: reply: $14144

|2f31de5fa60d02607e9a3aad0fa69a7bc06b6870 10.0.123.100:6379@1122 master - 0 1617950942000 16981 connected 9744-9831 9903-9963 9965-10052 10202-10203 10799 10923 11086-11141 12292 12406-12415 12417-12454 12456-12470 12572-12575 12894-12942 14200-14276 14278-14302 14862 15110 15510-15514
|0be46429cd7fe0b362043314053530c36bac2d87 10.0.119.155:6379@1122 slave 7b1b3516fd375ed4120b570895a1a6ede8273b82 0 1617950940000 12288 connected
|6bd75f1f698564977d37d3f6ff1cdce2cb84a8de 10.0.173.224:6379@1122 slave 2f4e367ca9ad23f3e31b3c1c71196379da909256 0 1617950945000 17272 connected
|21ddb5c6f2fb0278e7693dfb358c336580e052f4 10.0.120.42:6379@1122 slave 62d75a375183cf25ca18088236678122a70f9852 0 1617950940000 16980 connected
|57e9fb2e40439cf090ad3b46cfa3b2ec1eff9df8 10.0.148.127:6379@1122 slave 0bdaad94aa326c17ba2d56366b158c00e057dc5e 0 1617950942000 12304 connected
|93f1c0d20e095c69df580035eafce5481986182e 10.0.102.120:6379@1122 slave a8c916be600d1f893f53ab143c3373492b836fe2 0 1617950945000 12302 connected
|41a845737ebb80be8825e1607965e6190a327f59 :6379@1122 slave 143413eea38127b1fea26e0944ff904810ac3964 0 1617950942000 12295 connected
|f7b27973c60b2525ea8c507557bdbebb8e2b003f 10.0.187.124:6379@1122 slave 63c69478f42e86ea13cf423b8dcb34e19eb16e48 0 1617950941000 12303 connected
|0ab5dc80a19aeb63d998e907d1443a4277e70360 10.0.157.161:6379@1122 slave b66f89aa6209f12a33a27f824107af9272c7584c 0 1617950942819 17532 connected
|5ee6b7d87531feb45df96b06bcf6f266cd5cd3a7 10.0.189.119:6379@1122 slave 767ba227808ab00d4bc8bf1ca5a534174bbfd33b 0 1617950941000 17426 connected
|f905fad527694b26bdd7ca27da2eaeed0c6ab063 10.0.173.242:6379@1122 master - 0 1617950941823 16689 connected 2325-2353 4236-4270 4272-4289 4291-4324 4326-4379 4515-4518 4520-4553 4555-4623 4625-4720 4722-4745 4855-4878 5297-5303 5305-5330 5392-5394 5399-5427 5429-5463 5571-5572 6484 11333 11403
|58495ec6af33d6afad82f07679399b2744f0e419 10.0.128.49:6379@1122 slave c52cd11eb53c5b4025ed5b8be92d84fe7f21ab72 0 1617950942000 16838 connected
|767ba227808ab00d4bc8bf1ca5a534174bbfd33b 10.0.144.168:6379@1122 master - 0 1617950943570 17426 connected 1209-1276 1346-1360 2119-2179 2500-2517 2519-2544 2546-2559 3428-3430 3440-3446 3632-3692 4391-4419 4488-4514 4746-4801 5573-5578 6980 7400 7524 9168-9171 9173-9202 9204-9272 11623-11645
|b5b7e5c6b0c2ad1462dfba5cdd4a6b038de636ae 10.0.150.18:6379@1122 slave 011fb99ed1ece52b34ab88c0b393e17304ba76ab 0 1617950943000 12301 connected
|9cb44c9efaa35cd9485fc2180683afbb82c65c99 10.0.122.80:6379@1122 slave 2e5424028508ef4fc8c3bf0bb0ae2d03bf39110e 0 1617950939000 16530 connected
|edbcbdd1435fc42e9d1bcceabc32f8ba0820cf48 10.0.114.189:6379@1122 slave 1a84f052efc69089e00f9652943219f91a505f57 0 1617950943570 17476 connected
|7b1b3516fd375ed4120b570895a1a6ede8273b82 10.0.146.43:6379@1122 master - 0 1617950944766 12288 connected 9832 9861-9902 9964 10080 10212 10512 10644 11142-11162 11269-11275 12075-12079 12081-12101 13579-13633 13862-13864 14349-14350 14412-14515 14978-14985 14987-15037 15121-15137 15139-15291 15306-15312 15381-15405 15467-15469 15585-15589
|ed8b8ddf1c1ae51f30170e83e81908aa2f1ad84e 10.0.175.161:6379@1122 slave 2e3c6da8c12218881d0d0a83153d3488b63fd0be 0 1617950945963 1 connected
|2e3c6da8c12218881d0d0a83153d3488b63fd0be 10.0.131.227:6379@1122 master - 0 1617950945863 1 connected
|1a84f052efc69089e00f9652943219f91a505f57 10.0.154.153:6379@1122 master - 0 1617950939000 17476 connected 3273 4218-4221 4420-4456 4458-4465 4467-4487 6305-6347 9289-9335 9337 9630-9682 10064-10079 10081-10114 10348-10448 10509-10511 10513-10550 10552-10576 10836-10893 11071-11083 11171 11543-11562 12249 14366 15406
|3d4e1f55a2cd3e3ad4f0ad81743cb6b2f2a9d1ad 10.0.167.191:6379@1122 slave 8117e080fde12d7e05d1dfa8e9fc41437a28ea8f 0 1617950939000 17427 connected
|62d75a375183cf25ca18088236678122a70f9852 :6379@1122 master - 0 1617950942000 16980 connected 4624 5579-5642 5644-5654 7057-7132 7164-7168 7170-7205 7207-7275 7277-7300 7302-7329 7331-7356 7649-7733 7735-7796 8353 9079 9559 10303 11032-11035 11294-11321
|c52cd11eb53c5b4025ed5b8be92d84fe7f21ab72 10.0.119.142:6379@1122 master - 0 1617950939000 16838 connected 2354-2385 2387-2420 2422-2485 3447-3471 3567-3606 3608-3631 3693-3725 3919-3924 3926-3953 3955-3994 3996-4031 4044-4048 4050-4085 4087-4138 4140-4152 4222-4235 4554 5304 5428 11651 12263-12291 12293-12300
|60ac498383babcf301c35cf57dc6273b96b891f8 10.0.152.226:6379@1122 slave f905fad527694b26bdd7ca27da2eaeed0c6ab063 0 1617950944000 16689 connected
|86b94cb0869e6b76d1bed2f2ccec15803f795a28 10.0.164.188:6379@1122 slave 85c94ccf91e18c3d28659d1e5e1a032817a838c7 0 1617950945000 12287 connected
|8d8d79d9440ca398feee40560754d0bc5e77d6d2 10.0.190.2:6379@1122 slave 018956fd15060793eefcf18808a9b056c4a3ebc7 0 1617950944000 17041 connected
|a867f13af517cd2a141bc289d211d00a78b4c731 10.0.134.77:6379@1122 master - 0 1617950941000 12300 connected 10 64 142 196 258 390 491 592 724 786 821 856 918 988 1082 12143-12211 12213-12248 12250-12261 12376-12392 12394-12397 12400-12405 12943-12982 12984-12991 13860-13861 13922-14028 14030 14353-14365 14367-14411 14593-14598 14626-14640 14642-14664 14766-14772 14774-14785 15038-15045 15138 15292-15293 15313-15380 15407-15426 15428-15432 15837-15838
|8117e080fde12d7e05d1dfa8e9fc41437a28ea8f 10.0.105.161:6379@1122 master - 0 1617950941000 17427 connected 103 227 2839-2892 2895-2916 2918-2942 3726-3730 3732-3870 3872-3918 4032-4043 10116-10201 10204-10211 10213-10260 10793-10798 10800-10832 10894-10922 11401 11985 12262
|b28ac4d5c6975152131338d012d8ca88c0cf7564 10.0.133.93:6379@1122 master - 0 1617950945000 17531 connected 335-389 391-403 486-490 492-560 669-677 739-785 787-820 822-855 857-917 919-940 945 1301 2032-2042 3244-3272 3274 11166-11170 11172-11268 11291-11293 12003-12015 12140-12142 14986
|7346e854cda5bc7d92b4cb1b154164dc09ec9128 10.0.107.82:6379@1122 slave 9c9f3d3b4f0baef43204e75888801aeac3acede2 0 1617950943616 12289 connected
|5205b8efd8db4d65606a899040f077a7bc2f80c0 10.0.181.182:6379@1122 master - 0 1617950942000 12294 connected 2421 3925 3995 4049 4290 4380-4390 4457 4519 4721 4853 4879-4883 4885-5007 5009-5296 5395 5737-5766 10115 11485-11493 11495-11526 11528-11542 11603-11612
|011fb99ed1ece52b34ab88c0b393e17304ba76ab 10.0.99.114:6379@1122 master - 0 1617950945562 12301 connected 1177 1330 1425 1462 1578 1710 1826 1954-2031 2641-2668 2670-2748 3399-3415 3522-3542 8437-8440 9386-9468 12809-12811 13179-13198 13745-13780 13782-13833 14579-14592 14830-14833 15433-15438 15844-15927
|2e5424028508ef4fc8c3bf0bb0ae2d03bf39110e :6379@1122 master - 0 1617950943570 16530 connected 6703-6731 6733-6855 6857-6912 8800-8802 8804-8838 8955 9683 12416 13413-13565 13634-13648 13650-13658 14666-14737 14739-14765
|59a8c492a1d1651aac35af206f2c9b6ebc167ee5 10.0.113.17:6379@1122 slave d286d664dfef8c7aa6eee98bfe56a683da37f4b1 0 1617950941000 14739 connected
|018956fd15060793eefcf18808a9b056c4a3ebc7 10.0.137.45:6379@1122 master - 0 1617950941000 17041 connected 941-944 946-987 989-1081 1083-1091 1278-1300 1302-1319 1329 1331-1339 1787-1819 2669 2953-3040 3042-3078 3080-3099 3521 4466 7378-7380 7586-7647 8252-8263 8265-8304 9833-9860
|e8f1273794167a0abf021e26f7f71fc4fe23b73d 10.0.161.72:6379@1122 slave bb69a1c203f9ee5fa6c14d7bdd30493390accc20 0 1617950941000 17530 connected
|b584192c067b3627b2a00afdb6bdf36011402ab6 10.0.169.76:6379@1122 slave 2f31de5fa60d02607e9a3aad0fa69a7bc06b6870 0 1617950941000 16981 connected
|57bab188484251b5fabad10c4d7248637f3781cf 10.0.119.185:6379@1122 slave 25ac5bb6505008716f857fb5d3a38e57d784fb49 0 1617950943073 12293 connected
|2c50405871afeb24c8833b2638b6c80a68b2e614 10.0.99.197:6379@1122 slave 5205b8efd8db4d65606a899040f077a7bc2f80c0 0 1617950942000 12294 connected
|bb37e9019ac864d34dfbb25c72a79216fbc0ff7e 10.0.113.40:6379@1122 slave b28ac4d5c6975152131338d012d8ca88c0cf7564 0 1617950943000 17531 connected
|f8f0f3a534f363e195c369b94ba4bb3669d2f512 10.0.149.137:6379@1122 slave 29dac3179ac29ff19b669a65747eb04e92bf378c 0 1617950942000 12305 connected
|83a9c50f52bb45c10593677d675565336b68e5e0 10.0.156.150:6379@1122 slave 85fc2c5b4db75d1cce2d51027166c5644e005aa3 0 1617950942619 17304 connected
|b66f89aa6209f12a33a27f824107af9272c7584c 10.0.119.101:6379@1122 myself,master - 0 1617950941000 17532 connected 561-591 593-668 1093-1176 1178-1205 1340-1345 1402-1424 1426-1461 1463-1530 1820-1825 1827-1953 3149 4166 12992-13005 13338-13353 13566 13859 15724 15778
|a6caab74c3ad3a155586cccf1961e44b4efaf636 10.0.110.172:6379@1122 master - 0 1617950942618 12297 connected 1320-1328 2043-2118 2180-2185 2893-2894 3109-3148 3150-3177 4153-4165 4167-4192 4194-4217 10551 11563-11602 12016-12074 12080 12102-12106 12125 12212 12323 12393 12455 12525 12587 12641 12773 12851 12983 15441-15466 15668-15723 15725-15777 15779-15836 15839-15843 16379-16380
|bb69a1c203f9ee5fa6c14d7bdd30493390accc20 10.0.114.240:6379@1122 master - 0 1617950942000 17530 connected 5945-5967 6105-6109 6348-6372 6418-6483 6485-6514 6516-6607 6609-6616 7163 7500-7503 7579-7585 8052 8122 8176 8229 8305-8319 8557-8563 8598-8613 8732-8739 8803 9350-9385 9469-9515 9615-9629 10053-10063 10707-10712 11327-11332 11334-11361 11363-11400 11402 11404-11417
|d286d664dfef8c7aa6eee98bfe56a683da37f4b1 10.0.179.226:6379@1122 master - 0 1617950943121 14739 connected 289-300 3275-3278 5655-5688 6007-6011 6133-6135 7024-7056 8000-8018 8020-8051 8053-8121 8123-8150 8152-8175 8177-8193 8195-8228 8230-8245 8425-8436 8441-8457 8459-8511 8513-8556 8618-8643 8645-8681 8720-8725 11279 11457 13142
|a8c916be600d1f893f53ab143c3373492b836fe2 :6379@1122 master - 0 1617950943000 12302 connected 8726-8731 8758-8760 9124-9133 10326-10347 10449-10508 10577-10643 10645-10706 10924-10987 13115 13169 13247 13401 13649 13781 13865-13921 14029 14031-14199 15928-15929
|0bdaad94aa326c17ba2d56366b158c00e057dc5e 10.0.102.49:6379@1122 master - 0 1617950943818 12304 connected 7206 7276 7330 7648 7734 7797-7999 8246-8251 8320-8325 8327-8352 8354 8358-8395 8397-8424 9051-9078 9080-9097 9516-9558 9560-9577 10261-10302 10304-10325 10749-10792 11163-11165 14277 14641 14773
|fa62fd667ead2458da07209f8dac5b3f5ee976e3 10.0.173.184:6379@1122 master - 0 1617950943000 17459 connected 5552 6962-6979 6981-7023 7133-7162 7357-7377 7381-7399 7401-7499 7504-7523 7525-7564 7566-7578 8682-8719 9098-9117 9119-9123 9134-9153 12107-12124 12126-12139 13100-13107 13163-13168 13170-13178 13294-13337 13686 13834-13858 14614 15439-15440 15530 15584
|c98635dd64361d92666729dd18879f0c4383588d 10.0.174.200:6379@1122 master - 0 1617950945761 12296 connected 463-485 678-723 725-738 1206-1208 2545 4802-4852 4854 5331-5391 5767-5774 5776-5832 6050-6104 6608 6647 7169 7301 7565 10713-10748 10833-10835 11036-11070 11084-11085 11276-11278 11280-11290 11325-11326 11444-11456 11458-11484 12696-12706 13108-13114 13116-13141 13143-13162 13567-13578 14351-14352
|2f4e367ca9ad23f3e31b3c1c71196379da909256 10.0.135.178:6379@1122 master - 0 1617950941000 17272 connected 3416-3427 3431-3439 3472-3499 3501-3520 4884 5008 6046-6049 6110-6132 6136-6158 8355-8357 8564-8597 8614-8617 8740-8757 8761-8799 9338-9349 10988-11000 11527 13006-13017 13019-13099 13659-13672 13677-13685 13687-13744 14599-14613 14615-14625 14665 15470-15509 15515-15529 15531-15556
|85fc2c5b4db75d1cce2d51027166c5644e005aa3 10.0.108.50:6379@1122 master - 0 1617950943630 17304 connected 15592-15653 15655-15667 15930-16028 16030-16111 16113-16144 16146-16181 16183-16251 16253-16276 16278-16305 16307-16375 16377-16378 16381-16383
|29dac3179ac29ff19b669a65747eb04e92bf378c 10.0.162.232:6379@1122 master - 0 1617950943614 12305 connected 5689-5736 5833-5890 5892-5944 8019 8151 8194 8264 8326 8396 8458 8512 8644 11418-11443 11666-11747 11752-11761 12471-12524 12526-12571 13199-13246 13248-13293 13354-13400 13402-13412 14738
|25ac5bb6505008716f857fb5d3a38e57d784fb49 10.0.172.151:6379@1122 master - 0 1617950942000 12293 connected 3294-3398 3500 3543-3566 3607 3731 3871 3954 4086 4139 4193 4271 4325 12301-12322 12324-12375 14303-14348 14516-14578 14834-14845 14847-14861 14863-14977 15046-15109 15111-15120
|9c9f3d3b4f0baef43204e75888801aeac3acede2 10.0.128.236:6379@1122 master - 0 1617950942000 12289 connected 229 1531-1577 1579-1709 1711-1786 3041 3079 3100-3103 3105-3108 3178-3235 3237-3243 6617-6646 6648-6688 6913-6961 9154-9167 9273-9288 11362 11494 11964 13673-13676 14786-14829
|735b1e6a7372c6ec095c026c21de8a9e612bb656 10.0.122.200:6379@1122 slave 324d924c9b4b56025f3834ab8a532942c32eeac5 0 1617950942000 12290 connected
|c8ad8f76a125ac9cd3b7fefc5e0491ebae150523 10.0.99.73:6379@1122 slave fa62fd667ead2458da07209f8dac5b3f5ee976e3 0 1617950941000 17459 connected
|a3f638d1e630a22ac648b417faaea6d7b06fdbeb 10.0.124.150:6379@1122 slave c98635dd64361d92666729dd18879f0c4383588d 0 1617950940000 12296 connected
|759a249aab3a9e8444f592f19d270941a678e254 10.0.111.56:6379@1122 slave a867f13af517cd2a141bc289d211d00a78b4c731 0 1617950944068 12300 connected
|85c94ccf91e18c3d28659d1e5e1a032817a838c7 10.0.139.158:6379@1122 master - 0 1617950941000 12287 connected 1092 1277 5968-5979 6159-6304 6373-6398 6400-6417 6689-6702 6732 6856 8839-8954 8956-9050 9118 9172 9336 9578-9614 9684-9743
|a1e17e80527bdbffb03bcc78f9367ab506b97f1c 10.0.172.249:6379@1122 slave a6caab74c3ad3a155586cccf1961e44b4efaf636 0 1617950941000 12297 connected
|324d924c9b4b56025f3834ab8a532942c32eeac5 10.0.170.156:6379@1122 master - 0 1617950945609 12290 connected 0-9 11-63 65-102 104-141 143-195 197-226 228 230-257 259-288 301-334 404-462 1361-1401 3279-3293 5396-5398 11001-11031 11322-11324 11613-11622 11969-11984 11986-12002 12398-12399 14846 15294-15305 15427 15559 15590-15591 15654 16029 16112 16145 16182 16252 16277 16306 16376
|143413eea38127b1fea26e0944ff904810ac3964 10.0.123.93:6379@1122 master - 0 1617950942000 12295 connected 5527 5643 5775 5891 6023 6399 6515 9203 11646-11650 11652-11665 11748-11751 11762-11963 11965-11968 12576-12586 12588-12640 12642-12695 12707-12772 12774-12808 12812-12850 12852-12893
|63c69478f42e86ea13cf423b8dcb34e19eb16e48 10.0.112.75:6379@1122 master - 0 1617950943619 12303 connected 2186-2324 2386 2486-2499 2518 2560-2640 2749-2838 2917 2943-2952 3104 3236 5464-5526 5528-5551 5553-5570 5980-6006 6012-6022 6024-6045 13018 15557-15558 15560-15583
|

|, channel: [id: 0x0fbfb8d5, L:/10.0.155.129:54628 - R:/10.0.119.101:6379], command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@1047293b(incomplete)], command=(CLUSTER NODES), params=[], codec=null]
```

```
2021-04-09T06:49:06.513Z [DEBUG] (redisson-netty-2-7) org.redisson.cluster.ClusterConnectionManager: cluster nodes state got from /10.0.119.101:6379:
|2f31de5fa60d02607e9a3aad0fa69a7bc06b6870 10.0.123.100:6379@1122 master - 0 1617950942000 16981 connected 9744-9831 9903-9963 9965-10052 10202-10203 10799 10923 11086-11141 12292 12406-12415 12417-12454 12456-12470 12572-12575 12894-12942 14200-14276 14278-14302 14862 15110 15510-15514
|0be46429cd7fe0b362043314053530c36bac2d87 10.0.119.155:6379@1122 slave 7b1b3516fd375ed4120b570895a1a6ede8273b82 0 1617950940000 12288 connected
|6bd75f1f698564977d37d3f6ff1cdce2cb84a8de 10.0.173.224:6379@1122 slave 2f4e367ca9ad23f3e31b3c1c71196379da909256 0 1617950945000 17272 connected
|21ddb5c6f2fb0278e7693dfb358c336580e052f4 10.0.120.42:6379@1122 slave 62d75a375183cf25ca18088236678122a70f9852 0 1617950940000 16980 connected
|57e9fb2e40439cf090ad3b46cfa3b2ec1eff9df8 10.0.148.127:6379@1122 slave 0bdaad94aa326c17ba2d56366b158c00e057dc5e 0 1617950942000 12304 connected
|93f1c0d20e095c69df580035eafce5481986182e 10.0.102.120:6379@1122 slave a8c916be600d1f893f53ab143c3373492b836fe2 0 1617950945000 12302 connected
|f7b27973c60b2525ea8c507557bdbebb8e2b003f 10.0.187.124:6379@1122 slave 63c69478f42e86ea13cf423b8dcb34e19eb16e48 0 1617950941000 12303 connected
|0ab5dc80a19aeb63d998e907d1443a4277e70360 10.0.157.161:6379@1122 slave b66f89aa6209f12a33a27f824107af9272c7584c 0 1617950942819 17532 connected
|5ee6b7d87531feb45df96b06bcf6f266cd5cd3a7 10.0.189.119:6379@1122 slave 767ba227808ab00d4bc8bf1ca5a534174bbfd33b 0 1617950941000 17426 connected
|f905fad527694b26bdd7ca27da2eaeed0c6ab063 10.0.173.242:6379@1122 master - 0 1617950941823 16689 connected 2325-2353 4236-4270 4272-4289 4291-4324 4326-4379 4515-4518 4520-4553 4555-4623 4625-4720 4722-4745 4855-4878 5297-5303 5305-5330 5392-5394 5399-5427 5429-5463 5571-5572 6484 11333 11403
|58495ec6af33d6afad82f07679399b2744f0e419 10.0.128.49:6379@1122 slave c52cd11eb53c5b4025ed5b8be92d84fe7f21ab72 0 1617950942000 16838 connected
|767ba227808ab00d4bc8bf1ca5a534174bbfd33b 10.0.144.168:6379@1122 master - 0 1617950943570 17426 connected 1209-1276 1346-1360 2119-2179 2500-2517 2519-2544 2546-2559 3428-3430 3440-3446 3632-3692 4391-4419 4488-4514 4746-4801 5573-5578 6980 7400 7524 9168-9171 9173-9202 9204-9272 11623-11645
|b5b7e5c6b0c2ad1462dfba5cdd4a6b038de636ae 10.0.150.18:6379@1122 slave 011fb99ed1ece52b34ab88c0b393e17304ba76ab 0 1617950943000 12301 connected
|9cb44c9efaa35cd9485fc2180683afbb82c65c99 10.0.122.80:6379@1122 slave 2e5424028508ef4fc8c3bf0bb0ae2d03bf39110e 0 1617950939000 16530 connected
|edbcbdd1435fc42e9d1bcceabc32f8ba0820cf48 10.0.114.189:6379@1122 slave 1a84f052efc69089e00f9652943219f91a505f57 0 1617950943570 17476 connected
|7b1b3516fd375ed4120b570895a1a6ede8273b82 10.0.146.43:6379@1122 master - 0 1617950944766 12288 connected 9832 9861-9902 9964 10080 10212 10512 10644 11142-11162 11269-11275 12075-12079 12081-12101 13579-13633 13862-13864 14349-14350 14412-14515 14978-14985 14987-15037 15121-15137 15139-15291 15306-15312 15381-15405 15467-15469 15585-15589
|ed8b8ddf1c1ae51f30170e83e81908aa2f1ad84e 10.0.175.161:6379@1122 slave 2e3c6da8c12218881d0d0a83153d3488b63fd0be 0 1617950945963 1 connected
|2e3c6da8c12218881d0d0a83153d3488b63fd0be 10.0.131.227:6379@1122 master - 0 1617950945863 1 connected
|1a84f052efc69089e00f9652943219f91a505f57 10.0.154.153:6379@1122 master - 0 1617950939000 17476 connected 3273 4218-4221 4420-4456 4458-4465 4467-4487 6305-6347 9289-9335 9337 9630-9682 10064-10079 10081-10114 10348-10448 10509-10511 10513-10550 10552-10576 10836-10893 11071-11083 11171 11543-11562 12249 14366 15406
|3d4e1f55a2cd3e3ad4f0ad81743cb6b2f2a9d1ad 10.0.167.191:6379@1122 slave 8117e080fde12d7e05d1dfa8e9fc41437a28ea8f 0 1617950939000 17427 connected
|c52cd11eb53c5b4025ed5b8be92d84fe7f21ab72 10.0.119.142:6379@1122 master - 0 1617950939000 16838 connected 2354-2385 2387-2420 2422-2485 3447-3471 3567-3606 3608-3631 3693-3725 3919-3924 3926-3953 3955-3994 3996-4031 4044-4048 4050-4085 4087-4138 4140-4152 4222-4235 4554 5304 5428 11651 12263-12291 12293-12300
|60ac498383babcf301c35cf57dc6273b96b891f8 10.0.152.226:6379@1122 slave f905fad527694b26bdd7ca27da2eaeed0c6ab063 0 1617950944000 16689 connected
|86b94cb0869e6b76d1bed2f2ccec15803f795a28 10.0.164.188:6379@1122 slave 85c94ccf91e18c3d28659d1e5e1a032817a838c7 0 1617950945000 12287 connected
|8d8d79d9440ca398feee40560754d0bc5e77d6d2 10.0.190.2:6379@1122 slave 018956fd15060793eefcf18808a9b056c4a3ebc7 0 1617950944000 17041 connected
|a867f13af517cd2a141bc289d211d00a78b4c731 10.0.134.77:6379@1122 master - 0 1617950941000 12300 connected 10 64 142 196 258 390 491 592 724 786 821 856 918 988 1082 12143-12211 12213-12248 12250-12261 12376-12392 12394-12397 12400-12405 12943-12982 12984-12991 13860-13861 13922-14028 14030 14353-14365 14367-14411 14593-14598 14626-14640 14642-14664 14766-14772 14774-14785 15038-15045 15138 15292-15293 15313-15380 15407-15426 15428-15432 15837-15838
|8117e080fde12d7e05d1dfa8e9fc41437a28ea8f 10.0.105.161:6379@1122 master - 0 1617950941000 17427 connected 103 227 2839-2892 2895-2916 2918-2942 3726-3730 3732-3870 3872-3918 4032-4043 10116-10201 10204-10211 10213-10260 10793-10798 10800-10832 10894-10922 11401 11985 12262
|b28ac4d5c6975152131338d012d8ca88c0cf7564 10.0.133.93:6379@1122 master - 0 1617950945000 17531 connected 335-389 391-403 486-490 492-560 669-677 739-785 787-820 822-855 857-917 919-940 945 1301 2032-2042 3244-3272 3274 11166-11170 11172-11268 11291-11293 12003-12015 12140-12142 14986
|7346e854cda5bc7d92b4cb1b154164dc09ec9128 10.0.107.82:6379@1122 slave 9c9f3d3b4f0baef43204e75888801aeac3acede2 0 1617950943616 12289 connected
|5205b8efd8db4d65606a899040f077a7bc2f80c0 10.0.181.182:6379@1122 master - 0 1617950942000 12294 connected 2421 3925 3995 4049 4290 4380-4390 4457 4519 4721 4853 4879-4883 4885-5007 5009-5296 5395 5737-5766 10115 11485-11493 11495-11526 11528-11542 11603-11612
|011fb99ed1ece52b34ab88c0b393e17304ba76ab 10.0.99.114:6379@1122 master - 0 1617950945562 12301 connected 1177 1330 1425 1462 1578 1710 1826 1954-2031 2641-2668 2670-2748 3399-3415 3522-3542 8437-8440 9386-9468 12809-12811 13179-13198 13745-13780 13782-13833 14579-14592 14830-14833 15433-15438 15844-15927
|59a8c492a1d1651aac35af206f2c9b6ebc167ee5 10.0.113.17:6379@1122 slave d286d664dfef8c7aa6eee98bfe56a683da37f4b1 0 1617950941000 14739 connected
|018956fd15060793eefcf18808a9b056c4a3ebc7 10.0.137.45:6379@1122 master - 0 1617950941000 17041 connected 941-944 946-987 989-1081 1083-1091 1278-1300 1302-1319 1329 1331-1339 1787-1819 2669 2953-3040 3042-3078 3080-3099 3521 4466 7378-7380 7586-7647 8252-8263 8265-8304 9833-9860
|e8f1273794167a0abf021e26f7f71fc4fe23b73d 10.0.161.72:6379@1122 slave bb69a1c203f9ee5fa6c14d7bdd30493390accc20 0 1617950941000 17530 connected
|b584192c067b3627b2a00afdb6bdf36011402ab6 10.0.169.76:6379@1122 slave 2f31de5fa60d02607e9a3aad0fa69a7bc06b6870 0 1617950941000 16981 connected
|57bab188484251b5fabad10c4d7248637f3781cf 10.0.119.185:6379@1122 slave 25ac5bb6505008716f857fb5d3a38e57d784fb49 0 1617950943073 12293 connected
|2c50405871afeb24c8833b2638b6c80a68b2e614 10.0.99.197:6379@1122 slave 5205b8efd8db4d65606a899040f077a7bc2f80c0 0 1617950942000 12294 connected
|bb37e9019ac864d34dfbb25c72a79216fbc0ff7e 10.0.113.40:6379@1122 slave b28ac4d5c6975152131338d012d8ca88c0cf7564 0 1617950943000 17531 connected
|f8f0f3a534f363e195c369b94ba4bb3669d2f512 10.0.149.137:6379@1122 slave 29dac3179ac29ff19b669a65747eb04e92bf378c 0 1617950942000 12305 connected
|83a9c50f52bb45c10593677d675565336b68e5e0 10.0.156.150:6379@1122 slave 85fc2c5b4db75d1cce2d51027166c5644e005aa3 0 1617950942619 17304 connected
|b66f89aa6209f12a33a27f824107af9272c7584c 10.0.119.101:6379@1122 myself,master - 0 1617950941000 17532 connected 561-591 593-668 1093-1176 1178-1205 1340-1345 1402-1424 1426-1461 1463-1530 1820-1825 1827-1953 3149 4166 12992-13005 13338-13353 13566 13859 15724 15778
|a6caab74c3ad3a155586cccf1961e44b4efaf636 10.0.110.172:6379@1122 master - 0 1617950942618 12297 connected 1320-1328 2043-2118 2180-2185 2893-2894 3109-3148 3150-3177 4153-4165 4167-4192 4194-4217 10551 11563-11602 12016-12074 12080 12102-12106 12125 12212 12323 12393 12455 12525 12587 12641 12773 12851 12983 15441-15466 15668-15723 15725-15777 15779-15836 15839-15843 16379-16380
|bb69a1c203f9ee5fa6c14d7bdd30493390accc20 10.0.114.240:6379@1122 master - 0 1617950942000 17530 connected 5945-5967 6105-6109 6348-6372 6418-6483 6485-6514 6516-6607 6609-6616 7163 7500-7503 7579-7585 8052 8122 8176 8229 8305-8319 8557-8563 8598-8613 8732-8739 8803 9350-9385 9469-9515 9615-9629 10053-10063 10707-10712 11327-11332 11334-11361 11363-11400 11402 11404-11417
|d286d664dfef8c7aa6eee98bfe56a683da37f4b1 10.0.179.226:6379@1122 master - 0 1617950943121 14739 connected 289-300 3275-3278 5655-5688 6007-6011 6133-6135 7024-7056 8000-8018 8020-8051 8053-8121 8123-8150 8152-8175 8177-8193 8195-8228 8230-8245 8425-8436 8441-8457 8459-8511 8513-8556 8618-8643 8645-8681 8720-8725 11279 11457 13142
|0bdaad94aa326c17ba2d56366b158c00e057dc5e 10.0.102.49:6379@1122 master - 0 1617950943818 12304 connected 7206 7276 7330 7648 7734 7797-7999 8246-8251 8320-8325 8327-8352 8354 8358-8395 8397-8424 9051-9078 9080-9097 9516-9558 9560-9577 10261-10302 10304-10325 10749-10792 11163-11165 14277 14641 14773
|fa62fd667ead2458da07209f8dac5b3f5ee976e3 10.0.173.184:6379@1122 master - 0 1617950943000 17459 connected 5552 6962-6979 6981-7023 7133-7162 7357-7377 7381-7399 7401-7499 7504-7523 7525-7564 7566-7578 8682-8719 9098-9117 9119-9123 9134-9153 12107-12124 12126-12139 13100-13107 13163-13168 13170-13178 13294-13337 13686 13834-13858 14614 15439-15440 15530 15584
|c98635dd64361d92666729dd18879f0c4383588d 10.0.174.200:6379@1122 master - 0 1617950945761 12296 connected 463-485 678-723 725-738 1206-1208 2545 4802-4852 4854 5331-5391 5767-5774 5776-5832 6050-6104 6608 6647 7169 7301 7565 10713-10748 10833-10835 11036-11070 11084-11085 11276-11278 11280-11290 11325-11326 11444-11456 11458-11484 12696-12706 13108-13114 13116-13141 13143-13162 13567-13578 14351-14352
|2f4e367ca9ad23f3e31b3c1c71196379da909256 10.0.135.178:6379@1122 master - 0 1617950941000 17272 connected 3416-3427 3431-3439 3472-3499 3501-3520 4884 5008 6046-6049 6110-6132 6136-6158 8355-8357 8564-8597 8614-8617 8740-8757 8761-8799 9338-9349 10988-11000 11527 13006-13017 13019-13099 13659-13672 13677-13685 13687-13744 14599-14613 14615-14625 14665 15470-15509 15515-15529 15531-15556
|85fc2c5b4db75d1cce2d51027166c5644e005aa3 10.0.108.50:6379@1122 master - 0 1617950943630 17304 connected 15592-15653 15655-15667 15930-16028 16030-16111 16113-16144 16146-16181 16183-16251 16253-16276 16278-16305 16307-16375 16377-16378 16381-16383
|29dac3179ac29ff19b669a65747eb04e92bf378c 10.0.162.232:6379@1122 master - 0 1617950943614 12305 connected 5689-5736 5833-5890 5892-5944 8019 8151 8194 8264 8326 8396 8458 8512 8644 11418-11443 11666-11747 11752-11761 12471-12524 12526-12571 13199-13246 13248-13293 13354-13400 13402-13412 14738
|25ac5bb6505008716f857fb5d3a38e57d784fb49 10.0.172.151:6379@1122 master - 0 1617950942000 12293 connected 3294-3398 3500 3543-3566 3607 3731 3871 3954 4086 4139 4193 4271 4325 12301-12322 12324-12375 14303-14348 14516-14578 14834-14845 14847-14861 14863-14977 15046-15109 15111-15120
|9c9f3d3b4f0baef43204e75888801aeac3acede2 10.0.128.236:6379@1122 master - 0 1617950942000 12289 connected 229 1531-1577 1579-1709 1711-1786 3041 3079 3100-3103 3105-3108 3178-3235 3237-3243 6617-6646 6648-6688 6913-6961 9154-9167 9273-9288 11362 11494 11964 13673-13676 14786-14829
|735b1e6a7372c6ec095c026c21de8a9e612bb656 10.0.122.200:6379@1122 slave 324d924c9b4b56025f3834ab8a532942c32eeac5 0 1617950942000 12290 connected
|c8ad8f76a125ac9cd3b7fefc5e0491ebae150523 10.0.99.73:6379@1122 slave fa62fd667ead2458da07209f8dac5b3f5ee976e3 0 1617950941000 17459 connected
|a3f638d1e630a22ac648b417faaea6d7b06fdbeb 10.0.124.150:6379@1122 slave c98635dd64361d92666729dd18879f0c4383588d 0 1617950940000 12296 connected
|759a249aab3a9e8444f592f19d270941a678e254 10.0.111.56:6379@1122 slave a867f13af517cd2a141bc289d211d00a78b4c731 0 1617950944068 12300 connected
|85c94ccf91e18c3d28659d1e5e1a032817a838c7 10.0.139.158:6379@1122 master - 0 1617950941000 12287 connected 1092 1277 5968-5979 6159-6304 6373-6398 6400-6417 6689-6702 6732 6856 8839-8954 8956-9050 9118 9172 9336 9578-9614 9684-9743
|a1e17e80527bdbffb03bcc78f9367ab506b97f1c 10.0.172.249:6379@1122 slave a6caab74c3ad3a155586cccf1961e44b4efaf636 0 1617950941000 12297 connected
|324d924c9b4b56025f3834ab8a532942c32eeac5 10.0.170.156:6379@1122 master - 0 1617950945609 12290 connected 0-9 11-63 65-102 104-141 143-195 197-226 228 230-257 259-288 301-334 404-462 1361-1401 3279-3293 5396-5398 11001-11031 11322-11324 11613-11622 11969-11984 11986-12002 12398-12399 14846 15294-15305 15427 15559 15590-15591 15654 16029 16112 16145 16182 16252 16277 16306 16376
|143413eea38127b1fea26e0944ff904810ac3964 10.0.123.93:6379@1122 master - 0 1617950942000 12295 connected 5527 5643 5775 5891 6023 6399 6515 9203 11646-11650 11652-11665 11748-11751 11762-11963 11965-11968 12576-12586 12588-12640 12642-12695 12707-12772 12774-12808 12812-12850 12852-12893
|63c69478f42e86ea13cf423b8dcb34e19eb16e48 10.0.112.75:6379@1122 master - 0 1617950943619 12303 connected 2186-2324 2386 2486-2499 2518 2560-2640 2749-2838 2917 2943-2952 3104 3236 5464-5526 5528-5551 5553-5570 5980-6006 6012-6022 6024-6045 13018 15557-15558 15560-15583
```

It seems that the client stopped sending CLUSTER NODES commands after new the shard was added.

**Comment by mrniko** [comment]
may I have complete redisson log? 

I don't see log entry where Redisson added new slots.

**Comment by milicicm** [comment]
Can you specify what kind of information would be useful, so I know what to look for? There are millions of log entries with TRACE level logging enabled and I don't see how can I share the entire Redisson log.

**Comment by milicicm** [comment]
We are also seeing 100% errors in reads after scaling down / removing shards from the cluster. I see a few different exceptions.

First example:

```
2021-04-13T07:52:09.180Z [ERROR] 00e89ddc-973e-41a5-8eca-c32204548458 (Bobcat-20) <service_code> org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=3034, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@278765798 [redisClient=[addr=redis://10.0.137.45:6379], channel=[id: 0x6b3448bb, L:/10.0.155.129:50296 ! R:ip-10-0-137-45.ec2.internal/10.0.137.45:6379], currentCommand=null], command: (HGET), params: <key>, PooledUnsafeDirectByteBuf(ridx: 0, widx: 21, cap: 256)] after 2 retry attempts
<stack_trace>
```

Second example:
```
2021-04-13T07:52:10.480Z [ERROR] 03eae181-ee7d-4417-9426-4ed8dd726a64 (Bobcat-20) <service_code> org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: ip-10-0-155-156.ec2.internal/10.0.155.156:6379 Disconnected hosts: [ip-10-0-155-156.ec2.internal/10.0.155.156:6379] Hosts disconnected due to errors during `failedSlaveCheckInterval`: [ip-10-0-102-120.ec2.internal/10.0.102.120:6379]
<stack_trace>
```

**Comment by mrniko** [comment]
@milicicm 

Do you see any errors in logs?

**Comment by milicicm** [comment]
I've updated our service to use Redisson 3.15.3 and got the same results:

* Send constant HGET traffic to cluster
* Scale up the cluster from 16 to 32 shards
* Clients on all service hosts talking to Redis cluster can't send commands to newly added shards
* All clients stopped sending CLUSTER NODES to discover new shards

The errors and log entries are the same as the ones that I've already posted. Our service is running on ECS and errors are equally distributed across all ECS tasks in our service so it's not related to a single service host. 

I do see some additional errors reported by ClusterConnectionManager, right after the new shards are added to the cluster and before we start seeing the read errors:

```
2021-04-14T09:09:32.983Z [WARN]  (redisson-netty-2-12) io.netty.util.concurrent.DefaultPromise: An exception was thrown by org.redisson.misc.RedissonPromise$$Lambda$361/0x0000000800593c40.operationComplete() java.lang.NullPointerException
|	at org.redisson.cluster.ClusterConnectionManager.checkMasterNodesChange(ClusterConnectionManager.java:560)
|	at org.redisson.cluster.ClusterConnectionManager.lambda$updateClusterState$10(ClusterConnectionManager.java:466)
|	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187)
|	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
|	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
|	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
|	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
|	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
|	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
|	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
|	at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82)
|	at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:435)
|	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:429)
|	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:360)
|	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:177)
|	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:116)
|	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:101)
|	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
|	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
|	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
|	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
|	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
|	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
|	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
|	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
|	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
|	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
|	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
|	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
|	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
|	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
|	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
|	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
|	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
|	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
|	at java.base/java.lang.Thread.run(Thread.java:829)
```

There's one instance of this error log on each ECS host. Could this indicate that the ClusterConnectionManager died at this point? Is there something we can do here?

**Comment by mrniko** [comment]
> I do see some additional errors reported by ClusterConnectionManager, right after the new shards are added to the cluster and before we start seeing the read errors:

This is the cause of issue.

**Comment by avcad** [comment]
@milicicm  I wonder why AWS is reporting masters without IPs.  " :6379". isn't that a bug on their side?

```
|011fb99ed1ece52b34ab88c0b393e17304ba76ab 10.0.99.114:6379@1122 master - 0 1617950945562 12301 connected 1177 1330 1425 1462 1578 1710 1826 1954-2031 2641-2668 2670-2748 3399-3415 3522-3542 8437-8440 9386-9468 12809-12811 13179-13198 13745-13780 13782-13833 14579-14592 14830-14833 15433-15438 15844-15927
|2e5424028508ef4fc8c3bf0bb0ae2d03bf39110e :6379@1122 master - 0 1617950943570 16530 connected 6703-6731 6733-6855 6857-6912 8800-8802 8804-8838 8955 9683 12416 13413-13565 13634-13648 13650-13658 14666-14737 14739-14765
|59a8c492a1d1651aac35af206f2c9b6ebc167ee5 10.0.113.17:6379@1122 slave d286d664dfef8c7aa6eee98bfe56a683da37f4b1 0 1617950941000 14739 connected
```

**Comment by mrniko** [comment]
Yes, that's an issue. Can you report them?

**Comment by mrniko** [comment]
address can't be parsed in this case this why you get NPE.

**Comment by mrniko** [comment]
I switched to `Objects.equals()` method.

**Comment by mrniko** [comment]
Fixed

**Comment by mrniko** [comment]
I have checked nodes with wrong addresses are skipped

**Comment by mrniko** [comment]
@milicicm 

I attached fixed version so you can try it.
[redisson-3.15.4-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/6316613/redisson-3.15.4-SNAPSHOT.jar.zip)

**Comment by milicicm** [comment]
Thank you for the quick fix. I'll try it out and update the ticket if we encounter any similar issues.

**Comment by satyaprakash1729** [comment]
@mrniko 
We're on `redisson-3.15.6`. We encountered similar issue (manifestation & logs described here match) during scale out activity of Elasticache. Could this be a regression?
@milicicm Did you see the issue fixed with 3.15.4?

**Comment by milicicm** [comment]
We've also tried `3.15.6` version but the problem is still present. The fix posted earlier in this issue did not work for us. We are now encountering the errors posted in https://github.com/redisson/redisson/pull/3676

**Comment by mrniko** [comment]
@milicicm 

Do you see NPE like `java.lang.NullPointerException | at org.redisson.misc.RedisURI.compare(RedisURI.java:91)` ?

**Comment by milicicm** [comment]
Yes.

**Comment by mrniko** [comment]
Fixed.

**Comment by satyaprakash1729** [comment]
@mrniko We want to try out this fix and share feedback. Is there a SNAPSHOT library that we can use?

**Comment by mrniko** [comment]
@satyaprakash1729 

I attached two variants no-dependencies and all-dependencies.

[redisson-3.16.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/7020001/redisson-3.16.2-SNAPSHOT.jar.zip)
[redisson-all-3.16.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/7020005/redisson-all-3.16.2-SNAPSHOT.jar.zip)
