### ISSUE TITLE
Is there any instruction to build the project, thanks

### ISSUE THREAD

**Issue by stanstanwang** [redisson/redisson#3690]
#3652 

The fix hasn't been released yet, but we want to use it because we in the production environment.

I downloaded the source code today, switched to the corresponding tag(3.15.1) and tried to build it with the this fixed change, but the Maven dependency couldn't be found.

Is there any instruction to build the project, thanks

![image](https://user-images.githubusercontent.com/19669879/123530308-4d935980-d72b-11eb-83bb-c98005da9bb0.png)

**Comment by mom1705** [comment]
I tried 3.16 but same exception was thrown.

**Comment by stanstanwang** [comment]
https://github.com/redisson/redisson/issues/3652

i run by this example, it is fixed.

as for whether there will be other problems, our production environment is still under observation.

and what's your error stack trace, this may also help with us, thanks.

**Comment by stanstanwang** [comment]
> I tried 3.16 but same exception was thrown.

#3652

i run by this example, it is fixed.

as for whether there will be other problems, our production environment is still under observation.

and what's your error stack trace, this may also help with us, thanks.

**Comment by mrniko** [comment]
You need to use JDK 11 to build the project.

**Comment by mom1705** [comment]
I am still getting below with 3.16.0 build

Worker task stopped:org.snmp4j.transport.DefaultUdpTransportMapping$ListenThread
org.redisson.client.RedisException: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@7647104d(incomplete)
org.redisson.client.RedisException: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@7647104d(incomplete)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:115)
        at org.redisson.RedissonObject.get(RedissonObject.java:82)
        at org.redisson.RedissonList.add(RedissonList.java:115)
        
.............
        at org.snmp4j.Snmp.processPdu(Snmp.java:1300)
        at org.snmp4j.MessageDispatcherImpl.fireProcessPdu(MessageDispatcherImpl.java:694)
        at org.snmp4j.MessageDispatcherImpl.dispatchMessage(MessageDispatcherImpl.java:310)
        at org.snmp4j.MessageDispatcherImpl.processMessage(MessageDispatcherImpl.java:390)
        at org.snmp4j.MessageDispatcherImpl.processMessage(MessageDispatcherImpl.java:350)
        at org.snmp4j.transport.AbstractTransportMapping.fireProcessMessage(AbstractTransportMapping.java:76)
        at org.snmp4j.transport.DefaultUdpTransportMapping$ListenThread.run(DefaultUdpTransportMapping.java:430)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@7647104d(incomplete)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:212)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:112)
        ... 13 more
#[250721 06:30:15,708 | snmpmgr-depl-58fcccf7cd-8tfnm | INFO  |

**Comment by mrniko** [comment]
java.lang.InterruptedException means that thread was interrupted

**Comment by mom1705** [comment]
how to fix that ( sorry new to java and spring?

**Comment by mom1705** [comment]
This is after removing mutex

org.redisson.client.RedisException: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@54dddb23(incomplete)
org.redisson.client.RedisException: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@54dddb23(incomplete)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:115)
        at org.redisson.RedissonObject.get(RedissonObject.java:82)
        at org.redisson.RedissonList.add(RedissonList.java:115)
..............
Worker task stopped:org.snmp4j.transport.DefaultUdpTransportMapping$ListenThread
        at org.snmp4j.Snmp.processPdu(Snmp.java:1300)
        at org.snmp4j.MessageDispatcherImpl.fireProcessPdu(MessageDispatcherImpl.java:694)
        at org.snmp4j.MessageDispatcherImpl.dispatchMessage(MessageDispatcherImpl.java:310)
        at org.snmp4j.MessageDispatcherImpl.processMessage(MessageDispatcherImpl.java:390)
        at org.snmp4j.MessageDispatcherImpl.processMessage(MessageDispatcherImpl.java:350)
        at org.snmp4j.transport.AbstractTransportMapping.fireProcessMessage(AbstractTransportMapping.java:76)
        at org.snmp4j.transport.DefaultUdpTransportMapping$ListenThread.run(DefaultUdpTransportMapping.java:430)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@54dddb23(incomplete)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:212)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:112)
        ... 13 more

**Comment by mom1705** [comment]
So last stack trace which pasted was when I was not using any lock, now with RLock I get below

org.redisson.client.RedisException: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@6bf143b2(incomplete)
org.redisson.client.RedisException: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@6bf143b2(incomplete)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:115)
        at org.redisson.RedissonObject.get(RedissonObject.java:82)
        at org.redisson.RedissonLock.tryAcquire(RedissonLock.java:143)
        at org.redisson.RedissonLock.lock(RedissonLock.java:97)
        at org.redisson.RedissonLock.lock(RedissonLock.java:69)

....
        at org.snmp4j.Snmp.processPdu(Snmp.java:1300)
        at org.snmp4j.MessageDispatcherImpl.fireProcessPdu(MessageDispatcherImpl.java:694)
        at org.snmp4j.MessageDispatcherImpl.dispatchMessage(MessageDispatcherImpl.java:310)
        at org.snmp4j.MessageDispatcherImpl.processMessage(MessageDispatcherImpl.java:390)
        at org.snmp4j.MessageDispatcherImpl.processMessage(MessageDispatcherImpl.java:350)
        at org.snmp4j.transport.AbstractTransportMapping.fireProcessMessage(AbstractTransportMapping.java:76)
        at org.snmp4j.transport.DefaultUdpTransportMapping$ListenThread.run(DefaultUdpTransportMapping.java:430)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@6bf143b2(incomplete)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:212)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:112)
        ... 15 more

What Am I doing wrong ?

**Comment by mrniko** [comment]
You need to get the cause why thread invoking Redisson method got interrupted.

**Comment by mom1705** [comment]
So If RList is used by multiple thread, Do I need to use RLock ? Are redis datastructure thread safe ?

**Comment by mom1705** [comment]
I am traversing and deleting RList like normal List, will that cause any issue

ie.
            for (Iterator<String> iterator = rList.iterator();  iterator.hasNext(); ) {
               //do something 
                iterator.remove();
            }

**Comment by mrniko** [comment]
> Are redis datastructure thread safe ?

They are fully thread-safe as well as Redisson objects.

**Comment by mom1705** [comment]
So u meant differnet threads can do add/remove/traverse without lock/unlock ?

**Comment by mrniko** [comment]
yes

**Comment by mom1705** [comment]
thanks a lot.

**Comment by mom1705** [comment]
How can I figure out what is causing below? It happens after successful first add and later traversing and removing  element  also on 2nd add . Looks like after traversing and removing all elements from RList something happened wrong(pasted that code above) and then next add threw error.  Can you pls help me?

org.redisson.client.RedisException: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@61305b61(incomplete)
org.redisson.client.RedisException: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@61305b61(incomplete)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:115)
        at org.redisson.RedissonObject.get(RedissonObject.java:82)
        at org.redisson.RedissonList.add(RedissonList.java:115)
        at com.nokia.fm.SnmpToClogAlarm.clearHBMissingAlarm(SnmpToClogAlarm.java:209)
        at com.nokia.fm.HeartBeat.clearHBMissingAlarm(HeartBeat.java:130)
        at com.nokia.fm.HeartBeat$1.onResponse(HeartBeat.java:201)
        at org.snmp4j.Snmp.processPdu(Snmp.java:1300)
        at org.snmp4j.MessageDispatcherImpl.fireProcessPdu(MessageDispatcherImpl.java:694)
        at org.snmp4j.MessageDispatcherImpl.dispatchMessage(MessageDispatcherImpl.java:310)
        at org.snmp4j.MessageDispatcherImpl.processMessage(MessageDispatcherImpl.java:390)
        at org.snmp4j.MessageDispatcherImpl.processMessage(MessageDispatcherImpl.java:350)
        at org.snmp4j.transport.AbstractTransportMapping.fireProcessMessage(AbstractTransportMapping.java:76)
        at org.snmp4j.transport.DefaultUdpTransportMapping$ListenThread.run(DefaultUdpTransportMapping.java:430)
        at java.lang.Thread.run(Thread.java:748)
Worker task stopped:org.snmp4j.transport.DefaultUdpTransportMapping$ListenThread
Caused by: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@61305b61(incomplete)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:212)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:112)
        ... 13 more
#[270721 06:56:21,265 | snmpmgr-depl-58fcccf7cd-rf8hs | INFO  | scheduling-1 | AlarmSender | sending alarm from q to calm calarm : {"alarm":{"event-type":"co

**Comment by mrniko** [comment]
Unable to reproduce. Here is my code:

```java
        List<String> list = redisson.getList("list");
        list.add("1");
        list.add("4");
        list.add("2");
        list.add("5");
        list.add("3");

        for (Iterator<String> iterator = list.iterator(); iterator.hasNext();) {
            String value = iterator.next();
            iterator.remove();
        }

        assertThat(list).isEmpty();
```

**Comment by mom1705** [comment]
Can u pls try .add after assertThat also thru other thread?

**Comment by mrniko** [comment]
It works:

```java
        List<String> list = redisson.getList("list");
        list.add("1");
        list.add("4");
        list.add("2");
        list.add("5");
        list.add("3");

        Thread t = new Thread(() -> {
            while (true) {
                list.add("3");
            }
        });
        t.start();

        for (Iterator<String> iterator = list.iterator(); iterator.hasNext();) {
            String value = iterator.next();
            iterator.remove();
        }

        assertThat(list).isEmpty();
```

**Comment by mom1705** [comment]
I meant below

        List<String> list = redisson.getList("list");
        list.add("1");
        list.add("4");
        list.add("2");
        list.add("5");
        list.add("3");

        for (Iterator<String> iterator = list.iterator(); iterator.hasNext();) {
            String value = iterator.next();
            iterator.remove();
        }
 
        assertThat(list).isEmpty();

        Thread t = new Thread(() -> {
            while (true) {
                list.add("3");
            }
        });
        t.start();


as I continuously add elements ( new threads) and one more thread keeps on sending those items and removing  from list.

**Comment by mrniko** [comment]
it works as well.

**Comment by mom1705** [comment]
java version has something to do with it ?

**Comment by mom1705** [comment]
thanks a lot for trying everything, really appreciate.

**Comment by mom1705** [comment]
So it is not just add ( on RList) which leads to this exception but even size() is leading to this. Is it because list is empty and perhaps deleted ( when empty , not doing anything in code related to deleting list )?
org.redisson.client.RedisException: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@64e4ab01(incomplete)
org.redisson.client.RedisException: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@64e4ab01(incomplete)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:115)
        at org.redisson.RedissonObject.get(RedissonObject.java:82)
        at org.redisson.RedissonList.size(RedissonList.java:69)
..........
        at org.snmp4j.Snmp.processPdu(Snmp.java:1300)
        at org.snmp4j.MessageDispatcherImpl.fireProcessPdu(MessageDispatcherImpl.java:694)
        at org.snmp4j.MessageDispatcherImpl.dispatchMessage(MessageDispatcherImpl.java:310)
        at org.snmp4j.MessageDispatcherImpl.processMessage(MessageDispatcherImpl.java:390)
        at org.snmp4j.MessageDispatcherImpl.processMessage(MessageDispatcherImpl.java:350)
        at org.snmp4j.transport.AbstractTransportMapping.fireProcessMessage(AbstractTransportMapping.java:76)
        at org.snmp4j.transport.DefaultUdpTransportMapping$ListenThread.run(DefaultUdpTransportMapping.java:430)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@64e4ab01(incomplete)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:212)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:112)
        ... 13 more
