### ISSUE TITLE
an RedisNodeNotFoundException was encountered when using redisson

### ISSUE THREAD

**Issue by repeatthink123yuchao** [redisson/redisson#5333]
#server version
redis server : 5.0.14
#redisson client version
3.13.6
#describ
    private volatile Map<String, RedissonClient> redissonClientMap = null;

before our app link redis sentinel nodes,now our app will change link redis cluster nodes,implementation method is our app has a map to store two RedissonClient
one redisson client link redis sentinel nodes,another redisson client link redis cluster nodes, the map switcher is a key to routing a RedissonClient
but when we change key route to redis cluster nodes,After after a few minutes,app sometimes will print log 

	Node for slot: 1712 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command. Increase value of retryAttempts and/or retryInterval settings.org.redisson.client.RedisNodeNotFoundException: Node for slot: 1712 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command. Increase value of retryAttempts and/or retryInterval settings.
	at org.redisson.connection.MasterSlaveConnectionManager.createNodeNotFoundFuture(MasterSlaveConnectionManager.java:579)
	at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:563)
	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:644)
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:116)
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:244)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:668)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:743)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:471)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

guided by logs,when we invoke CLUSTER NODES command, the redis cluster nodes status is health

tip:sometimes the app will print the following warning level logs
[2023-09-12 22:47:33.978][INFO][698][redisson-netty-5-14] traceLogId:[null] dstTraceId:[] TxId:[] SpanId:[] call [org.redisson.cluster.ClusterConnectionManager][checkSlotsMigration] 294 slots removed from

how to solve this RedisNodeNotFoundException,because it affects normal business logic,thanks help me

**Comment by mrniko** [comment]
incorrect slots added,slots removed messages in Redis Cluster mode fixed in 3.23.4 version. Can you try it?

**Comment by repeatthink123yuchao** [comment]
> incorrect slots added,slots removed messages in Redis Cluster mode fixed in 3.23.4 version. Can you try it?

we increased the redisson version number from 3.11.1 to 3.13.6, but the problem(removed/added/RedisNodeNotFoundException) still exists,
and the problem(removed/added) does not affect normal business logic,but the RedisNodeNotFoundException is fatal,the RedisNodeNotFoundException affects normal business logic and intolerable
can you help me see how to solve this RedisNodeNotFoundException?

**Comment by mrniko** [comment]
Sorry, I suggest to use 3.23.4 version not 3.13.6

**Comment by repeatthink123yuchao** [comment]
> RedisNodeNotFoundException may arise if node was removed due to rare issue in topology handling. It was fixed in 3.23.4.

I'll try it first and get back to you with the test results later.

**Comment by repeatthink123yuchao** [comment]
> RedisNodeNotFoundException may arise if node was removed due to rare issue in topology handling. It was fixed in 3.23.4.

Thank you very much, this problem is solved
