### ISSUE TITLE
Expiry events not received with redis 7.0.7 cluster mode enabled

### ISSUE THREAD

**Issue by ddinde** [redisson/redisson#5447]
We had AWS Elasticache redis cluster with engine 6.2.6 and cluster mode enabled and expiry events were working fine.
Recently we upgraded that cluster to 7.0.7. Cluster mode is enabled.
After that we stopped receiving expiry events on our listener.
We tested with different values 'A' 'AKE' , "KExe' , 'sKExe' for 'notify-keyspace-events'  property , but nothing helped.

I created another 7.0.7 cluster with cluster mode DISABLED then it works fine, i do receive expiry events on my listener class there.

We contacted AWS support and they showed us with help of redis-cli that events are published on master node.
So not sure if redisson fails to connect with master node, to receive events when redis engine is 7.0.7.

We are using redisson '3.23.3' version, we tried with latest version '3.24.3' also.

**Expected behavior** expiry events should be received if redis engine is 7.0.7 with cluster mode enabled

**Actual behavior** expiry events not received

**Steps to reproduce or test case**  
Upgrade redis engine to 7.0.7 with cluster mode enabled
set 'notify-keyspace-events' to AKE or KExe

**Redis version** 
AWS Elastcache redis 7.0.7
1 shard with 1 replica

**Redisson version**  3.23.3 ( tried with '3.24.3' also)

**Redisson configuration** connecting to aws elasticache cluster endpoint
connectionTimeout 10000
subscriptionsPerConnection 10
subscriptionConnectionPoolSize 100
retryInterval 4000
retryAttempts 15
readMode MASTER
checkSlotsCoverage  false
with password

**Comment by ddinde** [comment]
Came across this in release notes:
"Feature - RMapCache and RLocalCachedMap should use sharded pubsub in Redis Cluster 7.0+"

Looks like we have to add listener differently for expiry events to use sharded pubsub, but couldn't find any redisson example.
Can someone please tell me how to made that change ( switch to sharded pubsub) ?
Currently we just do this 
```

RMapCache<String, String> mapCache = redissonClient.getMapCache(cacheName)
mapCache.addListener(new ExpiryEventListnerImpl());
```

**Comment by mrniko** [comment]
Unable to reproduce it with Redis Cluster 7.0.

Below is the test code.

```java
        testInCluster(r -> {
            RMapCache<String, String> map = redisson.getMapCache("simple");
            map.put("1", "2", 1, TimeUnit.SECONDS);
            map.addListener(new EntryExpiredListener() {
                @Override
                public void onExpired(EntryEvent event) {
                    System.out.println("here " + event);
                }
            });
        });

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by ddinde** [comment]
Thanks @mrniko for fixing this urgently.
When 3.25.0 ( to which this bug is tagged) release is planned  ? 
Downgrading cluster is not option for us and creating new cluster will affect too many use cases, so it's critical issue for us.

**Comment by OS-ramamurtisubramanian** [comment]
we are still facing this issue with 3.25.2. Can you please help?

**Comment by mrniko** [comment]
Can you provide the sample code to reproduce it? Which listeners do you use?

**Comment by OS-ramamurtisubramanian** [comment]
We are initializing the redisson client with useClusterServers and a custom nameMapper and we get the map cache with a name and custom codec.

We add the expiry listener like

 mapCache.addListener((EntryExpiredListener<K, V>) event -> {});

**Comment by mrniko** [comment]
@OS-ramamurtisubramanian 

Fixed.
