### ISSUE TITLE
Unable to send PING command over channel

### ISSUE THREAD

**Issue by hades-ruan** [redisson/redisson#5500]
<img width="1426" alt="image" src="https://github.com/redisson/redisson/assets/8568988/49d67071-aeb3-474e-8b85-bbd0f60e5082">
first
**Steps to reproduce or test case**
The first step is to set a null
The second step is to set a non-null

test code:
 @SneakyThrows
    @Test
    public void testPush() {
 
        ExecutorService executorService = Executors.newFixedThreadPool(100);
        CountDownLatch countDownLatch = new CountDownLatch(100);

        for (int i = 0; i < 100; i++) {
            int finalI = i;
            executorService.execute(()->{
                for (int j = 0; j < 1000; j++) {
                    long start = System.currentTimeMillis();
                    stringRedisTemplate.opsForValue().set(j+"",null);
                    stringRedisTemplate.opsForValue().set(j+"11","null");
                   log.info(finalI +"===:"+(System.currentTimeMillis()-start));
                    try {
                        TimeUnit.SECONDS.sleep(1);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
                countDownLatch.countDown();
            });
        }
        countDownLatch.await();
        log.info("===========ok");
    }
**Redis version**
6.0.1
**Redisson version**
3.17.7
**Redisson configuration**
spring:
  redis:
   redisson: 
      config: |
        clusterServersConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          failedSlaveReconnectionInterval: 3000
          failedSlaveCheckInterval: 60000
          password: "jr4qgvcGparY"
          subscriptionsPerConnection: 5
          clientName: null
          loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          slaveConnectionMinimumIdleSize: 24
          slaveConnectionPoolSize: 64
          masterConnectionMinimumIdleSize: 24
          masterConnectionPoolSize: 200
          readMode: "MASTER"
          subscriptionMode: "MASTER"
          nodeAddresses:
          - "redis://192.168.2.232:6302"
          - "redis://192.168.2.233:6302"
          - "redis://192.168.2.234:6302"
          - "redis://192.168.2.242:6302"
          - "redis://192.168.2.243:6302"
          - "redis://192.168.2.244:6302"
          scanInterval: 1000
          pingConnectionInterval: 30000
          keepAlive: true
          tcpNoDelay: true
        threads: 64
        nettyThreads: 64
        transportMode: "NIO"

**Comment by mrniko** [comment]
Thanks for the provided test. Unfortunately, I'm unable to reproduce the issue.

Can you share the full stacktrace?

**Comment by hades-ruan** [comment]
2023-12-18 13:44:28.827 [  ]-[redisson-netty-2-53] WARN  i.n.c.AbstractChannelHandlerContext:69 - Failed to mark a promise as failure because it has failed already: DefaultChannelPromise@7e02f483(failure: io.netty.handler.codec.EncoderException: java.lang.NullPointerException), unnotified cause: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at org.redisson.client.handler.CommandEncoder.write(CommandEncoder.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
	at org.redisson.client.handler.CommandBatchEncoder.write(CommandBatchEncoder.java:45)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:83)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:130)
	at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:99)
	at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:55)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	... 23 more

io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at org.redisson.client.handler.CommandEncoder.write(CommandEncoder.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
	at org.redisson.client.handler.CommandBatchEncoder.write(CommandBatchEncoder.java:45)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:83)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:130)
	at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:99)
	at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:55)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	... 23 common frames omitted

When using redisTemplate set null, after the CommandEncoder NullPointerException occurs, there will inevitably be a ping exception

**Comment by hades-ruan** [comment]
2023-12-18 13:44:48.907 [  ]-[Async-1] ERROR c.z.i.c.u.RedisUtils:303 - redis hash multi set error
org.springframework.dao.QueryTimeoutException: Redis server response timeout (3000 ms) occured after 3 retry attempts, is non-idempotent command: false Check connection with Redis node: 192.168.2.232/192.168.2.232:6302 for TCP packet drops.  Try to increase nettyThreads and/or timeout settings. Command: (HMSET), params: [[105, 109, 95, 117, 115, 101, 114, 95, 115, 99, ...], [55, 55, 102, 54, 101, 57, 55, 100, 100, 55, ...], [53]], channel: [id: 0xa6fc30f1, L:/192.168.17.19:62756 - R:192.168.2.232/192.168.2.232:6302]; nested exception is org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 3 retry attempts, is non-idempotent command: false Check connection with Redis node: 192.168.2.232/192.168.2.232:6302 for TCP packet drops.  Try to increase nettyThreads and/or timeout settings. Command: (HMSET), params: [[105, 109, 95, 117, 115, 101, 114, 95, 115, 99, ...], [55, 55, 102, 54, 101, 57, 55, 100, 100, 55, ...], [53]], channel: [id: 0xa6fc30f1, L:/192.168.17.19:62756 - R:192.168.2.232/192.168.2.232:6302]
	at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:48)
	at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:35)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.redisson.spring.data.connection.RedissonConnection.transform(RedissonConnection.java:204)
	at org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:199)
	at org.redisson.spring.data.connection.RedissonConnection.sync(RedissonConnection.java:369)
	at org.redisson.spring.data.connection.RedissonConnection.write(RedissonConnection.java:735)
	at org.redisson.spring.data.connection.RedissonConnection.hMSet(RedissonConnection.java:1469)
	at org.springframework.data.redis.core.DefaultHashOperations.lambda$putAll$12(DefaultHashOperations.java:213)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:223)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:190)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:97)
	at org.springframework.data.redis.core.DefaultHashOperations.putAll(DefaultHashOperations.java:212)
	at com.zdxlz.im.common.utils.RedisUtils.hmset(RedisUtils.java:297)
	at com.zdxlz.im.biz.score.service.impl.MyServiceImpl.dealMyScore(MyServiceImpl.java:106)
	at com.zdxlz.im.biz.score.service.factory.server.LoginDealService.lambda$toDeal$2(LoginDealService.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 3 retry attempts, is non-idempotent command: false Check connection with Redis node: 192.168.2.232/192.168.2.232:6302 for TCP packet drops.  Try to increase nettyThreads and/or timeout settings. Command: (HMSET), params: [[105, 109, 95, 117, 115, 101, 114, 95, 115, 99, ...], [55, 55, 102, 54, 101, 57, 55, 100, 100, 55, ...], [53]], channel: [id: 0xa6fc30f1, L:/192.168.17.19:62756 - R:192.168.2.232/192.168.2.232:6302]
	at org.redisson.command.RedisExecutor.lambda$scheduleResponseTimeout$8(RedisExecutor.java:387)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted



After stringRedisTemplate set null, because a null pointer exception is thrown in the CommandEncode stage, the request is not sent, then there will definitely be no CommandDecoder stage, according to pipe The order of the line, CommandsQueue is executed before CommandEncoder, which also means that the set null  request instruction is stuffed into the queue, and it is pushed out of the queue without a decoding stage. As a result, in the command of the next set normal value , the request is sent to redis, and redis also responds. However, in the decoding stage, the operation instruction taken out is the previous request , so that the decoding exception is abnormal, and because it is taken out at this time. The instruction of one operation  and the second instruction  are still waiting for the next time to be taken out of the queue and processed (promise.tryFailure), resulting in a normal set  timeout. Since then, all subsequent requests will have errors, because the QueueCommand taken out in the decoding stage is always the last request until the PinConnectionHandler makes an error and disconnects the connection. Reset the data of the whole channel under the same processing.

**Comment by hades-ruan** [comment]
@mrniko

**Comment by mrniko** [comment]
Fixed in 3.19.2 version.

**Comment by Muscleape** [comment]
After upgrading my redisson version from 3.18.1 to 3.19.2, I still get this exception
<img width="1235" alt="image" src="https://github.com/redisson/redisson/assets/16682039/2d60b444-b8ed-47d0-94f7-827efb77f92d">

**Comment by mrniko** [comment]
`Command execution timeout for command: (PING)` was fixed in 3.24.1 version
