### ISSUE TITLE
NullPointerException in ClusterConnectionManager

### ISSUE THREAD

**Issue by barreeeiroo** [redisson/redisson#6050]
### Redis version

6.2.6

### Redisson version

3.32.0

### Redisson configuration

```
        Config config = new Config();

        // Codec for json <-> java object serialization/deserialization
        config.setCodec(new JsonJacksonCodec(objectMapper));

        // Only one node of cluster configuration endpoint need to be specified - all other nodes are auto detected
        // SLAVE - Read from slave nodes, uses MASTER if no SLAVES are available.
        // MASTER - Read from master node,
        // MASTER_SLAVE - Read from master and slave nodes
        config.useClusterServers()
                .setReadMode(ReadMode.MASTER_SLAVE)
                .addNodeAddress(redisUrl)
                .setTimeout(500)
                .setRetryAttempts(2)
                .setRetryInterval(50)
                .setConnectTimeout(10000);

        return Redisson.create(config);
```

### What is the Actual behavior?

A `NullPointerException` is thrown by Redisson:

```
23 Jul 2024 22:13:18,296 [ERROR]  (redisson-netty-5-7) org.redisson.cluster.ClusterConnectionManager: null java.lang.NullPointerException: null|   
   at java.util.Objects.requireNonNull(Objects.java:209 undefined) ~[?:?]|  
   at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180 undefined) ~[?:?]|
   at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169 undefined) ~[?:?]| 
   at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779 undefined) ~[?:?]|  
   at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509 undefined) ~[?:?]|   
   at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499 undefined) ~[?:?]|
   at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921 undefined) ~[?:?]|  
   at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234 undefined) ~[?:?]|   
   at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682 undefined) ~[?:?]|  
   at org.redisson.cluster.ClusterConnectionManager.checkSlotsMigration(ClusterConnectionManager.java:750 undefined) ~[redisson-3.32.0.jar:?]|  
   at org.redisson.cluster.ClusterConnectionManager.lambda$updateClusterState$18(ClusterConnectionManager.java:500 undefined) ~[redisson-3.32.0.jar:?]| 
   at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863 undefined) ~[?:?]|  
   at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841 undefined) ~[?:?]|  
   at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510 undefined) ~[?:?]| 
   at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147 undefined) ~[?:?]|
   at org.redisson.connection.ServiceManager.lambda$resolveAll$1(ServiceManager.java:313 undefined) ~[redisson-3.32.0.jar:?]|   
   at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590 undefined) [netty-common-4.1.jar:4.1.111.Final]|  
   at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583 undefined) [netty-common-4.1.jar:4.1.111.Final]| 
   at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559 undefined) [netty-common-4.1.jar:4.1.111.Final]|   
   at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492 undefined) [netty-common-4.1.jar:4.1.111.Final]|  
   at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636 undefined) [netty-common-4.1.jar:4.1.111.Final]|
   at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625 undefined) [netty-common-4.1.jar:4.1.111.Final]|  
   at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:97 undefined) [netty-common-4.1.jar:4.1.111.Final]|
   at io.netty.resolver.InetSocketAddressResolver$2.operationComplete(InetSocketAddressResolver.java:84 undefined) [netty-resolver-4.1.jar:4.1.111.Final]|  
   at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590 undefined) [netty-common-4.1.jar:4.1.111.Final]|  
   at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583 undefined) [netty-common-4.1.jar:4.1.111.Final]| 
   at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559 undefined) [netty-common-4.1.jar:4.1.111.Final]|   
   at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492 undefined) [netty-common-4.1.jar:4.1.111.Final]|  
   at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636 undefined) [netty-common-4.1.jar:4.1.111.Final]|
   at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625 undefined) [netty-common-4.1.jar:4.1.111.Final]|  
   at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105 undefined) [netty-common-4.1.jar:4.1.111.Final]|   
   at io.netty.resolver.dns.DnsResolveContext$1.operationComplete(DnsResolveContext.java:263 undefined) [netty-resolver-dns-4.1.jar:4.1.111.Final]| 
   at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590 undefined) [netty-common-4.1.jar:4.1.111.Final]|  
   at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557 undefined) [netty-common-4.1.jar:4.1.111.Final]|   
   at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492 undefined) [netty-common-4.1.jar:4.1.111.Final]|  
   at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636 undefined) [netty-common-4.1.jar:4.1.111.Final]|
   at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625 undefined) [netty-common-4.1.jar:4.1.111.Final]|  
   at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105 undefined) [netty-common-4.1.jar:4.1.111.Final]|   
   at io.netty.resolver.dns.DnsNameResolver.trySuccess(DnsNameResolver.java:1028 undefined) [netty-resolver-dns-4.1.jar:4.1.111.Final]| 
   at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1121 undefined) [netty-resolver-dns-4.1.jar:4.1.111.Final]|  
   at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1098 undefined) [netty-resolver-dns-4.1.jar:4.1.111.Final]| 
   at io.netty.resolver.dns.DnsResolveContext.access$800(DnsResolveContext.java:69 undefined) [netty-resolver-dns-4.1.jar:4.1.111.Final]|   
   at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:530 undefined) [netty-resolver-dns-4.1.jar:4.1.111.Final]| 
   at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590 undefined) [netty-common-4.1.jar:4.1.111.Final]|  
   at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583 undefined) [netty-common-4.1.jar:4.1.111.Final]| 
   at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559 undefined) [netty-common-4.1.jar:4.1.111.Final]|   
   at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492 undefined) [netty-common-4.1.jar:4.1.111.Final]|  
   at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636 undefined) [netty-common-4.1.jar:4.1.111.Final]|
   at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625 undefined) [netty-common-4.1.jar:4.1.111.Final]|  
   at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105 undefined) [netty-common-4.1.jar:4.1.111.Final]|   
   at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:345 undefined) [netty-resolver-dns-4.1.jar:4.1.111.Final]|  
   at io.netty.resolver.dns.DnsQueryContext.finishSuccess(DnsQueryContext.java:336 undefined) [netty-resolver-dns-4.1.jar:4.1.111.Final]|   
   at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1384 undefined) [netty-resolver-dns-4.1.jar:4.1.111.Final]| 
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444 undefined) [netty-transport-4.1.jar:4.1.111.Final]|   
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420 undefined) [netty-transport-4.1.jar:4.1.111.Final]|   
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412 undefined) [netty-transport-4.1.jar:4.1.111.Final]| 
   at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103 undefined) [netty-codec-4.1.jar:4.1.111.Final]|   
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444 undefined) [netty-transport-4.1.jar:4.1.111.Final]|   
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420 undefined) [netty-transport-4.1.jar:4.1.111.Final]|   
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412 undefined) [netty-transport-4.1.jar:4.1.111.Final]| 
   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407 undefined) [netty-transport-4.1.jar:4.1.111.Final]|  
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440 undefined) [netty-transport-4.1.jar:4.1.111.Final]|   
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420 undefined) [netty-transport-4.1.jar:4.1.111.Final]|   
   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918 undefined) [netty-transport-4.1.jar:4.1.111.Final]|   
   at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97 undefined) [netty-transport-4.1.jar:4.1.111.Final]|
   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788 undefined) [netty-transport-4.1.jar:4.1.111.Final]|
   at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724 undefined) [netty-transport-4.1.jar:4.1.111.Final]|  
   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650 undefined) [netty-transport-4.1.jar:4.1.111.Final]|   
   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562 undefined) [netty-transport-4.1.jar:4.1.111.Final]|   
   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994 undefined) [netty-common-4.1.jar:4.1.111.Final]|  
   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74 undefined) [netty-common-4.1.jar:4.1.111.Final]| 
   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30 undefined) [netty-common-4.1.jar:4.1.111.Final]| 
   at java.lang.Thread.run(Thread.java:840 undefined)
```

Seems to be happening in this line:

```
        // https://github.com/redisson/redisson/issues/3635
        Map<String, MasterSlaveEntry> nodeEntries = clusterLastPartitions.stream().collect(Collectors.toMap(p -> p.getNodeId(),
                                                                                    p -> getEntry(p.getSlotRanges().iterator().next().getStartSlot())));
```

But not sure exactly where the NPE is happening or how...

### Additional information

Redis Cluster hosted in AWS ElastiCache. Service is running on AWS ECS with a Private VPC.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/6048

**Comment by barreeeiroo** [comment]
Hi @mrniko, the fix didn't seem to resolve our actual issue. The NPE is "fixed", but there is some other issue affecting DNS failures for the master node in single-shard clusters.
I'll open a different issue with more stack traces; this other "bug" was introduced in 3.32.0 (3.31.0 is fine).

**Comment by mrniko** [comment]
Sorry, didn't see any words regarding DNS failures in the issue.

**Comment by barreeeiroo** [comment]
@mrniko sorry about that. We saw the NPE originally on Tuesday investigating the issue, but it was last night when we were able to actually isolate the issue and reproduce. See #6061, it has the steps to reproduce it.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/6061
