### ISSUE TITLE
Redisson changes master/slave on new ip addition for aws elasticsearch serverless endpoint

### ISSUE THREAD

**Issue by fcappi** [redisson/redisson#6278]
### Redis version

any

### Redisson version

3.38.1

### Redisson configuration

```java
Config config = new Config();
if (isCluster) {
  config.useClusterServers().addNodeAddress(redisAddress);
} else {
  config.useSingleServer().setAddress(redisAddress);
}
return Redisson.create(config).reactive();
```

Connecting to AWS elasticsearch Serverless

### What is the Expected behavior?

When connecting to AWS Elasticsearch serverless (Endpoint resolves to multiple IP), we expect that redisson will not change master/slave when new IP is added and current master IP is not removed.

In the example, I would expect  X.X.X.147 to be master/slave until it's removed.

### What is the Actual behavior?

Master is changed when new IP is added.

For instance, if there are 3 nodes like this:
X.X.X.166
X.X.X.33
X.X.X.147 (Selected as master)

And then, I new node is include x.x.x.107, it results in:
X.X.X.107 (Selected as master)
X.X.X.166
X.X.X.33
X.X.X.147 (Still in the list, but not master anymore)

### Additional information

It seems to be related to changes applied on https://github.com/redisson/redisson/issues/5621 and  https://github.com/redisson/redisson/issues/5621

The IP list sorting seems to be the problem. We always sort and then get index 0. Should we first check if current IP is still in the list and use it in this case?

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by fcappi** [comment]
Hi, I see we still have issues when using the SingleServer configuration. Should we apply the same fix to DNSMonitor class as well?

**Comment by mrniko** [comment]
Hi, it's implemented already https://github.com/redisson/redisson/blob/9d9a3a0ddd82f47d12f718d3319c0edcbd1d7f29/redisson/src/main/java/org/redisson/connection/DNSMonitor.java#L126-L133
