### ISSUE TITLE
NullPointerException in MasterConnectionPool if no entries in pool

### ISSUE THREAD

**Issue by Glurz** [redisson/redisson#6475]
### Redis version

7.2.5

### Redisson version

3.44.0

### Redisson configuration

Simple Single-Server-Config with default settings.

### What is the Expected behavior?

In MasterConnectionPool there's a get Method to retrieve connections from the pool. The expected behavior is, that this method deals with the case that 'entries' is empty.

```
    @Override
    public CompletableFuture<RedisConnection> get(RedisCommand<?> command, boolean trackChanges) {
        return acquireConnection(command, entries.peek(), trackChanges);
    }
```

### What is the Actual behavior?

The actual behavior is, that entries.peek() in MasterConnectionPool:51 returns null if entries is empty. This leads to a NullPointerException:

```
java.lang.NullPointerException: Cannot invoke "org.redisson.connection.ClientConnectionsEntry.getConnectionsHolder()" because "entry" is null
at org.redisson.connection.pool.MasterConnectionPool.getConnectionHolder(MasterConnectionPool.java:46)
at org.redisson.connection.pool.ConnectionPool.acquireConnection(ConnectionPool.java:114)
at org.redisson.connection.pool.MasterConnectionPool.get(MasterConnectionPool.java:51)
at org.redisson.connection.MasterSlaveEntry.connectionWriteOp(MasterSlaveEntry.java:564)
at org.redisson.command.RedisExecutor.connectionWriteOp(RedisExecutor.java:868)
at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:762)
at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:135)
at org.redisson.command.CommandAsyncService.evalAsync(CommandAsyncService.java:560)
at org.redisson.command.CommandAsyncService.evalWriteAsync(CommandAsyncService.java:450)
at org.redisson.RedissonScript.evalAsync(RedissonScript.java:255)
at org.redisson.RedissonScript.eval(RedissonScript.java:267)
at org.redisson.RedissonScript.eval(RedissonScript.java:82)
```

### Additional information

We did not research in detail what circumstances lead to an empty 'entries' queue, but it can happen and the code does not deal with such a situation properly.

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by Glurz** [comment]
@mrniko We've tried with a newer version (redisson-3.45.1) that contains your fix. The problem still occurs - the NPE now is being thrown from a different location:
```
java.lang.NullPointerException: Cannot invoke "org.redisson.connection.ClientConnectionsEntry.getConnectionsHolder()" because "entry" is null
at org.redisson.connection.pool.MasterConnectionPool.getConnectionHolder(MasterConnectionPool.java:47),  
at org.redisson.connection.pool.ConnectionPool.acquireConnection(ConnectionPool.java:104)
at org.redisson.connection.pool.MasterConnectionPool.get(MasterConnectionPool.java:52)
at org.redisson.connection.MasterSlaveEntry.connectionWriteOp(MasterSlaveEntry.java:552)
at org.redisson.command.RedisExecutor.connectionWriteOp(RedisExecutor.java:869)
at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:763)
at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:135)
at org.redisson.command.CommandAsyncService.evalAsync(CommandAsyncService.java:565)
at org.redisson.command.CommandAsyncService.evalWriteAsync(CommandAsyncService.java:450)
at org.redisson.RedissonScript.evalAsync(RedissonScript.java:255)
at org.redisson.RedissonScript.eval(RedissonScript.java:267)
at org.redisson.RedissonScript.eval(RedissonScript.java:82)
```
In `MasterConnectionPool:52`, `masterSlaveEntry.getEntry()` can return `null` under some circumstances.

I suspect that the problem occurs when the Redisson client is used while it is still initializing. Could be some kind of race condition.

**Comment by mrniko** [comment]
@Glurz 

Thanks for your feedback. Is there any code to reproduce it?

**Comment by Glurz** [comment]
@mrniko 
Unfortunately not. It occurs infrequently in a large set of nightly system tests. I have no isolated unit test that shows the behavior. 
I see in the code that there is a concept of "initialization" in MasterSlaveEntry. It seems like the redisson client answers requests before it is fully initialized. Maybe a synchronization / multi-threading issue?

**Comment by mrniko** [comment]
> It seems like the redisson client answers requests before it is fully initialized.

How it can be if by default initialization is made during "Redisson.create()" method invocation. Do you use a `lazyInitialization` setting?

**Comment by Glurz** [comment]
No, we don't use the lazyInitialization setting. Our RedissonClient is configured as follows:
`Config redissonConfig = new Config()
			.setUseScriptCache(true); // This setting has only advantages. The only reason to deactivate it would be if it interferes with our own script management (currently non-existent).

		SingleServerConfig singleServerConfig = redissonConfig.useSingleServer();

		singleServerConfig
			.setSslVerificationMode(verifyServerHostname ? SslVerificationMode.STRICT : SslVerificationMode.NONE)
			.setAddress(redisUri)
			.setConnectionMinimumIdleSize(minimumIdleConnections)
			.setConnectionPoolSize(maximumPoolSize)
			.setConnectTimeout(connectionTimeoutInMs)
			.setIdleConnectionTimeout(idleTimeoutInMs)
			.setTimeout(responseTimeoutInMs)
			.setPingConnectionInterval(pingConnectionIntervalInMs)
			.setUsername(username)
			.setPassword(password)
			.setSslTruststore(toUrl(trustStorePath))
			.setSslTruststorePassword(trustStorePassword)
			.setSslKeystore(toUrl(keyStorePath))
			.setSslKeystorePassword(keyStorePassword)
			.setSslProtocols(new String[] {"TLSv1.3", "TLSv1.2"}); // no need to make this configurable - these are the only two secure versions

		try {
			return Redisson.create(redissonConfig);
		} catch (RedisConnectionException e) {
			LOG.fatal(REDIS_ACCESS, e.getMessage());
			throw e;
		}`

I had a look at the code. After construction, instances of `MasterSlaveEntry` have an uninitialized `masterEntry` field. I guess this is the root of the problem. If your code does not properly prevent other threads from accessing such instances, the NPE will occur. Eventually, `org.redisson.connection.MasterSlaveEntry#setupMasterEntry(org.redisson.client.RedisClient)` will initialize the `masterEntry` field - but that happens asynchronously. 
The NPE proves that `MasterSlaveEntry` instances with an uninitialized `masterEntry` field are given out to consumers.

**Comment by seakider** [comment]
The problem you're describing is more like another thread has started trying to use redisson at the same time you're calling Redisson.create to initialize redisson.

If that's the case, then this problem is definitely happening. The initialization of redisson should be done in the same way as the application initialization is done in the main thread before the other thread can make use of it.

Alternatively, you can try setting lazyInitialization = true to fix this.

Translated with [DeepL.com](https://www.deepl.com/?utm_campaign=product&utm_source=web_translator&utm_medium=web&utm_content=copy_free_translation) (free version)

**Comment by Glurz** [comment]
@mrniko I put some further effort into this.
My assumption is that we are dealing with a race condition during the initialization of `masterEntry` in `MasterSlaveEntry`. As an experiment, I changed this code fragment (in `MasterSlaveEntry.setupMasterEntry(RedisClient client)`)
```
            return CompletableFuture.allOf(futures.toArray(new CompletableFuture[0]))
                    .thenApply(r -> {
                        masterEntry = entry; // <-- suspicious, master is initially null

                        if (!config.isSlaveNotUsed()) {
                            addSlaveEntry(masterEntry);
                        }
                        return client;
                    });
```
to this:
```
            return CompletableFuture.allOf(futures.toArray(new CompletableFuture[0]))
                    .thenApply(r -> {
                        try {
                            Thread.sleep(5000); // <-- added sleep to increase chance of NPE
                        } catch (InterruptedException e) {
                            throw new RuntimeException(e);
                        }
                        masterEntry = entry;

                        if (!config.isSlaveNotUsed()) {
                            addSlaveEntry(masterEntry);
                        }
                        return client;
                    });
```
This simulates a slow initialization of the asynchronous logic in `MasterSlaveEntry`. With that `sleep` in place, I noticed that the Test `org.redisson.rx.RedissonBatchRxTest#testConnectionLeakAfterError` fails with a stack trace that looks very similar to the stack trace posted above:

```
...
Caused by: java.lang.NullPointerException: Cannot invoke "org.redisson.connection.ClientConnectionsEntry.getConnectionsHolder()" because "entry" is null
	at org.redisson.connection.pool.MasterConnectionPool.getConnectionHolder(MasterConnectionPool.java:47)
	at org.redisson.connection.pool.ConnectionPool.acquireConnection(ConnectionPool.java:104)
	at org.redisson.connection.pool.MasterConnectionPool.get(MasterConnectionPool.java:52)
	at org.redisson.connection.MasterSlaveEntry.connectionWriteOp(MasterSlaveEntry.java:560)
	at org.redisson.command.RedisExecutor.connectionWriteOp(RedisExecutor.java:876)
	at org.redisson.command.RedisQueuedBatchExecutor.lambda$getConnection$3(RedisQueuedBatchExecutor.java:230)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.redisson.command.RedisQueuedBatchExecutor.getConnection(RedisQueuedBatchExecutor.java:227)
...
```
Does this help you to track down the suspected bug further?

**Comment by Glurz** [comment]
@mrniko, @seakider: Did you have a chance to look into my suggestion? Thanks for your efforts!

**Comment by seakider** [comment]
I think your simulation is incorrect.

the Test `org.redisson.rx.RedissonBatchRxTest#testConnectionLeakAfterErrorcase `case uses `@Timeout(4)`, which causes it to reach 4 seconds when `Redisson.create(config)` initialization process, the below code in `MasterSlaveConnectionManager#doConnect` method  will catch the interrupt exception, 

>             CompletableFuture<RedisClient> masterFuture = masterSlaveEntry.setupMasterEntry(uri, hostname);
>             try {
>                 if (config.getMasterConnectionMinimumIdleSize() == 0) {
>                     masterFuture.join();
>                 } else {
>                     masterFuture.get(config.getConnectTimeout()*config.getMasterConnectionMinimumIdleSize(), TimeUnit.MILLISECONDS);
>                 }
>             } catch (InterruptedException e) {
>                 Thread.currentThread().interrupt();
>             } catch (ExecutionException | TimeoutException e) {
>                 throw new RedisConnectionException(e);
>             }


the interrupt exception is not thrown the code continues to execute, and at this point, due to your modification, the masterEntry is null, it will throw a null pointer when acquireConnection.

However, under normal usage, slow initialization may cause the `masterFuture.get()` in the above referenced code to time out, a timeout exception will be thrown, and the initialization process will fail with no subsequent operations.

**Comment by Glurz** [comment]
@seakider : Thanks for your analysis. Is this an issue you can fix in the near future?

**Comment by seakider** [comment]
What I mean is that the incorrect simulation caused this exception to be generated. We still don't know how normal usage would get an uninitialized Redisson instance causing this problem.

**Comment by Glurz** [comment]
@seakider Maybe the simulation is incorrect, however it manages to reproduce the exact stack-trace that we regularly observe in our application. The bug is real and looking at the code, there's effectively no guarantee that the masterEntry field is initialized before the RedissonClient is being used.

**Comment by mrniko** [comment]
@Glurz 

`MasterSlaveEntry#setupMasterEntry(org.redisson.client.RedisClient)` method guarantees that in case of any error it will be propagated to the client and RedissonClient instance won't be created.

**Comment by Glurz** [comment]
@mrniko I do agree that the problem is not obvious and unfortunately, I don't know how to reproduce the issue reliably with a simple unit test. However I do see that the problem occurs almost every night in our automated system tests and the stack trace shows that `masterEntry` can in fact be `null`.

**Comment by mrniko** [comment]
@Glurz 

We need more information to reproduce it.

**Comment by nhancdt2602** [comment]
@mrniko  I did encounter this problem once in scheduled test pipeline. The root cause lies in this catch block
```
catch (InterruptedException e) {
            Thread.currentThread().interrupt();
}
```
It silently swallows the exception without propagating that exception to an upper layer. It usually occurs during testing but not production phase. As in testing we normally limit the duration a test can run. If test running time exceeds a duration threshold, and `masterEntry` is not initialized yet, the above catch block is reached and then leaves `masterEntry` be `null`. The timing scenarios is as follow:

```
Given:
- Test time limit = 3s
- Redisson.create takes 4s
─────────────────────────────────────────────────────────────────────
t=        0s          1s          2s          3s          4s
          │           │           │           │           │
          ▼           │           │           │           │
Redisson.create() ────┼───────────┼───────────┼──────────►│ (takes 4s to fully setup),
          │           │           │           │           │  blocked > 3s)
          │           │           │           │           │
          │      masterEntry      │           │           │
          │      init starts      │           │           │
          │           │           │           │           │
          │           │           │           ▼           │
          │           │           │      INTERRUPT        │
          │           │           │      (timeout)        │
          │           │           │           │           │
          │           │           │           ▼           │
          │           │           │    catch(Interrupted  │
          │           │           │      Exception e) {   │
          │           │           │      interrupt()      │
          │           │           │    }  ← swallowed     │
          │           │           │           │           │
          │           │           │           ▼           │
          │           │           │    masterEntry = null │
          │           │           │    (init incomplete)  │
          │           │           │           │           │
          │           │           │           ▼           │
          │           │           │    test continues     │
          │           │           │    accessing client   │
          │           │           │           │           │
          │           │           │           ▼           │
          │           │           │    NullPointerExcep-  │
          │           │           │    tion               │
─────────────────────────────────────────────────────────────────────
```

Here is a minimum reproducible script

```java
package org.redisson;

import org.redisson.api.RAtomicLong;
import org.redisson.api.RedissonClient;
import org.redisson.config.Config;

import java.util.concurrent.atomic.AtomicBoolean;

public class Main {
    public static void main(String[] args) throws InterruptedException {

        final int NUM_RUN = 100;
        AtomicBoolean hasException = new AtomicBoolean();
        for (int i = 0; i < NUM_RUN; i++) {
            if (hasException.get()) break;
            Thread t1 = new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        Config config = new Config();
                        config.useSingleServer()
                                .setAddress("redis://127.0.0.1:6379")
                                .setRetryAttempts(1);

                        RedissonClient client = Redisson.create(config);
                        System.out.println("Redisson client is initialized");
                        RAtomicLong myLong = client.getAtomicLong("myLong");
                        long result = myLong.incrementAndGet();
                        System.out.println("myLong=" + result);
                    } catch (Exception e) {
                        e.printStackTrace();
                        hasException.set(true);
                    }

                }
            });

            t1.start();

            Thread t2 = new Thread(new Runnable() {
                @Override
                public void run() {
                    t1.interrupt();
                }
            });

            t2.start();

            t1.join();;
            t2.join();
        }
    }
}
```

# Recommended Fix
Should not swallow `InterruptedException` but re-throw it to uppercase during `connect`. If this fix makes sense and worthy, I am open to make a pull request.

**Comment by leonroars** [comment]
Hi, I've been following this issue and was able to reproduce the NPE on 4.3.0.

I also found the same silent `InterruptedException` pattern in a few other places within `MasterSlaveConnectionManager` (lines 205, 249, 263, 647) that could be addressed together.

After checking the current code convention, I noticed that incomplete initialization failures in `ConnectionsHolder.createConnection()` are already handled by wrapping in `RedisConnectionException` → `CompletionException`. The `InterruptedException` catch blocks could follow the same pattern to ensure initialization failure is properly propagated to the caller.

@nhancdt2602 If you're somehow not planning to submit a PR, I'd be happy to take it on. But tbh, I've learnt so much about this project and root cause tracking from your solution and comment. Much appreciate for you.

**Comment by nhancdt2602** [comment]
@leonroars glad to hear your review. I prefer being in charge of this issue as I also found some potential related bugs if lazy is enabled. Once I created a PR, I am welcome you to have a look and submit changes if needed

**Comment by mrniko** [comment]
@nhancdt2602 

Thanks for the details. Could you make a PR with a test covering issue?

**Comment by nhancdt2602** [comment]
@mrniko Of course. No problem

**Comment by Glurz** [comment]
@nhancdt2602 Thanks for your fix!
@mrniko Do you see a chance to backport the fix also to redisson 3.x? Due to a breaking change in redissons yaml config format with 4.x, we're currently unable to migrate to redisson 4.x. Thanks for considering this.

**Comment by mrniko** [comment]
@Glurz 

Unfortunately, no. 3.x version was deprecated.
