### ISSUE TITLE
Configured Timeout in ElasticCacheServerConfig being ignored

### ISSUE THREAD

**Issue by tankchintan** [redisson/redisson#677]
Hello,
I am using Redisson library version *2.2.4*. I have the following settings configured for when I want to create a Redisson Client object for connecting to the datastore. 

```      
"elasticacheServersConfig": {
    "nodeAddresses": [
          "//XXX.001.cache.amazonaws.com:6379",
          "//XXX.002.cache.amazonaws.com:6379"
     ],
    "timeout": 3000
}
```
As you can see from the above settings I am setting the `timeout` explicitly to be 3 seconds. But I am seeing exceptions in the log which says mentions 1 second timeout. Here is the exception,
```
error: org.redisson.client.RedisTimeoutException: Redis server response timeout (1000 ms) occured for command: (GET) with params: [XXXXX] channel: [id: 0x002202e0, L:/172.17.0.160:43221 - R://XXX.002.cache.amazonaws.com/10.169.226.201:6379]
        at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:528)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:588)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:662)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:385)
        at java.lang.Thread.run(Thread.java:745)
```

I am wondering how is this is possible? Also I think there is also auto-retry feature in Redisson, which defaults to 3 attempts. Then why would this happen?

Can I provide some more info to debug this issue?

**Comment by mrniko** [comment]
It's strange. You could point a debugger to CommandAsyncService:453 to ensure that correct value is used.

**Comment by tankchintan** [comment]
@mrniko I actually printed the `Config` object before it is used to create the `RedissonClient`.Below is the output,
```
singleServerConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 1000
  timeout: 1000
  retryAttempts: 3
  retryInterval: 1000
  reconnectionTimeout: 3000
  failedAttempts: 3
  subscriptionsPerConnection: 5
  address:
  - "//127.0.0.1:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 5
  connectionPoolSize: 100
  database: 0
  dnsMonitoring: false
  dnsMonitoringInterval: 5000
threads: 0
useLinuxNativeEpoll: false
```
I know this says Single Server Config, but I get same for ElastiCacheServer Config.

**Comment by johnou** [comment]
@mrniko maybe this was fixed with https://github.com/redisson/redisson/commit/047aa60daebaa9e5920227cbd9693e052aae85b5

**Comment by mrniko** [comment]
@tankchintan have you tried version from master branch?

**Comment by tankchintan** [comment]
@mrniko Yeah, actually we are pushing Redisson v3.0.0 to production today so we will know soon.

**Comment by mrniko** [comment]
@tankchintan But `Timer initialization` problem was fixed in 3.0.1

**Comment by johnou** [comment]
@tankchintan highly recommend you don't put 3.0.0 in production, reconnection is broken for elasticache.

**Comment by tankchintan** [comment]
Ok @johnou @mrniko Will be deploying `3.0.1`

**Comment by tankchintan** [comment]
@mrniko @johnou I dont think `3.0.1` has landed in maven repository yet.

```
[ERROR] Failed to execute goal on project pm-workflow: Could not resolve dependencies for project com.ooyala.pm.workflow:pm-workflow:pom:0.0.1-SNAPSHOT: Could not find artifact org.redisson:redisson:jar:3.0.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]```

**Comment by mrniko** [comment]
@tankchintan all we can do is just waiting for its appearance. I have published it several hours ago. Appearance in maven central might take up to 6-12 hours.

**Comment by johnou** [comment]
@tankchintan it's there https://repo1.maven.org/maven2/org/redisson/redisson/3.0.1/ try again?

**Comment by tankchintan** [comment]
@mrniko @johnou I think we can close this ticket for now & if I see the issue persists I will re-open. Thanks!
