### ISSUE TITLE
URIBuilder seems not to be thread safe

### ISSUE THREAD

**Issue by ebersb** [redisson/redisson#828]
We test this in case of a multi cluster setup and sometimes went the java.net.URL.factory to null instead of the original factory.

Scenario:
Thread 1
replaceURLFactory
	currentFactory is original value
start create URL

Thread 2
replaceURLFactory
	currentFactory == newFactory -> currentFactory = null
start create URL

Thread 1 and 2
restoreURLFactory
	set URL.factory to null

Next “new URL(…)” from different call cause to load new handlers.

Best,
  ebersb

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/798

**Comment by ebersb** [comment]
Sorry, I forgot to add the used version: 3.3.2
#789 does not fix this issue. In #789 are the methods replaceURLFactory and restoreURLFactory set to synchronized. This fixed the issues with the exceptions thrown from URL.setURLStreamHandlerFactory.
This issue describes the scenario where the URL.factory is null when two concurrent threads like to create an new URL with the URLBuilder.
I try to create a pull request later.
Thanks,
    ebersb

**Comment by mrniko** [comment]
> I try to create a pull request later.

OK, I'm looking forward to it
