### ISSUE TITLE
Cache ops taking too long

### ISSUE THREAD

**Issue by diogonicoleti** [redisson/redisson#899]
Currently i'm using Redisson 2.7.4  as JCache Provider, and some cache operations are taking a long time to execute, as can be seen in the log below:
```
2017-06-05 11:44:18.103 WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 89) Cache result for CompanyDemoFindService.find took 1669045 milliseconds
``` 
in some cases it takes **~30 minutes**

Taking a thread dump I noticed that all EJB async threads (and some http-executor threads too) were in the same state, generating a huge queue in the async thread pool:

![captura de tela 2017-06-05 as 11 34 11](https://cloud.githubusercontent.com/assets/4973742/26793748/82c1b376-49f5-11e7-9d14-29064737adca.png)

Thread dump for some threads (Complete thread dump can be downloaded [here](https://github.com/redisson/redisson/files/1052564/thread-dump.txt)):
```
2017-06-05 11:03:55

"EJB async - 2" - Thread t@1214
   java.lang.Thread.State: TIMED_WAITING
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for <b485fd6> (a java.util.concurrent.Semaphore$NonfairSync)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1033)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)
	at java.util.concurrent.Semaphore.tryAcquire(Semaphore.java:414)
	at org.redisson.RedissonLock.lockInterruptibly(RedissonLock.java:133)
	at org.redisson.RedissonLock.lock(RedissonLock.java:99)
	at org.redisson.jcache.JCache.getLockedLock(JCache.java:746)
	at org.redisson.jcache.JCache.get(JCache.java:194)
	at com.contaazul.cache.FailSafeCache.get(FailSafeCache.java:21)
	at org.jsr107.ri.annotations.AbstractCacheResultInterceptor.cacheResult(AbstractCacheResultInterceptor.java:71)
	at com.contaazul.cache.cdi.interceptor.CacheResultInterceptor.cacheResult(CacheResultInterceptor.java:28)
	at sun.reflect.GeneratedMethodAccessor141.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.weld.interceptor.proxy.SimpleMethodInvocation.invoke(SimpleMethodInvocation.java:30)
	at org.jboss.weld.interceptor.proxy.SimpleInterceptionChain.invokeNextInterceptor(SimpleInterceptionChain.java:69)
	at org.jboss.weld.bean.InterceptorImpl.intercept(InterceptorImpl.java:92)
	at org.jboss.as.weld.ejb.DelegatingInterceptorInvocationContext.proceed(DelegatingInterceptorInvocationContext.java:71)
	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.delegateInterception(Jsr299BindingsInterceptor.java:72)
	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:84)
	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:97)
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53)
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:73)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:21)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
	at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:53)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInNoTx(CMTTxInterceptor.java:259)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.notSupported(CMTTxInterceptor.java:323)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:236)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:59)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:55)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ee.component.TCCLInterceptor.processInvocation(TCCLInterceptor.java:45)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
	at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:185)
	at org.jboss.as.ee.component.ViewDescription$1.processInvocation(ViewDescription.java:182)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
	at org.jboss.as.ee.component.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:73)
	at com.contaazul.company.CompanyDemoFindService$$$view659.find(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor146.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.weld.util.reflection.SecureReflections$13.work(SecureReflections.java:267)
	at org.jboss.weld.util.reflection.SecureReflectionAccess.run(SecureReflectionAccess.java:52)
	at org.jboss.weld.util.reflection.SecureReflectionAccess.runAsInvocation(SecureReflectionAccess.java:137)
	at org.jboss.weld.util.reflection.SecureReflections.invoke(SecureReflections.java:263)
	at org.jboss.weld.bean.proxy.EnterpriseBeanProxyMethodHandler.invoke(EnterpriseBeanProxyMethodHandler.java:115)
	at org.jboss.weld.bean.proxy.EnterpriseTargetBeanInstance.invoke(EnterpriseTargetBeanInstance.java:56)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:105)
	at com.contaazul.company.CompanyDemoFindService$Proxy$_$$_Weld$Proxy$.find(CompanyDemoFindService$Proxy$_$$_Weld$Proxy$.java)
	at com.contaazul.fanout.ApplicationTrackService.resolveOrigin(ApplicationTrackService.java:161)
	at com.contaazul.fanout.ApplicationTrackService.getContentDTO(ApplicationTrackService.java:131)
	at com.contaazul.fanout.ApplicationTrackService.sendTrack(ApplicationTrackService.java:104)
	at com.contaazul.fanout.ApplicationTrackService.sendTrackOperation(ApplicationTrackService.java:72)
	at com.contaazul.fanout.ApplicationTrackService.track(ApplicationTrackService.java:48)
	at sun.reflect.GeneratedMethodAccessor565.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53)
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:374)
	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:86)
	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:97)
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53)
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:93)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:21)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
	at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:53)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInNoTx(CMTTxInterceptor.java:259)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.notSupported(CMTTxInterceptor.java:323)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:236)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:59)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:55)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ee.component.TCCLInterceptor.processInvocation(TCCLInterceptor.java:45)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
	at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:185)
	at org.jboss.as.ee.component.ViewDescription$1.processInvocation(ViewDescription.java:182)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.interceptors.AsyncFutureInterceptorFactory$1$1.runInvocation(AsyncFutureInterceptorFactory.java:89)
	at org.jboss.as.ejb3.component.interceptors.AsyncInvocationTask.run(AsyncInvocationTask.java:73)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:122)

   Locked ownable synchronizers:
	- locked <f75019a> (a java.util.concurrent.ThreadPoolExecutor$Worker)


"redisson-3-9" - Thread t@1416
   java.lang.Thread.State: WAITING
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for <2d3b7977> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None


"redisson-netty-1-9" - Thread t@1297
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <7ed0d3e3> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <130940b7> (a java.util.Collections$UnmodifiableSet)
	- locked <4eab503d> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:746)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None
```

it looks like that is a lock issue, but i don't know how to solve it.

**Comment by diogonicoleti** [comment]
My currently `redisson-jcache.yaml`:
```yaml
---
elasticacheServersConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 5000
  timeout: 1000
  retryAttempts: 2
  retryInterval: 1000
  reconnectionTimeout: 2000
  failedAttempts: 2
  password: null
  clientName: appcache
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionsPerConnection: 5
  slaveSubscriptionConnectionMinimumIdleSize: 10
  slaveSubscriptionConnectionPoolSize: 100
  slaveConnectionMinimumIdleSize: 5
  slaveConnectionPoolSize: 50
  masterConnectionMinimumIdleSize: 10
  masterConnectionPoolSize: 100
  readMode: "SLAVE"
  nodeAddresses:
  - "redis://redis-master.domain.local:6379"
  - "redis://redis-slave1.domain.local:6379"
  scanInterval: 1000
threads: 20
nettyThreads: 20
codec: !<org.redisson.codec.JsonJacksonCodec> {}
useLinuxNativeEpoll: false
```

**Comment by mrniko** [comment]
Hi! This issue has been resolved in 1261497a7e055debb8df0544dd7bac937bad9b60. We use lock object here to maintain consistency.

**Comment by diogonicoleti** [comment]
Thanks @mrniko! I'll update redisson to `2.9.2`

**Comment by diogonicoleti** [comment]
@mrniko i upgraded to version `2.9.2` but the problem persists.

**Comment by mrniko** [comment]
still waiting 30 minutes?

**Comment by diogonicoleti** [comment]
@mrniko it's a little better but slow yet. Up to now, the slowest operation took `356847` milliseconds (~6 minutes):
```
2017-06-06 14:17:13,701 WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 52) Cache result for CompanyDemoFindService.find took 356847 milliseconds
```

**Comment by mrniko** [comment]
@diogonicoleti `get` operation? It's strange this means some client not releasing lock properly, or delay in operation execution.

**Comment by diogonicoleti** [comment]
yes, it's a [ `cache.get(key)` ](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/jcache/JCache.java#L188) call.

**Comment by diogonicoleti** [comment]
I was monitoring Redis entries for `*:key` keys for a while and observed that some hashes remain stored for a long time:

<img width="550" alt="captura de tela 2017-06-06 as 13 40 42" src="https://user-images.githubusercontent.com/4973742/26855225-38982e82-4af0-11e7-9d26-149a69acefbe.png">

while another hashes were deleted correctly

**Comment by mrniko** [comment]
> I was monitoring Redis entries for *:key keys for a while and observed that some hashes remain stored for a long time:

We can't remove them immediately right at expiration time, anyway you won't see their entries in Redisson if they have been expired already.

**Comment by diogonicoleti** [comment]
@mrniko today I had worse cases (**~16,8 hours**), all them on the same server and user, as can seen in the log below:
```
09:03:00,407 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 35) Cache result for CompanyFeatureService.retrieve took 60439881 milliseconds
09:03:00,419 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 148) Cache result for CompanyFeatureService.retrieve took 58407278 milliseconds
09:03:00,430 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 28) Cache result for CompanyFeatureService.retrieve took 60488896 milliseconds
09:03:00,453 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 278) Cache result for CompanyFeatureService.retrieve took 59753376 milliseconds
09:03:00,481 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 23) Cache result for CompanyFeatureService.retrieve took 58137209 milliseconds
09:03:00,528 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 1) Cache result for CompanyFeatureService.retrieve took 60500273 milliseconds
09:03:00,551 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 164) Cache result for CompanyFeatureService.retrieve took 60499365 milliseconds
09:03:00,564 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 256) Cache result for CompanyFeatureService.retrieve took 59483347 milliseconds
09:03:00,592 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 252) Cache result for CompanyFeatureService.retrieve took 58433896 milliseconds
09:03:00,603 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 286) Cache result for CompanyFeatureService.retrieve took 59954952 milliseconds
09:03:00,617 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 224) Cache result for CompanyFeatureService.retrieve took 60423461 milliseconds
09:03:00,632 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 153) Cache result for CompanyFeatureService.retrieve took 60235877 milliseconds
09:03:00,643 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 48) Cache result for CompanyFeatureService.retrieve took 56647501 milliseconds
09:03:00,658 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 238) Cache result for CompanyFeatureService.retrieve took 60224420 milliseconds
09:03:00,678 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 101) Cache result for CompanyFeatureService.retrieve took 60463601 milliseconds
09:03:00,690 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 261) Cache result for CompanyFeatureService.retrieve took 60272649 milliseconds
09:03:00,714 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 216) Cache result for CompanyFeatureService.retrieve took 60499609 milliseconds
09:03:00,728 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 208) Cache result for CompanyFeatureService.retrieve took 1573768 milliseconds
09:03:00,741 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 231) Cache result for CompanyFeatureService.retrieve took 56660274 milliseconds
09:03:00,761 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 43) Cache result for CompanyFeatureService.retrieve took 60499039 milliseconds
09:03:00,786 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 120) Cache result for CompanyFeatureService.retrieve took 1514829 milliseconds
09:03:00,799 +NIR1nchMY0FVyQuXZmbSm7B app-0ef57a935936679c4.domain.local WARN  [com.contaazul.cache.cdi.interceptor.CacheResultInterceptor] (http-executor-threads - 158) Cache result for CompanyFeatureService.retrieve took 60434334 milliseconds
```

I had to delete the locks on redis because the user could not log in the application.

I also took a snapshot of cache statistics:

<img width="623" alt="captura de tela 2017-06-07 as 09 16 47" src="https://user-images.githubusercontent.com/4973742/26878680-aff3dfb6-4b64-11e7-8c04-abdde390ce44.png">

**Comment by mrniko** [comment]
As far as I remember EJB specification is not recommend to call blocking methods Am I right?

**Comment by diogonicoleti** [comment]
@mrniko not for all. It's not recommend in some cases, like singleton or when you are using EJB with JTA transaction that determine a transaction timeout.

But in these cases I related I'm not using EJB, it's only managed bean (CDI). It uses a http thread, for a thread pool defined by web connector (in these case Apache tomcat) which runs until the request is finished.

**Comment by mrniko** [comment]
Some kind of issue related to thread management of EJB container. Because lock could be acquired for `16 hours` only in case then thread owned lock has been stopped during invocation but Redisson client is still works...

**Comment by diogonicoleti** [comment]
@mrniko any idea how we can solve it?

**Comment by mrniko** [comment]
I would start to research cause of such thread stop

**Comment by diogonicoleti** [comment]
@mrniko cool! I can help you in your research if you need. In case you need more details about our environment and codes snippets that we are using you can tell me.

**Comment by mrniko** [comment]
Sorry, I mean if I would you :)

**Comment by diogonicoleti** [comment]
@mrniko no problem, i'll investigate better the root cause for this issue. For me, it's no make sense that the server is stoping threads for no reason and don't logging error or something else.

Anyway I have to fork redisson and force a `leaseTime` of 5 seconds to solve for now https://github.com/diogonicoleti/redisson/commit/fc2ff1271d32a82716d240d4079219aa72d62481  because a have a major outage yesterday due to this issue :( All my http threads stayed waiting for a lock forever.

Maybe it would be interesting to have some mechanism to prevent indefinitely held locks.

**Comment by caarlos0** [comment]
@diogonicoleti @mrniko maybe some kind of config setting for a `maxLeaseTime` or something...

**Comment by mrniko** [comment]
Please use `Config.lockWatchdogTimeout ` parameter to control lock timeout. This param has been added in 3.4.3 version
